import { requireFounder } from "@/lib/auth/requireFounder";
import { OpsIndexSearchable, type OpsSection } from "@/components/OpsIndexSearchable";

export const metadata = { title: "Ops index — EquipSeva Founder Console" };
export const dynamic = "force-dynamic";

const SECTIONS: OpsSection[] = [
  {
    label: "Executive",
    links: [
      { href: "/founder-morning-cockpit", title: "Morning cockpit ★", desc: "Pulse + rates + outreach + integrity · 2-min daily review", round: "r872★" },
      { href: "/live-feed", title: "Live feed ★", desc: "Raw event stream across jobs/payouts/AMC/disputes/code-red (r950 milestone)", round: "r950★" },
      { href: "/cross-tabs-index", title: "Cross-tabs index ★", desc: "11 month × status surfaces in one place (r976 / PR #1600 milestone)", round: "r976★" },
      { href: "/platform-pulse", title: "Platform pulse", desc: "12 KPIs at a glance · executive snapshot", round: "r700★" },
      { href: "/dashboard", title: "Hero dashboard", desc: "Top-line KPIs + today vs yesterday", round: "r597+" },
    ],
  },
  {
    label: "Database health",
    links: [
      { href: "/db-storage", title: "DB storage", desc: "Per-table size · WoW growth", round: "r600+" },
      { href: "/index-health", title: "Index health", desc: "Unused + seq-scan-heavy", round: "r605" },
      { href: "/long-queries", title: "Long-running queries", desc: ">5s queries · idle-in-tx", round: "r604" },
      { href: "/slow-rpcs", title: "Slow RPCs", desc: "pg_stat_statements top 50", round: "r610" },
    ],
  },
  {
    label: "Security & audit",
    links: [
      { href: "/rls-coverage", title: "RLS coverage", desc: "Per-table RLS + grants + risk", round: "r603" },
      { href: "/audit", title: "Founder action log", desc: "Append-only audit ledger", round: "r482+" },
      { href: "/admin-actions-trend", title: "Admin actions trend", desc: "Daily founder_action_log volume", round: "r672" },
      { href: "/admin-top-ops", title: "Admin top ops", desc: "Most-used founder ops · 30d", round: "r673" },
      { href: "/audit-by-actor", title: "Audit by actor", desc: "Top 50 actors by founder_action_log volume", round: "r874" },
      { href: "/audit-trail-export", title: "Audit trail export ★", desc: "CSV download for compliance archive (r900 milestone)", round: "r900★" },
      { href: "/audit-actions-by-day", title: "Audit actions by day", desc: "30d founder action log volume + variety", round: "r929" },
      { href: "/audit-by-week", title: "Audit by week (13wk)", desc: "Manual ops workload trend per week", round: "r980" },
      { href: "/pending-kyc", title: "Pending KYC", desc: "Engineer verification queue", round: "r664" },
      { href: "/kyc-pending-detail", title: "KYC pending detail", desc: "100 oldest pending verifications + days-pending tone", round: "r956" },
      { href: "/open-disputes", title: "Open disputes", desc: "Submitted packs awaiting decision", round: "r665" },
      { href: "/disputes-recent", title: "Disputes recent", desc: "Last 100 packs (90d)", round: "r938" },
      { href: "/dispute-by-mediator", title: "Dispute by mediator", desc: "Top 50 mediators · decisions + accept/reject (90d)", round: "r942" },
      { href: "/spot-audits-summary", title: "Spot audits", desc: "Invitations · responses · ratings", round: "r682" },
      { href: "/spot-audit-rating-distribution", title: "Spot audit ratings", desc: "Per-rating histogram (180d)", round: "r822" },
      { href: "/spot-audit-by-engineer", title: "Spot audit by engineer", desc: "Engineers ranked by lowest avg rating (quality watch)", round: "r894" },
      { href: "/integrity-events", title: "Integrity events", desc: "Play Integrity + client self-report audit", round: "r846" },
      { href: "/security-overview", title: "Security overview ★", desc: "Anti-mod layer status + dirty events", round: "r850" },
      { href: "/grants-audit", title: "Grants audit", desc: "EXECUTE privileges on every founder_* RPC", round: "r852" },
      { href: "/reconciliation-health", title: "Reconciliation health", desc: "3-way recon cron firing audit · 12mo", round: "r857" },
      { href: "/tds-health", title: "TDS 194O health", desc: "TDS row coverage vs processed payouts · 12mo", round: "r858" },
    ],
  },
  {
    label: "Cash flow & integrations",
    links: [
      { href: "/escrow-aging", title: "Escrow aging", desc: "Live escrow by age × status", round: "r607" },
      { href: "/escrow-balance-rollup", title: "Escrow balance rollup", desc: "Per-status totals + oldest", round: "r650" },
      { href: "/escrow-stuck", title: "Escrow stuck >30d", desc: "Pending/held/dispute aged out", round: "r662" },
      { href: "/escrow-velocity", title: "Escrow velocity", desc: "Created → released p50/p90", round: "r674" },
      { href: "/webhooks", title: "Webhook health", desc: "Razorpay + payouts success", round: "r606" },
      { href: "/webhook-failures-recent", title: "Webhook failures recent", desc: "Last 100 unapplied events (7d)", round: "r881" },
      { href: "/webhook-success-rate", title: "Webhook success rate", desc: "% applied per source · 7/30d", round: "r931" },
      { href: "/payouts", title: "Engineer payouts", desc: "Queue · dead-letter · ops", round: "r428+" },
      { href: "/payout-latency", title: "Payout latency", desc: "Queued → processed time", round: "r624" },
      { href: "/payout-volume-30d", title: "Payout volume 30d", desc: "Per-status rupees", round: "r651" },
      { href: "/payouts-by-day-trend", title: "Payouts by day", desc: "Daily paid + failed (14d)", round: "r686" },
      { href: "/payouts-pending-list", title: "Payouts pending list", desc: "Top 100 pending oldest-first", round: "r837" },
      { href: "/payouts-failed-list", title: "Payouts failed list", desc: "Last 100 failed (30d)", round: "r838" },
      { href: "/payouts-recent-list", title: "Payouts recent (7d)", desc: "Last 100 with mode + UTR + status", round: "r946" },
      { href: "/payouts-rupees-by-day", title: "Payouts ₹ by day (30d)", desc: "Daily processed ₹ + failed + pending", round: "r879" },
      { href: "/payouts-by-month-by-status", title: "Payouts month × status", desc: "12mo queued/processing/processed/failed/cancelled", round: "r965" },
      { href: "/escrow-amount-at-risk", title: "Escrow ₹ at risk", desc: "Sum held bucketed by age", round: "r873" },
      { href: "/escrow-flow-by-day", title: "Escrow flow by day (30d)", desc: "Inflow vs released vs refunded daily", round: "r901" },
      { href: "/escrow-by-month-by-status", title: "Escrow month × status", desc: "12mo paid/released/refunded/disputed", round: "r964" },
      { href: "/payouts-net-of-tds", title: "Payouts net of TDS", desc: "Gross vs TDS withheld vs net paid", round: "r889" },
      { href: "/tds-deductions-recent", title: "TDS deductions recent", desc: "Last 100 with deposited flag", round: "r943" },
      { href: "/undeposited-tds", title: "Undeposited TDS ⚠️", desc: "TDS deducted but not yet sent to govt · compliance", round: "r944" },
      { href: "/payout-fail-reasons", title: "Payout fail reasons", desc: "RazorpayX status distribution", round: "r666" },
      { href: "/engineers-missing-payout", title: "Engineers missing payout", desc: "Earned 30d but no verified VPA · outreach queue", round: "r726" },
      { href: "/payout-method-coverage", title: "Payout method coverage", desc: "% of earning engineers with verified VPA · 7/30/90d", round: "r791" },
      { href: "/refunds", title: "Refunds", desc: "Refund authorizations + history", round: "—" },
      { href: "/commission-revenue-30d", title: "Commission revenue (30d)", desc: "Daily platform take (est)", round: "r663" },
      { href: "/commission-by-month", title: "Commission by month", desc: "12mo platform commission est. (7% take)", round: "r893" },
      { href: "/jobs-vs-amc-revenue", title: "Jobs vs AMC revenue", desc: "12mo monthly split + recurring revenue share %", round: "r902" },
      { href: "/weekly-revenue-summary", title: "Weekly revenue summary", desc: "13-week jobs + AMC + parts (3 streams)", round: "r932" },
      { href: "/monthly-revenue-summary", title: "Monthly revenue summary", desc: "12-month jobs + AMC + parts (3 streams)", round: "r933" },
      { href: "/amc-revenue-trend", title: "AMC revenue trend", desc: "Daily AMC paid orders (14d)", round: "r656" },
      { href: "/amc-revenue-by-tier", title: "AMC revenue by tier", desc: "Per-tier MRR + ARR", round: "r688" },
      { href: "/amc-payment-orders-status", title: "AMC payment orders status", desc: "Pending/paid/failed/refunded", round: "r667" },
      { href: "/amc-payment-success-rate", title: "AMC payment success rate", desc: "paid / (paid+failed) 7/30/90d", round: "r714" },
    ],
  },
  {
    label: "Growth & engagement",
    links: [
      { href: "/signups", title: "Signups + active users", desc: "Funnel + DAU/WAU/MAU", round: "r608+" },
      { href: "/weekly-kpis", title: "Weekly KPIs", desc: "WoW snapshot · 7 metrics", round: "r625" },
      { href: "/weekly-kpi-snapshot", title: "Weekly KPI snapshot", desc: "13wk time series · 8 raw KPIs", round: "r986" },
      { href: "/monthly-kpi-snapshot", title: "Monthly KPI snapshot", desc: "12mo time series · 8 raw KPIs", round: "r987" },
      { href: "/daily-kpi-snapshot", title: "Daily KPI snapshot", desc: "90d time series · completes the daily/weekly/monthly trio", round: "r989" },
      { href: "/amc-renewal-window-30d", title: "AMC renewal window 30d", desc: "Renewing next 30d × tier · MRR at risk", round: "r991" },
      { href: "/engineers-no-jobs-30d", title: "Engineer activation leak", desc: "Engineers w/ 0 completed jobs in 30/60/90d + never", round: "r992" },
      { href: "/hospitals-no-jobs-30d", title: "Hospital activation leak", desc: "Hospitals w/ 0 posted jobs in 30/60/90d + never (demand-side mirror)", round: "r993" },
      { href: "/payouts-stuck-aging", title: "Payouts stuck aging", desc: "Queued/processing payouts × age bucket × INR · &gt;7d = engineer trust at risk", round: "r994" },
      { href: "/code-red-aging", title: "Code Red aging", desc: "Open emergency requests × age bucket · &gt;4h = SLA breach", round: "r995" },
      { href: "/spare-parts-stuck-aging", title: "Spare parts stuck aging", desc: "Paid but unshipped orders × age bucket × INR · &gt;7d = buyer trust", round: "r996" },
      { href: "/jobs-unassigned-aging", title: "Jobs unassigned aging", desc: "Open jobs with no engineer × age bucket · marketplace liquidity signal", round: "r997" },
      { href: "/bids-stuck-aging", title: "Bids stuck aging", desc: "Submitted/pending bids no decision × age · engineer trust signal", round: "r998" },
      { href: "/escrow-held-aging", title: "Escrow held aging", desc: "Held escrow rows × age × INR · capital tied up", round: "r999" },
      { href: "/critical-cockpit", title: "Founder critical cockpit ★", desc: "12 cross-system aging/leak signals in one panel (r1000 milestone)", round: "r1000★" },
      { href: "/critical-actions", title: "Critical actions queue", desc: "Top items across payouts/Code Red/spare parts/escrow · with item-level IDs", round: "r1002" },
      { href: "/amc-renewal-funnel-90d", title: "AMC renewal funnel 90d", desc: "Stage 1→2→3 notify cadence → renewed/expired · % of due", round: "r1003" },
      { href: "/payout-success-funnel-90d", title: "Payout success funnel 90d", desc: "Queued → processing → processed/failed/still-queued · % of queued", round: "r1004" },
      { href: "/engineer-onboarding-funnel", title: "Engineer onboarding funnel", desc: "Signup → profile → verified → 1st bid → 1st job → 1st payout · % of signups", round: "r1005" },
      { href: "/hospital-onboarding-funnel", title: "Hospital onboarding funnel", desc: "Signup → profile → 1st job posted → 1st bid → 1st completed → 1st AMC", round: "r1007" },
      { href: "/equipment-type-breakdown", title: "Equipment type breakdown", desc: "90d jobs by equipment_type · total + completed + open + avg hrs to complete", round: "r1008" },
      { href: "/reviews-pending-aging", title: "Reviews pending aging", desc: "Completed jobs no hospital rating × age · engagement gap signal", round: "r1009" },
      { href: "/funnels-index", title: "Funnels index ★", desc: "Unified landing for all 8+ multi-stage funnel surfaces (r1010 sub-milestone)", round: "r1010★" },
      { href: "/amc-pool-zero-balance", title: "AMC pool zero balance × tier", desc: "Active AMCs at 0 pool balance × tier · blocked MRR · hospitals can't book free services", round: "r1011" },
      { href: "/kyc-pending-aging", title: "KYC pending aging", desc: "Engineers awaiting verification × age bucket · activation pipeline blocker", round: "r1012" },
      { href: "/gst-invoices-by-month-by-source", title: "GST invoices by month × source", desc: "12mo invoice volume × 6 source kinds + taxable/GST/invoice rupees", round: "r1014" },
      { href: "/platform-fee-revenue-by-month", title: "Platform fee revenue by month", desc: "12mo platform-fee taxable INR × 4 sources (repair/AMC visit/spare/AMC sub)", round: "r1015" },
      { href: "/notifications-engagement-30d", title: "Notifications engagement 30d", desc: "Daily sent/read + unread % · engagement health signal", round: "r1016" },
      { href: "/notifications-by-kind-30d", title: "Notifications by kind 30d", desc: "Per-kind sent/read/read-% · candidates to drop or rework", round: "r1017" },
      { href: "/audit-by-actor-30d", title: "Audit by actor 30d", desc: "Top 20 actors by founder_action_log volume + success/failure split", round: "r1018" },
      { href: "/audit-by-op-30d", title: "Audit by op 30d", desc: "Top 50 op_names · failed-heavy ops are candidates for retry/RPC fix", round: "r1019" },
      { href: "/audit-by-table-30d", title: "Audit by table 30d", desc: "Top 50 target_tables · completes audit trio (actor/op/table)", round: "r1020" },
      { href: "/audit-failed-events-30d", title: "Audit failed events 30d", desc: "Top 100 recent failed actions · security + reliability signal", round: "r1021" },
      { href: "/jobs-completion-latency-histogram", title: "Jobs completion latency histogram", desc: "90d completed jobs × 7 latency buckets · marketplace velocity signal", round: "r1022" },
      { href: "/spare-parts-by-supplier-30d", title: "Spare parts by supplier 30d", desc: "Top 50 suppliers × orders + paid + GMV · seller-side leaderboard", round: "r1023" },
      { href: "/engineer-leaderboard-30d", title: "Engineer leaderboard 30d", desc: "Top 50 engineers · jobs done + earnings + avg rating + tier", round: "r1024" },
      { href: "/hospital-leaderboard-30d", title: "Hospital leaderboard 30d", desc: "Top 50 hospitals · jobs posted + completed + spend + AMC count", round: "r1025" },
      { href: "/leaderboards-index", title: "Leaderboards index ★", desc: "4th meta-landing · Supply/Demand/Seller leaderboards in one place", round: "r1026★" },
      { href: "/agings-index", title: "Agings index ★", desc: "5th meta-landing · 9 aging surfaces grouped by severity (Trust/Liquidity/Pipeline/Engagement)", round: "r1027★" },
      { href: "/city-coverage", title: "City coverage", desc: "Top 50 cities · engineers + hospitals + jobs + active AMCs", round: "r1028" },
      { href: "/state-coverage", title: "State coverage", desc: "All states · engineers + verified + hospitals + active AMCs + MRR", round: "r1029" },
      { href: "/coverage-index", title: "Coverage index ★", desc: "6th meta-landing · geographic + chain coverage surfaces", round: "r1030★" },
      { href: "/amc-pool-burn-rate-by-tier", title: "AMC pool burn rate × tier", desc: "Per-tier 30d debit rate + months-to-zero projection", round: "r1031" },
      { href: "/failed-payouts-recent", title: "Failed payouts recent", desc: "Top 100 recent failed payouts × engineer × reason × age · action queue", round: "r1032" },
      { href: "/failed-payouts-by-reason", title: "Failed payouts by reason", desc: "Top 50 failure_reason patterns · systemic vs data-fix diagnosis", round: "r1033" },
      { href: "/audit-ops-by-day-30d", title: "Audit ops by day 30d", desc: "Daily ops count + success/fail + actors + distinct ops · founder activity time series", round: "r1034" },
      { href: "/amc-revenue-projection", title: "AMC revenue projection", desc: "Current MRR + expiring windows + new MRR + 30d/90d forward projections", round: "r1035" },
      { href: "/referral-bounty-leaderboard", title: "Referral bounty leaderboard", desc: "Top 50 referrers · paid/queued/cancelled split + paid INR", round: "r1036" },
      { href: "/code-red-by-day-30d", title: "Code Red by day 30d", desc: "Daily Code Red volume + resolved/timed_out/open + resolved %", round: "r1037" },
      { href: "/amc-contracts-by-day-30d", title: "AMC contracts by day 30d", desc: "Daily new AMCs + MRR added + tiers used · revenue growth time series", round: "r1038" },
      { href: "/jobs-by-day-30d", title: "Jobs by day 30d", desc: "Daily posted/completed/cancelled + bids · marketplace activity time series", round: "r1039" },
      { href: "/by-day-index", title: "By-day index ★", desc: "7th meta-landing · 6 daily time-series surfaces (Marketplace/Revenue/Trust/Engagement/Governance)", round: "r1040★" },
      { href: "/metas-index", title: "🌐 Metas index ★★", desc: "Meta-of-metas · all 7 meta-landings in one page · founder navigation root", round: "r1041★★" },
      { href: "/admin-actions-recent", title: "Admin actions recent", desc: "Top 100 most recent founder/admin actions · live governance feed", round: "r1042" },
      { href: "/amc-tier-current-snapshot", title: "AMC tier current snapshot", desc: "Per-tier active/paused/expired + avg INR + MRR + avg pool + avg days→end", round: "r1043" },
      { href: "/bid-acceptance-funnel-30d", title: "Bid acceptance funnel 30d", desc: "Submitted → accepted → completed + rejected + expired tails", round: "r1045" },
      { href: "/spare-part-order-funnel-30d", title: "Spare part order funnel 30d", desc: "Created → paid → shipped → delivered + cancelled/refunded tails", round: "r1046" },
      { href: "/tiers", title: "Engineer tiers", desc: "Tier distribution + threshold", round: "r550+" },
      { href: "/tier-history", title: "Tier history", desc: "Promotion/demotion ledger", round: "r593+" },
      { href: "/tier-distribution-trend", title: "Tier distribution trend", desc: "Current + 30d delta", round: "r632" },
      { href: "/tier-distribution-by-city", title: "Tier distribution by city", desc: "Top 50 cities × engineer cert tier mix", round: "r898" },
      { href: "/tier-climbers", title: "Tier climbers", desc: "Non-gold close to promotion", round: "r676" },
      { href: "/demand-signals", title: "Demand signals", desc: "Market intel + priority", round: "r571+" },
      { href: "/demand-signal-status", title: "Demand signal status", desc: "Open by priority + resolved", round: "r677" },
      { href: "/demand-by-brand", title: "Demand by brand", desc: "Top 50 brands by 90d demand", round: "r712" },
      { href: "/demand-by-model", title: "Demand by model", desc: "Top 50 models by 90d demand", round: "r713" },
      { href: "/training", title: "Supervised training", desc: "Pending + active assignments", round: "r576+" },
      { href: "/supervised-active", title: "Supervised active", desc: "Pending + active list", round: "r684" },
      { href: "/supervised-assignments-recent", title: "Supervised assignments recent", desc: "Last 100 trainee/supervisor pairs (30d)", round: "r937" },
      { href: "/supervised-outcomes", title: "Supervised outcomes", desc: "Lifetime status distribution", round: "r685" },
      { href: "/supervision-funnel", title: "Supervision funnel", desc: "Request → success conversion", round: "r623" },
      { href: "/profile-completeness", title: "Profile completeness", desc: "Per-field coverage", round: "r620" },
      { href: "/signup-completion-rate", title: "Signup completion %", desc: "% new profiles with name+state+city", round: "r939" },
      { href: "/referral-funnel", title: "Referral funnel", desc: "90d cohort signed → paid", round: "r646" },
      { href: "/referral-volume-trend", title: "Referral volume trend", desc: "Daily referrals/first-jobs", round: "r668" },
      { href: "/referrers-leaderboard", title: "Referrers leaderboard", desc: "Top 50 by first-job conversions", round: "r680" },
      { href: "/top-referrers-90d", title: "Top referrers (90d)", desc: "Top 50 by paid bounty volume", round: "r884" },
      { href: "/referrers-by-tier", title: "Referrers by tier", desc: "Referral activity by referrer's cert tier", round: "r891" },
      { href: "/referrals-roi", title: "Referrals ROI ×", desc: "Referee gross / bounty paid", round: "r908" },
      { href: "/referrals-recent", title: "Referrals recent", desc: "Last 100 with eligibility + paid flags", round: "r917" },
      { href: "/retention-cohort", title: "Retention cohort", desc: "Engineer signup-week × active", round: "r647" },
      { href: "/hospital-retention-cohort", title: "Hospital retention cohort", desc: "Hospital signup-week × posted 30d", round: "r836" },
    ],
  },
  {
    label: "Engineers",
    links: [
      { href: "/engineer-utilization", title: "Utilization", desc: "Verified active 7/30/90d", round: "r628" },
      { href: "/engineer-tenure", title: "Tenure", desc: "Verified by signup age", round: "r629" },
      { href: "/engineer-onboarding-funnel", title: "Onboarding funnel", desc: "Signup → first job", round: "r630" },
      { href: "/engineer-loyalty-funnel", title: "Loyalty funnel", desc: "Lifetime cohort: signup → 10+ jobs loyalist", round: "r903" },
      { href: "/engineer-referral-coverage", title: "Referral coverage", desc: "% engineers who referred ≥1", round: "r827" },
      { href: "/bidder-engagement", title: "Bidder engagement", desc: "% verified engineers placing ≥1 bid", round: "r832" },
      { href: "/engineer-dormancy", title: "Dormancy", desc: "Past completers idle >30d", round: "r631" },
      { href: "/engineer-recency", title: "Recency buckets", desc: "Verified engineers by days since last bid", round: "r888" },
      { href: "/verified-engineers-recent", title: "Verified engineers recent", desc: "Last 100 verifications + signup→verified latency", round: "r955" },
      { href: "/engineer-geo", title: "Geo", desc: "Top 50 cities + verification", round: "r633" },
      { href: "/engineer-specialization-coverage", title: "Specialization coverage", desc: "Per-category counts", round: "r634" },
      { href: "/top-engineers-7d", title: "Top earners (7d)", desc: "Top 25 by 7d gross", round: "r615" },
      { href: "/top-engineers-30d", title: "Top earners (30d)", desc: "Top 50 by 30d gross", round: "r635" },
      { href: "/top-engineers-90d", title: "Top earners (90d)", desc: "Top 50 by 90d gross (long loyalists)", round: "r818" },
      { href: "/engineer-acceptance-rate", title: "Acceptance rate", desc: "30d bid → accepted %", round: "r636" },
      { href: "/engineer-payout-history", title: "Payout history", desc: "30/90d/lifetime per engineer", round: "r658" },
      { href: "/engineer-rating-distribution", title: "Rating distribution", desc: "180d histogram", round: "r671" },
      { href: "/lead-scoring", title: "Lead scoring", desc: "≥10 bids, 0 completions", round: "r670" },
    ],
  },
  {
    label: "Hospitals",
    links: [
      { href: "/hospital-utilization", title: "Utilization", desc: "Posting jobs 7/30/90d", round: "r637" },
      { href: "/hospital-repeat-rate", title: "Repeat rate", desc: "Lifetime job count buckets", round: "r638" },
      { href: "/hospital-onboarding-funnel", title: "Onboarding funnel", desc: "Hospital signup → AMC (90d cohort)", round: "r828" },
      { href: "/hospital-loyalty-funnel", title: "Loyalty funnel", desc: "Lifetime: signup → 10+ jobs loyalist", round: "r904" },
      { href: "/hospital-recency", title: "Hospital recency", desc: "Buckets by days since last posted job", round: "r887" },
      { href: "/hospital-geo", title: "Geo", desc: "Top 50 cities", round: "r639" },
      { href: "/hospital-spend-30d", title: "Spend (30d)", desc: "Top 50 spenders + AMC flag", round: "r659" },
      { href: "/hospital-amc-coverage", title: "AMC coverage", desc: "With vs without active AMC", round: "r675" },
      { href: "/hospital-amc-coverage-by-city", title: "AMC coverage by city", desc: "Top 50 cities · AMC penetration %", round: "r899" },
      { href: "/top-hospitals-30d", title: "Top hospitals (30d)", desc: "Top 25 by 30d posts", round: "r616" },
      { href: "/top-hospitals-90d", title: "Top hospitals (90d)", desc: "Top 50 by 90d posts", round: "r819" },
      { href: "/top-amc-spenders",  title: "Top AMC spenders",   desc: "Top 50 by 90d pool credits",  round: "r817" },
    ],
  },
  {
    label: "Repair jobs",
    links: [
      { href: "/repair-job-funnel", title: "Funnel", desc: "30d posted → completed", round: "r641" },
      { href: "/repair-jobs-status", title: "Status snapshot", desc: "All-time status distribution", round: "r692" },
      { href: "/repair-jobs-status-snapshot", title: "Status snapshot (live)", desc: "All-time histogram + share%", round: "r878" },
      { href: "/job-fee-distribution", title: "Fee distribution", desc: "90d gross by bucket", round: "r642" },
      { href: "/job-bid-counts", title: "Bid counts", desc: "Bids-per-job histogram", round: "r643" },
      { href: "/unmatched-jobs", title: "Unmatched >7d", desc: "Posted >7d ago · zero bids", round: "r661" },
      { href: "/jobs-by-hour-of-day", title: "Jobs by hour", desc: "30d hour-of-day distribution", round: "r690" },
      { href: "/jobs-by-day-of-week", title: "Jobs by weekday", desc: "90d weekday distribution", round: "r691" },
      { href: "/jobs-heatmap", title: "Jobs heatmap (hour×weekday)", desc: "7×24 IST grid of posted jobs (90d)", round: "r892" },
    ],
  },
  {
    label: "Spare parts",
    links: [
      { href: "/parts-demand-supply", title: "Demand vs supply", desc: "90d demand vs bonded stock", round: "r644" },
      { href: "/spare-part-orders-recent", title: "Spare part orders recent", desc: "Last 100 orders (30d)", round: "r911" },
      { href: "/spare-parts-by-status", title: "Spare parts by status", desc: "90d count + ₹ per order_status", round: "r912" },
      { href: "/spare-parts-by-month", title: "Spare parts by month", desc: "12mo orders + ₹", round: "r913" },
      { href: "/spare-parts-buyer-mix", title: "Spare parts buyer mix", desc: "Engineer vs hospital share % (90d)", round: "r914" },
      { href: "/spare-parts-by-month-by-status", title: "Spare parts month × status", desc: "12mo total/paid/pending/failed/refunded", round: "r978" },
      { href: "/parts-vendor-share", title: "Vendor share", desc: "Top 50 bonded suppliers", round: "r645" },
      { href: "/bonded-inventory", title: "Bonded inventory", desc: "SKU rollup · in-stock", round: "r619" },
      { href: "/bonded-by-supplier-tier", title: "By supplier tier", desc: "OEM/AUTHORIZED/VERIFIED rollup", round: "r708" },
      { href: "/bonded-dispatch-status", title: "Dispatch status", desc: "All-time dispatch status dist", round: "r709" },
    ],
  },
  {
    label: "Operations latency",
    links: [
      { href: "/kyc-aging", title: "KYC aging", desc: "Pending/rejected age buckets", round: "r612" },
      { href: "/dispute-aging", title: "Dispute aging", desc: "Evidence pack age buckets", round: "r613" },
      { href: "/dispute-resolution-latency", title: "Dispute resolution latency", desc: "Submitted → decision p50/p90", round: "r648" },
      { href: "/dispute-outcomes", title: "Dispute outcomes", desc: "Accepted vs rejected + avg stake", round: "r715" },
      { href: "/bid-latency", title: "Bid acceptance latency", desc: "Posted → accepted (p50/p90)", round: "r617" },
      { href: "/dsr-latency", title: "DSR sign-off latency", desc: "Engineer → hospital signed", round: "r618" },
      { href: "/code-red-sla", title: "Code Red SLA", desc: "Emergency accept rate", round: "r622" },
      { href: "/code-red-by-hour", title: "Code Red by hour", desc: "90d hourly distribution", round: "r716" },
    ],
  },
  {
    label: "Business health",
    links: [
      { href: "/amc-churn", title: "AMC churn", desc: "Rolling 30/90/180d churn %", round: "r614" },
      { href: "/amc-renewal-pipeline", title: "AMC renewal pipeline", desc: "Expiring 30/60/90d · MRR/ARR", round: "r627" },
      { href: "/amc-near-expiry", title: "AMC near expiry", desc: "Expiring within 30d list", round: "r660" },
      { href: "/amc-near-expiry-by-tier", title: "AMC near expiry by tier", desc: "Expiring 30/60/90d + MRR at risk per tier", round: "r882" },
      { href: "/amc-pending-by-hospital", title: "AMC pending by hospital", desc: "Top 50 hospitals with pending payment orders", round: "r883" },
      { href: "/amc-tier-distribution", title: "AMC tier distribution", desc: "Per-tier active + MRR", round: "r640" },
      { href: "/amc-categories-coverage", title: "AMC categories coverage", desc: "Equipment categories rolled up", round: "r689" },
      { href: "/amc-visits-cadence", title: "AMC visits cadence", desc: "Completed vs scheduled %", round: "r649" },
      { href: "/amc-visits-recent", title: "AMC visits recent (30d)", desc: "Last 100 amc-contract-tagged repair jobs", round: "r906" },
      { href: "/amc-vs-adhoc-jobs", title: "AMC vs ad-hoc jobs", desc: "12mo monthly split + AMC share %", round: "r907" },
      { href: "/repair-jobs-by-source", title: "Repair jobs by source", desc: "amc_visit · code_red · direct (90d)", round: "r928" },
      { href: "/amc-debits-by-engineer", title: "AMC debits by engineer", desc: "Top 50 engineers consuming AMC pool 90d", round: "r909" },
      { href: "/amc-pool-health", title: "AMC pool health", desc: "Balance distribution buckets", round: "r678" },
      { href: "/amc-pool-low-balance", title: "AMC pool low balance", desc: "Active AMCs below 2× monthly fee · outreach queue", round: "r724" },
      { href: "/amc-paused", title: "AMC paused", desc: "Paused contracts · MRR frozen", round: "r679" },
      { href: "/amc-paused-recent", title: "AMC paused (sorted)", desc: "100 most-recently-paused + days-paused tone", round: "r951" },
      { href: "/amc-paused-by-tier", title: "AMC paused by tier", desc: "Frozen MRR + avg days paused per tier", round: "r982" },
      { href: "/amc-cancellations", title: "AMC cancellations 30d", desc: "Cancelled/failed/expired list", round: "r683" },
      { href: "/amc-cancellations-recent", title: "AMC cancellations (sorted)", desc: "30d cancellations with MRR lost", round: "r952" },
      { href: "/chains-health", title: "Chains health", desc: "Per-chain AMC % + jobs", round: "r621" },
      { href: "/chains-leaderboard", title: "Chains leaderboard", desc: "Top 50 by member count", round: "r681" },
    ],
  },
  {
    label: "Daily trends (14d)",
    links: [
      { href: "/signups-by-day-trend", title: "Signups", desc: "Daily + engineer breakdown", round: "r652" },
      { href: "/bid-volume-trend", title: "Bids", desc: "Placed + accepted + engineers", round: "r653" },
      { href: "/jobs-volume-trend", title: "Jobs", desc: "Posted + completed + gross", round: "r654" },
      { href: "/demand-signals-trend", title: "Demand signals", desc: "Daily + distinct SKUs + reporters", round: "r655" },
      { href: "/referral-volume-trend", title: "Referrals", desc: "Daily referrals + first-jobs", round: "r668" },
      { href: "/code-red-volume-trend", title: "Code Red", desc: "Daily opened + timed-out", round: "r669" },
      { href: "/payouts-by-day-trend", title: "Payouts", desc: "Daily paid + rupees + failed", round: "r686" },
      { href: "/amc-pool-credits-trend", title: "AMC pool credits", desc: "Daily ledger credit/debit/refund", round: "r693" },
      { href: "/amc-pool-credits-source", title: "AMC pool credits/month", desc: "12mo credit/debit/refund/net", round: "r896" },
      { href: "/amc-pool-debits-recent", title: "AMC pool debits recent", desc: "Last 100 debits (30d) + balance-after tone", round: "r947" },
      { href: "/amc-pool-debits-by-month-by-tier", title: "Pool debits month × tier", desc: "6mo cross-tab · which tier drains pools fastest", round: "r983" },
      { href: "/amc-pool-credits-by-month-by-tier", title: "Pool credits month × tier", desc: "6mo cross-tab · pool top-up cadence per tier", round: "r985" },
      { href: "/amc-pool-credits-recent", title: "AMC pool credits recent", desc: "Last 100 credits (30d)", round: "r948" },
      { href: "/bonded-intake-trend", title: "Bonded intake", desc: "Daily intake rows + qty + cost", round: "r706" },
      { href: "/bonded-dispatch-trend", title: "Bonded dispatch", desc: "Daily dispatches + qty + installed", round: "r707" },
    ],
  },
  {
    label: "Monthly trends (12mo)",
    links: [
      { href: "/repair-jobs-by-month", title: "Repair jobs", desc: "Posted / completed / cancelled / gross", round: "r694" },
      { href: "/jobs-by-month-by-status", title: "Jobs month × status", desc: "12mo posted/completed/cancelled/in-flight", round: "r967" },
      { href: "/signups-by-month", title: "Signups", desc: "Total + engineer subset", round: "r695" },
      { href: "/signups-by-month-by-role", title: "Signups month × role", desc: "12mo engineer vs hospital split", round: "r968" },
      { href: "/amc-contracts-by-month", title: "AMC contracts", desc: "New AMCs + new MRR", round: "r696" },
      { href: "/amc-contracts-by-month-by-tier", title: "New AMCs month × tier", desc: "6mo acquisition by tier", round: "r971" },
      { href: "/payouts-by-month", title: "Engineer payouts", desc: "Paid count / rupees / failed", round: "r697" },
      { href: "/disputes-by-month", title: "Disputes", desc: "Submitted / accepted / rejected", round: "r698" },
      { href: "/disputes-by-month-by-status", title: "Disputes month × status", desc: "12mo submitted/accepted/rejected/pending", round: "r974" },
      { href: "/referrals-by-month", title: "Referrals", desc: "Referrals / first jobs / bounties", round: "r699" },
      { href: "/referrals-by-month-by-status", title: "Referrals month × status", desc: "12mo cohort funnel: signup→first→eligible→paid", round: "r972" },
      { href: "/demand-signals-by-month", title: "Demand signals", desc: "Signals / SKUs / resolved", round: "r701" },
      { href: "/code-red-by-month", title: "Code Red", desc: "Opened / resolved / timed-out", round: "r702" },
      { href: "/code-red-by-month-by-status", title: "Code Red month × status", desc: "12mo monthly funnel", round: "r969" },
      { href: "/escrow-by-month", title: "Escrow", desc: "Released vs refunded", round: "r703" },
      { href: "/tier-changes-by-month", title: "Tier changes", desc: "Promotions / demotions", round: "r704" },
      { href: "/spot-audits-by-month", title: "Spot audits", desc: "Invitations / responses / rating", round: "r705" },
      { href: "/supervised-by-month", title: "Supervised", desc: "Assigned / successful / failed", round: "r710" },
      { href: "/supervised-by-month-by-status", title: "Supervised month × status", desc: "12mo requested/successful/failed/declined", round: "r973" },
      { href: "/amc-payment-by-month", title: "AMC payments", desc: "Paid count / rupees / failed", round: "r711" },
    ],
  },
  {
    label: "Weekly trends (13wk)",
    links: [
      { href: "/jobs-by-week",            title: "Jobs",            desc: "Posted/completed/cancelled/gross", round: "r735" },
      { href: "/signups-by-week",         title: "Signups",         desc: "Total + engineer subset",          round: "r736" },
      { href: "/amc-contracts-by-week",   title: "AMC contracts",   desc: "New AMCs + new MRR",               round: "r737" },
      { href: "/payouts-by-week",         title: "Engineer payouts", desc: "Paid count + rupees + failed",    round: "r738" },
      { href: "/disputes-by-week",        title: "Disputes",        desc: "Submitted/accepted/rejected",      round: "r739" },
      { href: "/referrals-by-week",       title: "Referrals",       desc: "Referrals/first-jobs/bounties",    round: "r740" },
      { href: "/demand-signals-by-week",  title: "Demand signals",  desc: "Signals/SKUs/resolved",            round: "r741" },
      { href: "/code-red-by-week",        title: "Code Red",        desc: "Opened/resolved/timed-out",        round: "r742" },
      { href: "/escrow-by-week",          title: "Escrow",          desc: "Released vs refunded",             round: "r743" },
      { href: "/tier-changes-by-week",    title: "Tier changes",    desc: "Promotions/demotions",             round: "r744" },
      { href: "/supervised-by-week",      title: "Supervised",      desc: "Assigned/successful/failed",       round: "r745" },
      { href: "/spot-audits-by-week",     title: "Spot audits",     desc: "Invitations/responses/rating",     round: "r746" },
      { href: "/amc-payment-by-week",     title: "AMC payments",    desc: "Paid count + rupees + failed",     round: "r747" },
    ],
  },
  {
    label: "Time patterns",
    links: [
      { href: "/signups-by-hour",         title: "Signups by hour", desc: "90d hourly distribution",          round: "r748" },
      { href: "/bids-by-hour",            title: "Bids by hour",    desc: "90d hourly distribution",          round: "r749" },
      { href: "/payouts-by-hour",         title: "Payouts by hour", desc: "90d queued_at distribution",       round: "r750" },
      { href: "/signups-by-day-of-week",  title: "Signups weekday", desc: "90d weekday distribution",         round: "r751" },
      { href: "/bids-by-day-of-week",     title: "Bids weekday",    desc: "90d weekday distribution",         round: "r752" },
      { href: "/code-red-by-day-of-week", title: "Code Red weekday", desc: "90d weekday distribution",        round: "r753" },
      { href: "/payouts-by-day-of-week",  title: "Payouts weekday", desc: "90d weekday distribution",         round: "r754" },
      { href: "/amc-by-day-of-week",      title: "AMC weekday",     desc: "180d signup weekday",              round: "r755" },
    ],
  },
  {
    label: "Cross-cuts & revenue",
    links: [
      { href: "/at-risk-revenue",         title: "At-risk revenue", desc: "6-category leak roll-up",          round: "r756" },
      { href: "/jobs-completion-rate",    title: "Completion rate", desc: "Posted-to-completed weekly funnel", round: "r757" },
      { href: "/amc-churn-monthly",       title: "AMC churn %",     desc: "12-month churn %",                 round: "r758" },
      { href: "/top-suppliers-30d",       title: "Top suppliers",   desc: "Top 25 by 30d intake",             round: "r759" },
      { href: "/bid-amount-distribution", title: "Bid amounts",     desc: "90d bid rupee buckets",            round: "r760" },
      { href: "/bid-vs-contract-spread",  title: "Bid vs contract", desc: "Negotiation stretch p7/30/90d",    round: "r761" },
      { href: "/jobs-by-equipment-type",  title: "Jobs by equipment", desc: "90d category breakdown",         round: "r762" },
      { href: "/commission-vs-payout",    title: "Commission vs payout", desc: "12mo GMV vs paid vs net",     round: "r779" },
      { href: "/pulse-extended",          title: "Pulse extended ★",desc: "10 KPIs WoW (r780 milestone)",     round: "r780" },
    ],
  },
  {
    label: "Cumulative (12mo growth)",
    links: [
      { href: "/verified-engineer-growth", title: "Verified engineers", desc: "Cumulative verified base",     round: "r763" },
      { href: "/amc-base-growth",          title: "AMC base",        desc: "Cumulative AMCs + MRR",           round: "r764" },
      { href: "/signups-cumulative",       title: "Signups",         desc: "Cumulative user base",            round: "r765" },
      { href: "/payouts-cumulative",       title: "Engineer payouts", desc: "Cumulative paid count + rupees", round: "r766" },
      { href: "/gmv-cumulative",           title: "GMV",             desc: "Cumulative GMV + jobs",           round: "r767" },
      { href: "/commission-cumulative",    title: "Commission",      desc: "Cumulative platform take",        round: "r768" },
      { href: "/escrow-cumulative",        title: "Escrow",          desc: "Cumulative released + refunded",  round: "r769" },
      { href: "/amc-revenue-cumulative",   title: "AMC revenue",     desc: "Cumulative AMC payment orders",   round: "r770" },
      { href: "/referrals-cumulative",     title: "Referrals",       desc: "Cumulative referrals + first-jobs", round: "r771" },
      { href: "/demand-signals-cumulative", title: "Demand signals", desc: "Cumulative signals + resolved",   round: "r772" },
      { href: "/disputes-cumulative",      title: "Disputes",        desc: "Cumulative disputes",             round: "r773" },
      { href: "/code-red-cumulative",      title: "Code Red",        desc: "Cumulative Code Red",             round: "r774" },
      { href: "/supervised-cumulative",    title: "Supervised",      desc: "Cumulative supervised",           round: "r775" },
      { href: "/spot-audits-cumulative",   title: "Spot audits",     desc: "Cumulative spot audits",          round: "r776" },
      { href: "/tier-changes-cumulative",  title: "Tier changes",    desc: "Cumulative promo/demo",           round: "r777" },
      { href: "/bonded-intake-cumulative", title: "Bonded intake",   desc: "Cumulative bonded rows/qty/cost", round: "r778" },
    ],
  },
  {
    label: "Health rates",
    links: [
      { href: "/amc-pool-coverage",            title: "AMC pool coverage",       desc: "Active AMCs by buffer buckets",                 round: "r793" },
      { href: "/jobs-fill-rate",               title: "Jobs fill rate",          desc: "% jobs that got bid within 7d",                 round: "r794" },
      { href: "/jobs-time-to-complete",        title: "Jobs time-to-complete",   desc: "Posted → completed p50/p90 hours",              round: "r795" },
      { href: "/escrow-release-rate",          title: "Escrow release rate",     desc: "% completed jobs whose escrow released",        round: "r796" },
      { href: "/amc-payment-collection-rate",  title: "AMC payment collection",  desc: "% AMC payment orders paid · 7/30/90d",          round: "r797" },
      { href: "/payouts-success-rate",         title: "Payouts success rate",    desc: "% engineer payouts processed vs failed",        round: "r798" },
      { href: "/dispute-resolution-rate",      title: "Dispute resolution rate", desc: "% disputes mediator decided",                   round: "r799" },
      { href: "/amc-renewal-rate",             title: "AMC renewal rate",        desc: "% renewal attempts succeeded · 30/90/365d",     round: "r800" },
      { href: "/supervised-success-rate",      title: "Supervised success rate", desc: "% supervised jobs marked successful",           round: "r801" },
      { href: "/jobs-cancellation-rate",       title: "Jobs cancellation rate",  desc: "% repair jobs ending in cancellation",          round: "r802" },
      { href: "/spot-audit-pass-rate",         title: "Spot audit pass rate",    desc: "% spot audit responses rated ≥4★",              round: "r803" },
      { href: "/hospital-retention-rate",      title: "Hospital retention rate", desc: "% active hospitals with ≥2 jobs · 30/90/180d",  round: "r805" },
      { href: "/engineer-retention-rate",      title: "Engineer retention rate", desc: "% engineers with ≥2 completions · 30/90/180d",  round: "r806" },
      { href: "/bids-acceptance-rate-platform", title: "Bid acceptance (platform)", desc: "% all bids accepted · 7/30/90d",              round: "r807" },
      { href: "/code-red-resolution-rate",     title: "Code Red resolution rate", desc: "% emergency requests resolved · 7/30/90d",      round: "r825" },
      { href: "/onboarding-time-to-first-action", title: "Onboarding time-to-first-action", desc: "Median + p90 min from signup → first action", round: "r859" },
      { href: "/first-bid-latency", title: "First bid latency",       desc: "Posted → first-bid time distribution",                round: "r861" },
      { href: "/amc-renewal-by-tenure", title: "Renewal by tenure",   desc: "Renewal success % by contract age",                   round: "r863" },
      { href: "/referral-payout-conversion", title: "Referral signup→paid %", desc: "Referral funnel conversion",                  round: "r864" },
      { href: "/spot-audit-coverage-rate", title: "Spot audit coverage", desc: "Invitation + response rate vs completed jobs",     round: "r865" },
      { href: "/amc-pool-utilization", title: "AMC pool utilization", desc: "debits/credits% per active contract",                 round: "r866" },
      { href: "/tier-progression-rate", title: "Tier progression rate", desc: "Engineer cert promotions vs demotions",             round: "r867" },
      { href: "/tier-graduations-recent", title: "Tier graduations recent", desc: "Last 100 cert tier transitions (30d)",          round: "r876" },
    ],
  },
  {
    label: "Aging surfaces",
    links: [
      { href: "/pending-payouts-aging",     title: "Pending payouts aging",    desc: "engineer_payouts pending bucketed by age",   round: "r809" },
      { href: "/pending-amc-orders-aging",  title: "Pending AMC orders aging", desc: "amc_payment_orders pending bucketed by age", round: "r810" },
      { href: "/repair-jobs-stuck",         title: "Repair jobs stuck >14d",   desc: "Non-terminal repair jobs older than 14d",    round: "r811" },
      { href: "/repair-jobs-recent",        title: "Repair jobs recent (7d)",  desc: "Last 100 created · live raw view",           round: "r949" },
      { href: "/amc-renewal-failures-aging", title: "Renewal failures aging",  desc: "renewal_failed by days since end_date",      round: "r820" },
      { href: "/amc-renewal-failures",       title: "Renewal failures list",   desc: "renewal_failed outreach queue",              round: "r821" },
      { href: "/amc-renewal-attempts-recent", title: "Renewal attempts recent", desc: "Last 100 renewal attempts (30d) + errors", round: "r936" },
      { href: "/amc-renewal-by-month-by-status", title: "Renewals month × status", desc: "12mo succeeded/failed/abandoned monthly", round: "r963" },
      { href: "/amc-renewal-attempts-by-tier", title: "Renewal attempts × tier", desc: "Per-tier 90d outcome counts", round: "r977" },
    ],
  },
  {
    label: "Geo & dimension breakdowns",
    links: [
      { href: "/amc-revenue-by-city",   title: "AMC revenue by city (90d)",   desc: "Top 50 cities by 90d AMC paid rupees",       round: "r812" },
      { href: "/amc-revenue-by-state",  title: "AMC revenue by state (90d)",  desc: "Top 40 states by 90d AMC paid rupees",       round: "r923" },
      { href: "/jobs-revenue-by-city",  title: "Jobs revenue by city (90d)",  desc: "Top 50 cities by 90d completed-jobs gross",   round: "r813" },
      { href: "/jobs-by-state",         title: "Jobs by state",               desc: "Top 40 states · hospitals + jobs + AMC count", round: "r920" },
      { href: "/signups-by-city",       title: "Signups by city (90d)",       desc: "Top 50 cities by 90d new accounts",           round: "r814" },
      { href: "/signups-by-state",      title: "Signups by state (90d)",      desc: "Top 40 states by 90d new accounts",           round: "r922" },
      { href: "/signups-recent",        title: "Signups recent (7d)",         desc: "Last 100 new profiles · raw view",             round: "r953" },
      { href: "/payouts-by-bank",       title: "Payouts by bank (90d)",       desc: "Top 50 banks · processed vs failed",          round: "r815" },
      { href: "/payouts-by-mode",       title: "Payouts by mode (90d)",       desc: "UPI/IMPS/NEFT/RTGS split",                    round: "r860" },
      { href: "/chains-amc-gap",        title: "Chains AMC gap",              desc: "Chain hospitals without AMC · sales queue",   round: "r868" },
      { href: "/demand-by-city",        title: "Demand by city (90d)",        desc: "Top 50 cities by 90d demand signals",         round: "r824" },
      { href: "/demand-priority-distribution", title: "Demand priority", desc: "Demand signals by founder priority · 90d",   round: "r871" },
      { href: "/demand-signals-recent", title: "Demand signals recent", desc: "Last 100 raw signal events (30d)", round: "r915" },
      { href: "/chains-revenue-rollup", title: "Chains revenue rollup (90d)", desc: "Top 50 chains by AMC + jobs revenue",         round: "r826" },
      { href: "/amc-payments-by-tier",  title: "AMC payments by tier (90d)",  desc: "Paid rupees rolled up by AMC tier",           round: "r829" },
      { href: "/amc-revenue-by-month-by-tier", title: "AMC revenue month × tier", desc: "Cross-tab 6mo AMC paid orders",         round: "r962" },
      { href: "/amc-renewal-success-by-tier", title: "Renewal success by tier", desc: "Per-tier renewal success % (90d)",        round: "r854" },
      { href: "/amc-mrr-by-tier",        title: "AMC MRR by tier",         desc: "Active + MRR + ARR + share% per tier",        round: "r877" },
      { href: "/code-red-by-equipment", title: "Code Red by equipment", desc: "Top 50 equipment types · 90d Code Red volume + resolution", round: "r862" },
      { href: "/codered-to-repair-conversion", title: "Code Red → repair conversion", desc: "% Code Red that spawned + completed repair job", round: "r897" },
      { href: "/code-red-recent-list", title: "Code Red recent", desc: "Last 100 emergency events (30d)", round: "r918" },
      { href: "/amc-pool-balance-by-hospital", title: "AMC pool balance by hospital", desc: "Top 50 by active-contract pool balance", round: "r831" },
      { href: "/amc-pool-balance-by-city", title: "AMC pool balance by city",        desc: "Top 50 cities by active-contract balance", round: "r841" },
      { href: "/amc-pool-balance-by-tier", title: "AMC pool balance by tier",        desc: "Total pool + avg buffer (months of MRR) per tier", round: "r919" },
      { href: "/amc-pool-balance-by-state", title: "AMC pool balance by state",       desc: "Top 40 states by active-contract balance", round: "r924" },
      { href: "/state-overview",        title: "State overview ★",            desc: "All-state consolidated dashboard (r925 / PR #1550 milestone)", round: "r925★" },
      { href: "/escrow-by-state",       title: "Escrow by state",             desc: "Held + released + refunded per state",        round: "r926" },
      { href: "/payouts-by-state",      title: "Payouts by state",            desc: "Top 40 states by engineer payout volume 90d", round: "r927" },
      { href: "/spare-parts-by-state",  title: "Spare parts by state",        desc: "Top 40 states by 90d spare-part orders ₹",    round: "r961" },
      { href: "/payouts-by-engineer-tier", title: "Payouts by engineer tier",  desc: "90d processed payouts by cert tier",          round: "r833" },
      { href: "/jobs-by-engineer-tier", title: "Jobs by engineer tier",        desc: "90d completed jobs by cert tier",             round: "r834" },
      { href: "/jobs-completion-by-tier", title: "Jobs completion by tier",    desc: "Per-tier completion % from accepted bids",    round: "r934" },
      { href: "/jobs-completion-by-equipment", title: "Completion hours by equipment", desc: "p50/p90/avg hours per equipment (90d)", round: "r886" },
    ],
  },
  {
    label: "Cron & periodic jobs",
    links: [
      { href: "/cron-status", title: "Cron status", desc: "pg_cron last-run + failures", round: "r599" },
    ],
  },
];

export default async function OpsIndexPage() {
  await requireFounder();

  return (
    <div className="space-y-8">
      <header className="flex items-baseline justify-between">
        <h1 className="text-xl font-semibold">Ops index</h1>
        <span className="text-xs text-[var(--color-muted)]">
          r599–r1046 sprint · 249 ships · all founder ops surfaces in one place
        </span>
      </header>

      <OpsIndexSearchable sections={SECTIONS} />

      <section className="rounded border border-[var(--color-border)] bg-white p-3 text-xs text-[var(--color-muted)]">
        <strong>r855 — search-filter shipped.</strong> 200+ founder ops surfaces
        across ~18 sections, all filterable by title / description / route / round.
        Start at <a href="/platform-pulse" className="underline">/platform-pulse</a>
        (r700 milestone) for the daily executive snapshot;
        <a href="/security-overview" className="underline ml-1">/security-overview</a> (r850)
        for anti-mod stack state.
      </section>
    </div>
  );
}
