import { requireFounder } from "@/lib/auth/requireFounder";
import { OpsIndexSearchable, type OpsSection } from "@/components/OpsIndexSearchable";

export const metadata = { title: "Ops index — EquipSeva Founder Console" };
export const dynamic = "force-dynamic";

const SECTIONS: OpsSection[] = [
  {
    label: "Executive",
    links: [
      { href: "/founder-morning-cockpit", title: "Morning cockpit ★", desc: "Pulse + rates + outreach + integrity · 2-min daily review", round: "r872★" },
      { href: "/live-feed", title: "Live feed ★", desc: "Raw event stream across jobs/payouts/AMC/disputes/code-red (r950 milestone)", round: "r950★" },
      { href: "/cross-tabs-index", title: "Cross-tabs index ★", desc: "11 month × status surfaces in one place (r976 / PR #1600 milestone)", round: "r976★" },
      { href: "/platform-pulse", title: "Platform pulse", desc: "12 KPIs at a glance · executive snapshot", round: "r700★" },
      { href: "/dashboard", title: "Hero dashboard", desc: "Top-line KPIs + today vs yesterday", round: "r597+" },
    ],
  },
  {
    label: "Database health",
    links: [
      { href: "/db-storage", title: "DB storage", desc: "Per-table size · WoW growth", round: "r600+" },
      { href: "/index-health", title: "Index health", desc: "Unused + seq-scan-heavy", round: "r605" },
      { href: "/long-queries", title: "Long-running queries", desc: ">5s queries · idle-in-tx", round: "r604" },
      { href: "/slow-rpcs", title: "Slow RPCs", desc: "pg_stat_statements top 50", round: "r610" },
    ],
  },
  {
    label: "Security & audit",
    links: [
      { href: "/rls-coverage", title: "RLS coverage", desc: "Per-table RLS + grants + risk", round: "r603" },
      { href: "/audit", title: "Founder action log", desc: "Append-only audit ledger", round: "r482+" },
      { href: "/admin-actions-trend", title: "Admin actions trend", desc: "Daily founder_action_log volume", round: "r672" },
      { href: "/admin-top-ops", title: "Admin top ops", desc: "Most-used founder ops · 30d", round: "r673" },
      { href: "/audit-by-actor", title: "Audit by actor", desc: "Top 50 actors by founder_action_log volume", round: "r874" },
      { href: "/audit-trail-export", title: "Audit trail export ★", desc: "CSV download for compliance archive (r900 milestone)", round: "r900★" },
      { href: "/audit-actions-by-day", title: "Audit actions by day", desc: "30d founder action log volume + variety", round: "r929" },
      { href: "/audit-by-week", title: "Audit by week (13wk)", desc: "Manual ops workload trend per week", round: "r980" },
      { href: "/pending-kyc", title: "Pending KYC", desc: "Engineer verification queue", round: "r664" },
      { href: "/kyc-pending-detail", title: "KYC pending detail", desc: "100 oldest pending verifications + days-pending tone", round: "r956" },
      { href: "/open-disputes", title: "Open disputes", desc: "Submitted packs awaiting decision", round: "r665" },
      { href: "/disputes-recent", title: "Disputes recent", desc: "Last 100 packs (90d)", round: "r938" },
      { href: "/dispute-by-mediator", title: "Dispute by mediator", desc: "Top 50 mediators · decisions + accept/reject (90d)", round: "r942" },
      { href: "/spot-audits-summary", title: "Spot audits", desc: "Invitations · responses · ratings", round: "r682" },
      { href: "/spot-audit-rating-distribution", title: "Spot audit ratings", desc: "Per-rating histogram (180d)", round: "r822" },
      { href: "/spot-audit-by-engineer", title: "Spot audit by engineer", desc: "Engineers ranked by lowest avg rating (quality watch)", round: "r894" },
      { href: "/integrity-events", title: "Integrity events", desc: "Play Integrity + client self-report audit", round: "r846" },
      { href: "/security-overview", title: "Security overview ★", desc: "Anti-mod layer status + dirty events", round: "r850" },
      { href: "/grants-audit", title: "Grants audit", desc: "EXECUTE privileges on every founder_* RPC", round: "r852" },
      { href: "/reconciliation-health", title: "Reconciliation health", desc: "3-way recon cron firing audit · 12mo", round: "r857" },
      { href: "/tds-health", title: "TDS 194O health", desc: "TDS row coverage vs processed payouts · 12mo", round: "r858" },
    ],
  },
  {
    label: "Cash flow & integrations",
    links: [
      { href: "/escrow-aging", title: "Escrow aging", desc: "Live escrow by age × status", round: "r607" },
      { href: "/escrow-balance-rollup", title: "Escrow balance rollup", desc: "Per-status totals + oldest", round: "r650" },
      { href: "/escrow-stuck", title: "Escrow stuck >30d", desc: "Pending/held/dispute aged out", round: "r662" },
      { href: "/escrow-velocity", title: "Escrow velocity", desc: "Created → released p50/p90", round: "r674" },
      { href: "/webhooks", title: "Webhook health", desc: "Razorpay + payouts success", round: "r606" },
      { href: "/webhook-failures-recent", title: "Webhook failures recent", desc: "Last 100 unapplied events (7d)", round: "r881" },
      { href: "/webhook-success-rate", title: "Webhook success rate", desc: "% applied per source · 7/30d", round: "r931" },
      { href: "/payouts", title: "Engineer payouts", desc: "Queue · dead-letter · ops", round: "r428+" },
      { href: "/payout-latency", title: "Payout latency", desc: "Queued → processed time", round: "r624" },
      { href: "/payout-volume-30d", title: "Payout volume 30d", desc: "Per-status rupees", round: "r651" },
      { href: "/payouts-by-day-trend", title: "Payouts by day", desc: "Daily paid + failed (14d)", round: "r686" },
      { href: "/payouts-pending-list", title: "Payouts pending list", desc: "Top 100 pending oldest-first", round: "r837" },
      { href: "/payouts-failed-list", title: "Payouts failed list", desc: "Last 100 failed (30d)", round: "r838" },
      { href: "/payouts-recent-list", title: "Payouts recent (7d)", desc: "Last 100 with mode + UTR + status", round: "r946" },
      { href: "/payouts-rupees-by-day", title: "Payouts ₹ by day (30d)", desc: "Daily processed ₹ + failed + pending", round: "r879" },
      { href: "/payouts-by-month-by-status", title: "Payouts month × status", desc: "12mo queued/processing/processed/failed/cancelled", round: "r965" },
      { href: "/escrow-amount-at-risk", title: "Escrow ₹ at risk", desc: "Sum held bucketed by age", round: "r873" },
      { href: "/escrow-flow-by-day", title: "Escrow flow by day (30d)", desc: "Inflow vs released vs refunded daily", round: "r901" },
      { href: "/escrow-by-month-by-status", title: "Escrow month × status", desc: "12mo paid/released/refunded/disputed", round: "r964" },
      { href: "/payouts-net-of-tds", title: "Payouts net of TDS", desc: "Gross vs TDS withheld vs net paid", round: "r889" },
      { href: "/tds-deductions-recent", title: "TDS deductions recent", desc: "Last 100 with deposited flag", round: "r943" },
      { href: "/undeposited-tds", title: "Undeposited TDS ⚠️", desc: "TDS deducted but not yet sent to govt · compliance", round: "r944" },
      { href: "/payout-fail-reasons", title: "Payout fail reasons", desc: "RazorpayX status distribution", round: "r666" },
      { href: "/engineers-missing-payout", title: "Engineers missing payout", desc: "Earned 30d but no verified VPA · outreach queue", round: "r726" },
      { href: "/payout-method-coverage", title: "Payout method coverage", desc: "% of earning engineers with verified VPA · 7/30/90d", round: "r791" },
      { href: "/refunds", title: "Refunds", desc: "Refund authorizations + history", round: "—" },
      { href: "/commission-revenue-30d", title: "Commission revenue (30d)", desc: "Daily platform take (est)", round: "r663" },
      { href: "/commission-by-month", title: "Commission by month", desc: "12mo platform commission est. (7% take)", round: "r893" },
      { href: "/jobs-vs-amc-revenue", title: "Jobs vs AMC revenue", desc: "12mo monthly split + recurring revenue share %", round: "r902" },
      { href: "/weekly-revenue-summary", title: "Weekly revenue summary", desc: "13-week jobs + AMC + parts (3 streams)", round: "r932" },
      { href: "/monthly-revenue-summary", title: "Monthly revenue summary", desc: "12-month jobs + AMC + parts (3 streams)", round: "r933" },
      { href: "/amc-revenue-trend", title: "AMC revenue trend", desc: "Daily AMC paid orders (14d)", round: "r656" },
      { href: "/amc-revenue-by-tier", title: "AMC revenue by tier", desc: "Per-tier MRR + ARR", round: "r688" },
      { href: "/amc-payment-orders-status", title: "AMC payment orders status", desc: "Pending/paid/failed/refunded", round: "r667" },
      { href: "/amc-payment-success-rate", title: "AMC payment success rate", desc: "paid / (paid+failed) 7/30/90d", round: "r714" },
    ],
  },
  {
    label: "Growth & engagement",
    links: [
      { href: "/signups", title: "Signups + active users", desc: "Funnel + DAU/WAU/MAU", round: "r608+" },
      { href: "/weekly-kpis", title: "Weekly KPIs", desc: "WoW snapshot · 7 metrics", round: "r625" },
      { href: "/weekly-kpi-snapshot", title: "Weekly KPI snapshot", desc: "13wk time series · 8 raw KPIs", round: "r986" },
      { href: "/monthly-kpi-snapshot", title: "Monthly KPI snapshot", desc: "12mo time series · 8 raw KPIs", round: "r987" },
      { href: "/daily-kpi-snapshot", title: "Daily KPI snapshot", desc: "90d time series · completes the daily/weekly/monthly trio", round: "r989" },
      { href: "/amc-renewal-window-30d", title: "AMC renewal window 30d", desc: "Renewing next 30d × tier · MRR at risk", round: "r991" },
      { href: "/engineers-no-jobs-30d", title: "Engineer activation leak", desc: "Engineers w/ 0 completed jobs in 30/60/90d + never", round: "r992" },
      { href: "/hospitals-no-jobs-30d", title: "Hospital activation leak", desc: "Hospitals w/ 0 posted jobs in 30/60/90d + never (demand-side mirror)", round: "r993" },
      { href: "/payouts-stuck-aging", title: "Payouts stuck aging", desc: "Queued/processing payouts × age bucket × INR · &gt;7d = engineer trust at risk", round: "r994" },
      { href: "/code-red-aging", title: "Code Red aging", desc: "Open emergency requests × age bucket · &gt;4h = SLA breach", round: "r995" },
      { href: "/spare-parts-stuck-aging", title: "Spare parts stuck aging", desc: "Paid but unshipped orders × age bucket × INR · &gt;7d = buyer trust", round: "r996" },
      { href: "/jobs-unassigned-aging", title: "Jobs unassigned aging", desc: "Open jobs with no engineer × age bucket · marketplace liquidity signal", round: "r997" },
      { href: "/bids-stuck-aging", title: "Bids stuck aging", desc: "Submitted/pending bids no decision × age · engineer trust signal", round: "r998" },
      { href: "/escrow-held-aging", title: "Escrow held aging", desc: "Held escrow rows × age × INR · capital tied up", round: "r999" },
      { href: "/critical-cockpit", title: "Founder critical cockpit ★", desc: "12 cross-system aging/leak signals in one panel (r1000 milestone)", round: "r1000★" },
      { href: "/critical-actions", title: "Critical actions queue", desc: "Top items across payouts/Code Red/spare parts/escrow · with item-level IDs", round: "r1002" },
      { href: "/amc-renewal-funnel-90d", title: "AMC renewal funnel 90d", desc: "Stage 1→2→3 notify cadence → renewed/expired · % of due", round: "r1003" },
      { href: "/payout-success-funnel-90d", title: "Payout success funnel 90d", desc: "Queued → processing → processed/failed/still-queued · % of queued", round: "r1004" },
      { href: "/engineer-onboarding-funnel", title: "Engineer onboarding funnel", desc: "Signup → profile → verified → 1st bid → 1st job → 1st payout · % of signups", round: "r1005" },
      { href: "/equipment-type-breakdown", title: "Equipment type breakdown", desc: "90d jobs by equipment_type · total + completed + open + avg hrs to complete", round: "r1008" },
      { href: "/reviews-pending-aging", title: "Reviews pending aging", desc: "Completed jobs no hospital rating × age · engagement gap signal", round: "r1009" },
      { href: "/funnels-index", title: "Funnels index ★", desc: "Unified landing for all 8+ multi-stage funnel surfaces (r1010 sub-milestone)", round: "r1010★" },
      { href: "/amc-pool-zero-balance", title: "AMC pool zero balance × tier", desc: "Active AMCs at 0 pool balance × tier · blocked MRR · hospitals can't book free services", round: "r1011" },
      { href: "/kyc-pending-aging", title: "KYC pending aging", desc: "Engineers awaiting verification × age bucket · activation pipeline blocker", round: "r1012" },
      { href: "/gst-invoices-by-month-by-source", title: "GST invoices by month × source", desc: "12mo invoice volume × 6 source kinds + taxable/GST/invoice rupees", round: "r1014" },
      { href: "/platform-fee-revenue-by-month", title: "Platform fee revenue by month", desc: "12mo platform-fee taxable INR × 4 sources (repair/AMC visit/spare/AMC sub)", round: "r1015" },
      { href: "/notifications-engagement-30d", title: "Notifications engagement 30d", desc: "Daily sent/read + unread % · engagement health signal", round: "r1016" },
      { href: "/notifications-by-kind-30d", title: "Notifications by kind 30d", desc: "Per-kind sent/read/read-% · candidates to drop or rework", round: "r1017" },
      { href: "/audit-by-actor-30d", title: "Audit by actor 30d", desc: "Top 20 actors by founder_action_log volume + success/failure split", round: "r1018" },
      { href: "/audit-by-op-30d", title: "Audit by op 30d", desc: "Top 50 op_names · failed-heavy ops are candidates for retry/RPC fix", round: "r1019" },
      { href: "/audit-by-table-30d", title: "Audit by table 30d", desc: "Top 50 target_tables · completes audit trio (actor/op/table)", round: "r1020" },
      { href: "/audit-failed-events-30d", title: "Audit failed events 30d", desc: "Top 100 recent failed actions · security + reliability signal", round: "r1021" },
      { href: "/jobs-completion-latency-histogram", title: "Jobs completion latency histogram", desc: "90d completed jobs × 7 latency buckets · marketplace velocity signal", round: "r1022" },
      { href: "/spare-parts-by-supplier-30d", title: "Spare parts by supplier 30d", desc: "Top 50 suppliers × orders + paid + GMV · seller-side leaderboard", round: "r1023" },
      { href: "/engineer-leaderboard-30d", title: "Engineer leaderboard 30d", desc: "Top 50 engineers · jobs done + earnings + avg rating + tier", round: "r1024" },
      { href: "/hospital-leaderboard-30d", title: "Hospital leaderboard 30d", desc: "Top 50 hospitals · jobs posted + completed + spend + AMC count", round: "r1025" },
      { href: "/leaderboards-index", title: "Leaderboards index ★", desc: "4th meta-landing · Supply/Demand/Seller leaderboards in one place", round: "r1026★" },
      { href: "/agings-index", title: "Agings index ★", desc: "5th meta-landing · 9 aging surfaces grouped by severity (Trust/Liquidity/Pipeline/Engagement)", round: "r1027★" },
      { href: "/city-coverage", title: "City coverage", desc: "Top 50 cities · engineers + hospitals + jobs + active AMCs", round: "r1028" },
      { href: "/state-coverage", title: "State coverage", desc: "All states · engineers + verified + hospitals + active AMCs + MRR", round: "r1029" },
      { href: "/coverage-index", title: "Coverage index ★", desc: "6th meta-landing · geographic + chain coverage surfaces", round: "r1030★" },
      { href: "/amc-pool-burn-rate-by-tier", title: "AMC pool burn rate × tier", desc: "Per-tier 30d debit rate + months-to-zero projection", round: "r1031" },
      { href: "/failed-payouts-recent", title: "Failed payouts recent", desc: "Top 100 recent failed payouts × engineer × reason × age · action queue", round: "r1032" },
      { href: "/failed-payouts-by-reason", title: "Failed payouts by reason", desc: "Top 50 failure_reason patterns · systemic vs data-fix diagnosis", round: "r1033" },
      { href: "/audit-ops-by-day-30d", title: "Audit ops by day 30d", desc: "Daily ops count + success/fail + actors + distinct ops · founder activity time series", round: "r1034" },
      { href: "/amc-revenue-projection", title: "AMC revenue projection", desc: "Current MRR + expiring windows + new MRR + 30d/90d forward projections", round: "r1035" },
      { href: "/referral-bounty-leaderboard", title: "Referral bounty leaderboard", desc: "Top 50 referrers · paid/queued/cancelled split + paid INR", round: "r1036" },
      { href: "/code-red-by-day-30d", title: "Code Red by day 30d", desc: "Daily Code Red volume + resolved/timed_out/open + resolved %", round: "r1037" },
      { href: "/amc-contracts-by-day-30d", title: "AMC contracts by day 30d", desc: "Daily new AMCs + MRR added + tiers used · revenue growth time series", round: "r1038" },
      { href: "/jobs-by-day-30d", title: "Jobs by day 30d", desc: "Daily posted/completed/cancelled + bids · marketplace activity time series", round: "r1039" },
      { href: "/by-day-index", title: "By-day index ★", desc: "7th meta-landing · 6 daily time-series surfaces (Marketplace/Revenue/Trust/Engagement/Governance)", round: "r1040★" },
      { href: "/metas-index", title: "🌐 Metas index ★★", desc: "Meta-of-metas · all 7 meta-landings in one page · founder navigation root", round: "r1041★★" },
      { href: "/admin-actions-recent", title: "Admin actions recent", desc: "Top 100 most recent founder/admin actions · live governance feed", round: "r1042" },
      { href: "/amc-tier-current-snapshot", title: "AMC tier current snapshot", desc: "Per-tier active/paused/expired + avg INR + MRR + avg pool + avg days→end", round: "r1043" },
      { href: "/bid-acceptance-funnel-30d", title: "Bid acceptance funnel 30d", desc: "Submitted → accepted → completed + rejected + expired tails", round: "r1045" },
      { href: "/spare-part-order-funnel-30d", title: "Spare part order funnel 30d", desc: "Created → paid → shipped → delivered + cancelled/refunded tails", round: "r1046" },
      { href: "/repair-job-funnel-30d", title: "Repair job funnel 30d", desc: "Posted → bid → assigned → completed + cancelled · core marketplace funnel", round: "r1047" },
      { href: "/payouts-amount-histogram", title: "Payouts amount histogram", desc: "90d processed payouts × 7 amount buckets · pricing tier signal", round: "r1048" },
      { href: "/amc-amount-histogram", title: "AMC amount histogram", desc: "Active AMCs × 7 amount buckets · pricing distribution", round: "r1049" },
      { href: "/histograms-index", title: "Histograms index ★", desc: "8th meta-landing · distribution surfaces (Amount/Latency/Frequency)", round: "r1050★" },
      { href: "/engineer-cohort-retention", title: "Engineer cohort retention", desc: "12mo signup cohorts × 30/60/90/180d active % · classic retention table", round: "r1051" },
      { href: "/hospital-cohort-retention", title: "Hospital cohort retention", desc: "12mo signup cohorts × 30/60/90/180d posted-job % · demand retention", round: "r1052" },
      { href: "/retention-index", title: "Retention index ★", desc: "9th meta-landing · cohort retention + activation leak (Supply/Demand)", round: "r1053★" },
      { href: "/amc-renewal-rate-by-month", title: "AMC renewal rate by month", desc: "6mo actual renewal rate (renewed/due × 100) · key revenue health metric", round: "r1054" },
      { href: "/amc-paused-aging", title: "AMC paused aging", desc: "Paused AMCs × 6 age buckets × frozen MRR · &gt;30d paused = likely churned", round: "r1055" },
      { href: "/engineer-suspension-aging", title: "Engineer suspension aging", desc: "Cash-auto-suspended engineers × 6 age buckets · review queue", round: "r1056" },
      { href: "/audit-by-hour-7d", title: "Audit by hour 7d", desc: "24 IST hours · 7d founder ops distribution · time-of-day pattern", round: "r1057" },
      { href: "/jobs-by-hour-7d", title: "Jobs by hour 7d", desc: "24 IST hours · jobs posted + bids + completed · marketplace temporal pattern", round: "r1058" },
      { href: "/by-hour-index", title: "By-hour index ★", desc: "10th meta-landing · 24 IST hour-of-day surfaces", round: "r1059★" },
      { href: "/amc-pool-credit-events-recent", title: "AMC pool credit events recent", desc: "Top 100 recent credit/refund ledger entries · revenue flow", round: "r1060" },
      { href: "/amc-pool-debit-events-recent", title: "AMC pool debit events recent", desc: "Top 100 recent debit ledger entries · usage feed", round: "r1061" },
      { href: "/events-index", title: "Events index ★", desc: "11th meta-landing · live event feeds (Money/Governance/Marketplace/Trust)", round: "r1062★" },
      { href: "/chains-amc-leaderboard", title: "Chains AMC leaderboard", desc: "Top 50 hospital chains × active AMCs × aggregated MRR", round: "r1063" },
      { href: "/chains-engineer-coverage", title: "Chains engineer coverage", desc: "Per chain · hospitals + cities + engineer supply + verified % · readiness signal", round: "r1064" },
      { href: "/amc-pool-net-flow-by-month", title: "AMC pool net flow by month", desc: "6mo · credits − (debits + refunds) · pool float trend", round: "r1065" },
      { href: "/amc-pool-running-balance", title: "AMC pool running balance", desc: "6mo · net flow + cumulative running total · pool float trajectory", round: "r1066" },
      { href: "/platform-fee-cumulative", title: "Platform fee cumulative", desc: "12mo monthly + cumulative platform-fee revenue", round: "r1067" },
      { href: "/payouts-cumulative", title: "Payouts cumulative", desc: "12mo monthly + cumulative processed engineer payouts", round: "r1068" },
      { href: "/jobs-completed-cumulative", title: "Jobs completed cumulative", desc: "12mo monthly + cumulative completed-job count", round: "r1071" },
      { href: "/cumulative-index", title: "Cumulative index ★", desc: "12th meta-landing · 16 cumulative running-total surfaces by domain", round: "r1072★" },
      { href: "/amc-pool-balance-distribution", title: "AMC pool balance distribution", desc: "Active AMCs × 7 current-balance buckets · 0-balance + grand float", round: "r1073" },
      { href: "/audit-success-rate-by-week", title: "Audit success rate by week", desc: "13wk weekly success/fail % · governance reliability signal", round: "r1074" },
      { href: "/amc-pool-top-balances", title: "AMC pool top balances", desc: "Top 50 active AMCs by current pool balance · upsell + audit candidates", round: "r1075" },
      { href: "/amc-pool-bottom-balances", title: "AMC pool bottom balances", desc: "Bottom 50 active AMCs by pool balance · founder top-up campaign queue", round: "r1076" },
      { href: "/payouts-pending-by-engineer", title: "Payouts pending by engineer", desc: "Top 50 engineers · pending count + INR + oldest + 90d failures", round: "r1077" },
      { href: "/amc-renewal-attempts-by-month", title: "AMC renewal attempts by month", desc: "12mo · attempts split by status + success % · Razorpay outcome quality", round: "r1078" },
      { href: "/disputes-by-day-30d", title: "Disputes by day 30d", desc: "Daily submitted + resolved + open-EOD · dispute lane time series", round: "r1079" },
      { href: "/spare-part-orders-by-day-30d", title: "Spare part orders by day 30d", desc: "Daily orders + paid + shipped + delivered + GMV · marketplace lane", round: "r1080" },
      { href: "/signups-by-role-30d", title: "Signups by role 30d", desc: "Daily engineer + hospital + buyer + other splits · supply-vs-demand growth pulse", round: "r1081" },
      { href: "/supervised-by-day-30d", title: "Supervised by day 30d", desc: "Daily requested + active + successful + failed + declined · training pulse", round: "r1082" },
      { href: "/tier-changes-by-day-30d", title: "Tier changes by day 30d", desc: "Daily promotions vs demotions · supply quality pulse", round: "r1083" },
      { href: "/amc-renewal-window-90d", title: "AMC renewal window 90d", desc: "Renewing in next 90d × tier × MRR at risk · pair with /amc-renewal-window-30d (r991)", round: "r1084" },
      { href: "/code-red-by-hour-7d", title: "Code Red by hour 7d", desc: "24 IST hours · Code Red volume + resolved + timed_out · staffing signal", round: "r1086" },
      { href: "/payouts-by-hour-7d", title: "Payouts by hour 7d", desc: "24 IST hours · queued/processed/failed + paid INR · 7d", round: "r1087" },
      { href: "/amc-renewal-attempts-recent", title: "AMC renewal attempts recent", desc: "Top 100 recent renewal attempts × tier × outcome × error · live feed", round: "r1088" },
      { href: "/disputes-resolution-time-distribution", title: "Dispute resolution time distribution", desc: "90d resolved disputes × 6 latency buckets · mediation velocity histogram", round: "r1090" },
      { href: "/first-bid-latency-distribution", title: "First-bid latency distribution", desc: "90d jobs × 6 buckets of post→first-bid latency · marketplace responsiveness", round: "r1091" },
      { href: "/bids-per-job-distribution", title: "Bids per job distribution", desc: "90d jobs × 6 bid-count buckets · marketplace competitiveness · 0-bid count", round: "r1092" },
      { href: "/signups-by-hour-7d", title: "Signups by hour 7d", desc: "24 IST hours · 7d signups split engineer/hospital/other · onboarding pattern", round: "r1094" },
      { href: "/amc-contracts-by-week-13wk", title: "AMC contracts by week 13wk", desc: "Weekly new AMCs + MRR added + tiers used · medium grain time series", round: "r1098" },
      { href: "/jobs-by-week-13wk", title: "Jobs by week 13wk", desc: "Weekly posted + completed + cancelled + bids · medium grain time series", round: "r1099" },
      { href: "/signups-by-week-13wk", title: "Signups by week 13wk", desc: "Weekly engineer + hospital + other splits · medium grain time series", round: "r1101" },
      { href: "/payouts-by-week-13wk", title: "Payouts by week 13wk", desc: "Weekly queued + processed + failed + paid INR · medium grain time series", round: "r1103" },
      { href: "/by-week-index", title: "By-week index ★", desc: "13th meta-landing · 7 weekly time-series surfaces (13wk grain)", round: "r1104★" },
      { href: "/disputes-by-week-13wk", title: "Disputes by week 13wk", desc: "Weekly submitted + resolved + open-EOW · dispute lane medium grain", round: "r1105" },
      { href: "/code-red-by-week-13wk", title: "Code Red by week 13wk", desc: "Weekly total + resolved + timed_out + resolved % · trust lane medium grain", round: "r1106" },
      { href: "/spare-part-orders-by-week-13wk", title: "Spare part orders by week 13wk", desc: "Weekly orders + paid + delivered + GMV · medium grain", round: "r1107" },
      { href: "/amc-revenue-by-week-13wk", title: "AMC revenue by week 13wk", desc: "Weekly new MRR − expired MRR = net MRR change · revenue health pulse", round: "r1108" },
      { href: "/commission-by-week-13wk", title: "Commission by week 13wk", desc: "Weekly platform-fee invoices count + INR · revenue trend", round: "r1109" },
      { href: "/code-red-resolution-funnel-30d", title: "Code Red resolution funnel 30d", desc: "Created → accepted → resolved + timed_out/cancelled/open tails", round: "r1111" },
      { href: "/amc-pool-net-flow-by-week-13wk", title: "AMC pool net flow by week 13wk", desc: "Weekly credits − (debits + refunds) · pool float trend", round: "r1114" },
      { href: "/amc-pool-running-balance-by-week", title: "AMC pool running balance by week", desc: "13wk cumulative net flow trajectory · weekly grain of r1066", round: "r1115" },
      { href: "/jobs-completion-rate-by-week", title: "Jobs completion rate by week", desc: "13wk · posted + completed + completion % · marketplace health", round: "r1116" },
      { href: "/payouts-success-rate-by-week", title: "Payouts success rate by week", desc: "13wk · processed/queued % · target ≥95% · pair with failed-payouts-by-reason", round: "r1117" },
      { href: "/amc-renewal-rate-by-week", title: "AMC renewal rate by week", desc: "13wk · renewed/due % · weekly companion to r1054 monthly", round: "r1118" },
      { href: "/code-red-resolution-rate-by-week", title: "Code Red resolution rate by week", desc: "13wk · resolved/total % · life-safety SLA weekly trend", round: "r1119" },
      { href: "/rates-index", title: "Rates index ★", desc: "14th meta-landing · 8 conversion/success-rate surfaces by domain", round: "r1120★" },
      { href: "/jobs-cancellation-rate-by-week", title: "Jobs cancellation rate by week", desc: "13wk · cancelled/posted %. >15% = friction signal", round: "r1121" },
      { href: "/spare-parts-delivery-rate-by-week", title: "Spare parts delivery rate by week", desc: "13wk · delivered/paid % · fulfillment health. Target ≥80%", round: "r1122" },
      { href: "/signups-first-action-rate-by-week", title: "Signups first-action rate by week", desc: "13wk · % new signups taking 1st marketplace action in 7d (eng bid/hosp job)", round: "r1124" },
      { href: "/tier-promotion-rate-by-month", title: "Tier promotion rate by month", desc: "12mo · promotions/active-engineers % · engineer quality trend", round: "r1125" },
      { href: "/amc-churn-rate-by-month", title: "AMC churn rate by month", desc: "12mo · (expired + newly paused)/active SOM % · churn signal. Target ≤3%", round: "r1126" },
      { href: "/amc-pool-debits-by-week-13wk", title: "AMC pool debits by week 13wk", desc: "13wk debit events + INR + distinct AMCs · consumption velocity", round: "r1127" },
      { href: "/amc-pool-credits-by-week-13wk", title: "AMC pool credits by week 13wk", desc: "13wk credit events + INR + distinct AMCs · top-up velocity", round: "r1128" },
      { href: "/founder-morning-pulse-v2", title: "Founder morning pulse v2 ★", desc: "12 actionable numbers · today vs yesterday · 4 categories (Growth/Marketplace/Revenue/Trust)", round: "r1130★" },
      { href: "/engineer-earnings-distribution", title: "Engineer earnings distribution", desc: "90d earnings per engineer × 7 amount buckets · pricing-fairness signal", round: "r1131" },
      { href: "/hospital-spend-distribution", title: "Hospital spend distribution", desc: "90d spend per hospital × 7 amount buckets · demand concentration signal", round: "r1132" },
      { href: "/code-red-by-engineer-90d", title: "Code Red by engineer 90d", desc: "Top 50 responders · paged → accepted → resolved funnel per engineer", round: "r1135" },
      { href: "/referral-bounty-payouts-by-week-13wk", title: "Referral bounty payouts by week 13wk", desc: "Weekly bounty paid + cancelled + queued + paid INR · growth-loop spend", round: "r1136" },
      { href: "/amc-by-equipment-category", title: "AMC by equipment category", desc: "AMCs grouped by equipment_categories array element × status + MRR", round: "r1137" },
      { href: "/amc-by-visit-frequency", title: "AMC by visit frequency", desc: "AMCs by weekly/biweekly/monthly/quarterly cadence × status + MRR + avg", round: "r1138" },
      { href: "/amc-by-renewal-term", title: "AMC by renewal term", desc: "AMCs grouped by contract length (months) · long-term commitment mix", round: "r1139" },
      { href: "/amc-index", title: "AMC index ★", desc: "15th meta-landing · 34 AMC surfaces (Structure/Lifecycle/Pool/Revenue/Renewal/Health)", round: "r1140★" },
      { href: "/payouts-index", title: "Payouts index ★", desc: "16th meta-landing · 18 payout surfaces (Aggregate/Timeseries/Diagnostics/Leaderboard/Distribution)", round: "r1141★" },
      { href: "/code-red-index", title: "Code Red index ★", desc: "17th meta-landing · 12 life-safety lane surfaces (Aggregate/Timeseries/SLA/Aging/Leaderboard)", round: "r1142★" },
      { href: "/disputes-index", title: "Disputes index ★", desc: "18th meta-landing · 13 dispute lane surfaces (Aggregate/Timeseries/Latency/Aging/Outcome)", round: "r1143★" },
      { href: "/spare-parts-index", title: "Spare parts index ★", desc: "19th meta-landing · 12 marketplace inventory surfaces", round: "r1144★" },
      { href: "/jobs-index", title: "Jobs index ★", desc: "20th meta-landing · 23 repair-job surfaces (Aggregate/Timeseries/Latency/Aging/Equipment/Funnel/Rate)", round: "r1145★" },
      { href: "/engineers-index", title: "Engineers index ★", desc: "21st meta-landing · 19 engineer surfaces (Aggregate/Tier/Retention/Earnings/Aging/Quality/Geographic)", round: "r1146★" },
      { href: "/hospitals-index", title: "Hospitals index ★", desc: "22nd meta-landing · 13 hospital surfaces (Aggregate/Retention/Spend/Aging/Chain/Geographic)", round: "r1147★" },
      { href: "/notifications-throughput-30d", title: "Notifications throughput 30d", desc: "5 KPIs · sent + read + read % + distinct users + distinct kinds", round: "r1148" },
      { href: "/notifications-index", title: "Notifications index ★", desc: "23rd meta-landing · 3 notification engagement surfaces", round: "r1149★" },
      { href: "/audit-today-summary", title: "Audit today summary", desc: "8 KPI cards · founder/admin actions today (IST) · daily governance pulse", round: "r1150" },
      { href: "/governance-today-vs-yesterday", title: "Governance today vs yesterday", desc: "6 governance metrics · today vs yesterday delta (Failed delta flips color)", round: "r1151" },
      { href: "/engineer-tier-distribution-current", title: "Engineer tier distribution current", desc: "Per tier · engineers + verified + active-30d + %", round: "r1152" },
      { href: "/hospitals-with-no-amc", title: "Hospitals with no AMC", desc: "Conversion gap · 5-card breakdown of hospitals with no/expired/paused AMC", round: "r1153" },
      { href: "/engineers-with-no-payouts", title: "Engineers with no payouts", desc: "Activation gap · 5-card breakdown of engineer payout status", round: "r1154" },
      { href: "/referral-bounty-payouts-by-month", title: "Referral bounty payouts by month", desc: "12mo queued/paid/cancelled + paid INR · growth-loop spend monthly grain", round: "r1155" },
      { href: "/engineers-by-tier-by-city", title: "Engineers by tier by city", desc: "Top 50 cities × engineer tier cross-tab + verified count", round: "r1156" },
      { href: "/amc-by-state", title: "AMC by state", desc: "Per state · AMC status breakdown + active MRR · sorted by MRR desc", round: "r1157" },
      { href: "/amc-by-city", title: "AMC by city (top 50)", desc: "Top 50 cities · AMC status breakdown + active MRR", round: "r1158" },
      { href: "/spare-parts-revenue-by-month", title: "Spare parts revenue by month", desc: "12mo paid orders + GMV + avg/order", round: "r1159" },
      { href: "/supervision-outcome-rate-by-month", title: "Supervision outcome rate by month", desc: "12mo successful/requested % · training program effectiveness", round: "r1160" },
      { href: "/amc-snapshot-summary", title: "AMC snapshot summary", desc: "13-KPI single-row dashboard · pair with /amc-index meta-landing", round: "r1161" },
      { href: "/jobs-snapshot-summary", title: "Jobs snapshot summary", desc: "12-KPI marketplace dashboard · today/30d/all-time mix", round: "r1162" },
      { href: "/code-red-snapshot-summary", title: "Code Red snapshot summary", desc: "13-KPI emergency dashboard · SLA breach % · today/30d/all-time", round: "r1165" },
      { href: "/payouts-snapshot-summary", title: "Payouts snapshot summary", desc: "14-KPI payouts pipeline · queued/processed/failed/stuck · today/30d", round: "r1166" },
      { href: "/spare-parts-snapshot-summary", title: "Spare parts snapshot summary", desc: "15-KPI commerce dashboard · paid/shipped/delivered/stuck · today/30d", round: "r1167" },
      { href: "/engineers-snapshot-summary", title: "Engineers snapshot summary", desc: "14-KPI supply dashboard · KYC + tiers + activity · today/30d/all-time", round: "r1168" },
      { href: "/hospitals-snapshot-summary", title: "Hospitals snapshot summary", desc: "15-KPI demand dashboard · AMC coverage + spend + loyalty · today/30d", round: "r1169" },
      { href: "/disputes-snapshot-summary", title: "Disputes snapshot summary", desc: "14-KPI mediation dashboard · open + resolution % + money at stake · today/30d", round: "r1170" },
      { href: "/escrow-snapshot-summary", title: "Escrow snapshot summary", desc: "18-KPI escrow pipeline · held + released + refunded + scheduled · money-in-flight", round: "r1171" },
      { href: "/snapshots-index", title: "Snapshots index ★", desc: "24th meta-landing · 9 domain snapshot summaries grouped Demand/Supply/Money/Trust", round: "r1172★" },
      { href: "/by-month-index", title: "By-month index ★", desc: "25th meta-landing · 40 monthly time-series grouped Marketplace/AMC/Money/Trust/Growth/Supply", round: "r1179★" },
      { href: "/referrals-snapshot-summary", title: "Referrals snapshot summary", desc: "14-KPI growth dashboard · funnel + bounty spend + ROI + stuck · today/30d", round: "r1180" },
      { href: "/hospital-chains-snapshot-summary", title: "Hospital chains snapshot summary", desc: "13-KPI chain whale dashboard · AMC coverage + revenue concentration", round: "r1181" },
      { href: "/supervised-training-snapshot-summary", title: "Supervised training snapshot summary", desc: "14-KPI training pipeline · active + pass rate + stuck · today/30d", round: "r1182" },
      { href: "/notifications-snapshot-summary", title: "Notifications snapshot summary", desc: "12-KPI throughput · today/30d · stuck-unread alerts", round: "r1183" },
      { href: "/signups-funnel-snapshot-summary", title: "Signups funnel snapshot summary", desc: "13-KPI acquisition funnel · today/7d/30d by role + first-action %", round: "r1184" },
      { href: "/spot-audits-snapshot-summary", title: "Spot audits snapshot summary", desc: "14-KPI QA dashboard · invitations + responses + ratings + coverage", round: "r1185" },
      { href: "/money-in-flight-summary", title: "Money in flight summary ★", desc: "Cross-domain cash position · escrow + payouts + spare-parts + AMC pool + bounty + disputes", round: "r1193★" },
      { href: "/trust-pulse-summary", title: "Trust pulse summary ★", desc: "Composite trust score · disputes + audits + Code Red + refunds + payouts + KYC", round: "r1195★" },
      { href: "/executive-dashboard-index", title: "Executive dashboard index ★", desc: "26th meta-landing · 19 founder dashboards ranked Tier 1/2/3 priority", round: "r1196★" },
      { href: "/equipment-category-snapshot", title: "Equipment category snapshot", desc: "13-KPI taxonomy mix · scope gate · top category by job volume", round: "r1197" },
      { href: "/engineer-certifications-snapshot", title: "Engineer certifications snapshot", desc: "14-KPI cert-ladder · tier mix + promo flow + stalled queue", round: "r1198" },
      { href: "/compliance-evidence-snapshot", title: "Compliance evidence snapshot", desc: "15-KPI regulatory posture · §65B ledger + DPDP + DSR + NABH + audit log", round: "r1199" },
      { href: "/cumulative-rollup-summary", title: "Cumulative rollup summary", desc: "14-KPI lifetime autobiography · investor-deck row · jobs/GMV/payouts/AMC/referrals", round: "r1200" },
      { href: "/regional-state-summary", title: "Regional state summary", desc: "15-KPI top-3 states by composite activity 30d · capital-allocation signal", round: "r1201" },
      { href: "/investor-pulse-summary", title: "Investor pulse summary ★", desc: "15-KPI monthly update · MRR + GMV + active users + lifetime totals · paste into deck", round: "r1208★" },
      { href: "/kyc-pipeline-snapshot", title: "KYC pipeline snapshot", desc: "20-KPI regulatory backlog · engineer + buyer pending + rekyc-due + intake-vs-approval", round: "r1202" },
      { href: "/webhooks-snapshot", title: "Webhooks snapshot", desc: "12-KPI Razorpay webhook health · success rate + retry queue + signature failures", round: "r1203" },
      { href: "/gst-invoice-snapshot", title: "GST invoice snapshot", desc: "12-KPI tax-audit-ready · today/MTD value + dispatch + GSTIN-missing + HSN coverage", round: "r1204" },
      { href: "/rfq-marketplace-snapshot", title: "RFQ marketplace snapshot", desc: "14-KPI vendor RFQs + rental + financing · marketplace TAM expansion lane", round: "r1205" },
      { href: "/amc-sla-warranty-snapshot", title: "AMC SLA warranty snapshot", desc: "14-KPI SLA breach + warranty-detected fee-waived + breach $ exposure", round: "r1206" },
      { href: "/reconciliation-tax-snapshot", title: "Reconciliation tax snapshot", desc: "12-KPI finance-ops · recon mismatch + TDS MTD + 26AS + gateway-vs-ledger drift", round: "r1207" },
      { href: "/amc-pool-pulse-summary", title: "AMC pool pulse summary ★", desc: "12-KPI pool health · balance + flow + zero-balance alerts", round: "r1209★" },
      { href: "/supply-quality-summary", title: "Supply quality summary ★", desc: "Composite engineer-trust score · KYC + tiers + audit + payouts + activity", round: "r1211★" },
      { href: "/demand-quality-summary", title: "Demand quality summary ★", desc: "Composite hospital-trust score · AMC coverage + activity + loyalty + churn", round: "r1212★" },
      { href: "/chat-moderation-summary", title: "Chat moderation summary", desc: "12-KPI DPDP safety · volume + PII-attempts + repeat offenders 30d", round: "r1213" },
      { href: "/onboarding-velocity-summary", title: "Onboarding velocity summary", desc: "12-KPI signup→first-action latency · median + p90 + by role", round: "r1214" },
      { href: "/dsr-data-export-sla-summary", title: "DSR data export SLA summary", desc: "12-KPI DPDP-mandated DSR queue + 24h-SLA compliance + breaches", round: "r1215" },
      { href: "/consent-ledger-summary", title: "Consent ledger summary", desc: "13-KPI DPDP per-purpose grant + revocation velocity", round: "r1216" },
      { href: "/founder-action-followups-summary", title: "Founder action followups summary", desc: "16-KPI untouched items >7d · meta-operational TODO age pulse", round: "r1217" },
      { href: "/system-throughput-hourly-summary", title: "System throughput hourly summary", desc: "12-KPI jobs-per-hour + peak distribution · capacity planning", round: "r1218" },
      { href: "/repair-job-bids-snapshot-summary", title: "Repair job bids snapshot summary", desc: "12-KPI bid dynamics · acceptance % + engineer competition + bids/job", round: "r1229" },
      { href: "/engineer-availability-summary", title: "Engineer availability summary", desc: "12-KPI live supply vs open demand · reachable 1h/24h/7d", round: "r1220" },
      { href: "/razorpay-payments-pulse-summary", title: "Razorpay payments pulse summary", desc: "14-KPI gateway-side pulse · capture lag + webhook recon + refund inflight", round: "r1221" },
      { href: "/email-delivery-health-summary", title: "Email delivery health summary", desc: "12-KPI email channel · sent/delivered/bounced + suppression-list growth", round: "r1222" },
      { href: "/founder-checkpoints-summary", title: "Founder checkpoints summary", desc: "16-KPI release/migration/deployment history · incident-triage signal", round: "r1223" },
      { href: "/regional-city-summary", title: "Regional city summary", desc: "15-KPI top cities by composite activity · city-grain rollup", round: "r1224" },
      { href: "/repair-types-snapshot-summary", title: "Repair types snapshot summary", desc: "13-KPI job-type distribution · margin signal · revenue + latency per type", round: "r1225" },
      { href: "/collusion-flags-summary", title: "Collusion flags summary", desc: "15-KPI fraud signals · engineer↔hospital collusion · open + severity + oldest unreviewed", round: "r1231" },
      { href: "/duplicate-account-flags-summary", title: "Duplicate account flags summary", desc: "14-KPI dupe signups · phone/email/device-id reuse · referral-bounty integrity", round: "r1232" },
      { href: "/promo-redemptions-summary", title: "Promo redemptions summary", desc: "15-KPI CAC visibility · which codes firing + total ₹ given + abuse signals", round: "r1233" },
      { href: "/device-integrity-checks-summary", title: "Device integrity checks summary", desc: "14-KPI Play Integrity attestation · rooted devices + emulators + blocked installs", round: "r1234" },
      { href: "/equipment-pm-schedule-summary", title: "Equipment PM schedule summary", desc: "14-KPI preventive maintenance plan · upcoming PM + overdue · proactive visit driver", round: "r1235" },
      { href: "/cart-abandonment-summary", title: "Cart abandonment summary", desc: "12-KPI active carts ₹ + abandonment rate + top SKUs + conversion-to-order", round: "r1236" },
      { href: "/day-5-shipping-ledger", title: "Day 5 shipping ledger ★", desc: "Milestones + workflows-ridden recap · static page · narrative for stakeholders", round: "r1244★" },
      { href: "/phone-otp-funnel-summary", title: "Phone OTP funnel summary", desc: "12-KPI SMS-OTP layer · request → verify rate + bot bursts + rate-limit hits", round: "r1238" },
      { href: "/bonded-parts-pipeline-summary", title: "Bonded parts pipeline summary", desc: "12-KPI counterfeit-defense chain · in-bond → dispatch → install evidence", round: "r1239" },
      { href: "/virtual-call-sessions-summary", title: "Virtual call sessions summary", desc: "12-KPI Exotel calls · remote-resolve rate + abuse-detection signal", round: "r1240" },
      { href: "/pre-visit-dossier-readiness-summary", title: "Pre-visit dossier readiness summary", desc: "7-KPI engineer prep · dossier-opened-before-visit % · first-time-fix predictor", round: "r1241" },
      { href: "/tds-deductions-pulse-summary", title: "TDS deductions pulse summary", desc: "12-KPI 194C/194J withholding ledger · MTD accrued + missing-PAN + filing aging", round: "r1242" },
      { href: "/dpdp-grievance-pulse-summary", title: "DPDP grievance pulse summary", desc: "12-KPI DPDP Act complaints · 30-day SLA breach + correction/erasure/portability mix", round: "r1243" },
      { href: "/audit-history-index", title: "Audit history index ★", desc: "Pre-deploy adversarial audit log · 6 workflows ridden · 26+ confirmed bugs caught", round: "r1254★" },
      { href: "/workflows-history-index", title: "Workflows history index ★", desc: "Ultracode workflow ledger · 14 ridden (8 design + 6 audit) · ~5.4M agent-tokens spent", round: "r1255★" },
      { href: "/engineer-attendance-summary", title: "Engineer attendance summary", desc: "12-KPI GPS check-ins + suspicious-distance + verified-eng-no-checkin-7d alerts", round: "r1256" },
      { href: "/amc-renewal-attempts-summary", title: "AMC renewal attempts summary", desc: "19-KPI auto-renewal retry pile · success/fail/decline-reason · revenue leak", round: "r1257" },
      { href: "/cash-payment-surveys-summary", title: "Cash payment surveys summary", desc: "14-KPI engineer cash-collection confessions · off-platform leakage detector", round: "r1258" },
      { href: "/buyer-kyc-pipeline-summary", title: "Buyer KYC pipeline summary", desc: "14-KPI hospital-buyer KYC queue · GST/NABH doc mix + verification SLA", round: "r1259" },
      { href: "/catalog-coverage-summary", title: "Catalog coverage summary", desc: "12-KPI devices/brands indexed + untagged equipment + taxonomy depth", round: "r1260" },
      { href: "/refund-authorization-queue-summary", title: "Refund authorization queue summary", desc: "12-KPI manual-approval queue · oldest aging + auto-vs-manual ratio", round: "r1261" },
      { href: "/v04-status-summary", title: "v0.4 status summary ★", desc: "5-phase roadmap roll-up · 451+ ships · 27 meta-landings · investor-deck-ready", round: "r1268★" },
      { href: "/risk-score-snapshots-summary", title: "Risk score snapshots summary", desc: "Forensic risk telemetry · band distribution + action funnel + drift", round: "r1262" },
      { href: "/evidence-ledger-65b-summary", title: "Evidence ledger §65B summary", desc: "Indian Evidence Act content-hash chain · 14 kinds · admissibility pulse", round: "r1263" },
      { href: "/amc-affidavits-summary", title: "AMC affidavits summary", desc: "4 mandatory legal declarations · signer mix + category-coverage + unsigned backlog", round: "r1264" },
      { href: "/amc-engineer-rotation-summary", title: "AMC engineer rotation summary", desc: "AMC↔engineer roster mapping · load distribution + rotation churn", round: "r1265" },
      { href: "/repair-job-cost-revisions-summary", title: "Repair job cost revisions summary", desc: "Scope-creep audit trail · revision freq + avg uplift % + top-revising engineers", round: "r1266" },
      { href: "/db-storage-snapshots-summary", title: "DB storage snapshots summary", desc: "Postgres infra-health · top-N tables by size + fastest-growing wow + capacity planning", round: "r1267" },
      { href: "/amc-admin-escalations-summary", title: "AMC admin escalations summary", desc: "12-KPI ops triage · open backlog + reason mix + oldest unresolved + weekly intake", round: "r1269" },
      { href: "/amc-subscription-charges-summary", title: "AMC subscription charges summary", desc: "22-KPI recurring charge ledger · per-subscription billing pipeline", round: "r1270" },
      { href: "/engineer-kyc-renewals-summary", title: "Engineer KYC renewals summary", desc: "14-KPI periodic re-KYC queue · annual refresh · distinct from initial onboarding", round: "r1271" },
      { href: "/engineer-payout-methods-summary", title: "Engineer payout methods summary", desc: "12-KPI UPI/bank registry · verification state per engineer · payout-method readiness", round: "r1272" },
      { href: "/engineer-tier-history-summary", title: "Engineer tier history summary", desc: "14-KPI tier-progression timeline · transitions + promo/demo velocity", round: "r1273" },
      { href: "/payment-verify-events-summary", title: "Payment verify events summary", desc: "14-KPI server-side Razorpay verify-endpoint ledger · audit trail of capture verifications", round: "r1274" },
      { href: "/sprint-stats-summary", title: "Sprint stats summary ★", desc: "Day 5 velocity stats · 467+ ships · 80+ snapshots · 27 metas · 20 workflows", round: "r1289★" },
      { href: "/investor-update-template", title: "Investor update template ★", desc: "Auto-filled monthly investor email body · MRR + GMV + lifetime totals · copy-paste-ready", round: "r1290★" },
      { href: "/buyer-kyc-verifications-summary", title: "Buyer KYC verifications summary", desc: "16-KPI decision outcomes · approval rate + doc-type mix + p95 time-to-decision", round: "r1291" },
      { href: "/cash-survey-responses-summary", title: "Cash survey responses summary", desc: "16-KPI hospital cash-handling answers · gray-money leakage detector", round: "r1292" },
      { href: "/catalog-coverage-snapshot-summary", title: "Catalog coverage snapshot summary", desc: "17-KPI catalog freshness · brand/device counts + missing-images/specs", round: "r1293" },
      { href: "/seller-verification-requests-summary", title: "Seller verification requests summary", desc: "12-KPI marketplace seller KYC · pending/approved/rejected", round: "r1294" },
      { href: "/spare-part-demand-signals-summary", title: "Spare part demand signals summary", desc: "14-KPI supply-gap radar · buyer requests for not-in-catalog parts", round: "r1295" },
      { href: "/content-reports-moderation-summary", title: "Content reports moderation summary", desc: "14-KPI community safety · user-reports + block-list + repeat offenders", round: "r1296" },
      { href: "/spot-audit-responses-summary", title: "Spot audit responses summary", desc: "Detail-level spot-audit responses · pair with /spot-audits-snapshot-summary", round: "r1287" },
      { href: "/razorpay-webhook-events-summary", title: "Razorpay webhook events summary", desc: "14-KPI incoming-payment telemetry · webhook lag + signature fails + dup events", round: "r1297" },
      { href: "/payouts-webhook-events-summary", title: "Payouts webhook events summary", desc: "14-KPI Cashfree outbound · terminal state distribution + reconciliation gap", round: "r1298" },
      { href: "/amc-sla-breaches-summary", title: "AMC SLA breaches summary", desc: "22-KPI breach ledger by week + tier + engineer + breach type · retention risk", round: "r1299" },
      { href: "/workflow-failure-modes-catalog", title: "Workflow failure modes catalog ★", desc: "18 distinct workflow-agent failure modes observed + fix strategies · knowledge catalog", round: "r1302★" },
      { href: "/founder-action-center", title: "Founder action center ★★★", desc: "UNIFIED PRIORITY QUEUE · top items across 14 source domains · with ACK/RESOLVE/ESCALATE/IGNORE buttons (r1306)", round: "r1303★★★" },
      { href: "/founder-priority-actions-log", title: "Founder priority actions log ★", desc: "Audit trail of every founder ACK/RESOLVE/ESCALATE/IGNORE action · pair with /founder-action-center", round: "r1306★" },
      { href: "/v05-roadmap", title: "v0.5 roadmap ★", desc: "10-phase v0.5 plan · Cashfree payouts + chains + dental + action-center-v2 + investor share v2", round: "r1304★" },
      { href: "/share/investor/v2/<token>", title: "Public investor share v2 ★", desc: "Token-gated public page · 13 sanitized KPIs (MRR + lifetime GMV + trust score) · v0.5 Phase 6 SHIPPED", round: "r1307★" },
      { href: "/founder-cron-status", title: "Founder cron status ★", desc: "pg_cron jobs · last-run state + 24h failure rate · monitors all background automation", round: "r1312★" },
      { href: "/tiers", title: "Engineer tiers", desc: "Tier distribution + threshold", round: "r550+" },
      { href: "/tier-history", title: "Tier history", desc: "Promotion/demotion ledger", round: "r593+" },
      { href: "/tier-distribution-trend", title: "Tier distribution trend", desc: "Current + 30d delta", round: "r632" },
      { href: "/tier-distribution-by-city", title: "Tier distribution by city", desc: "Top 50 cities × engineer cert tier mix", round: "r898" },
      { href: "/tier-climbers", title: "Tier climbers", desc: "Non-gold close to promotion", round: "r676" },
      { href: "/demand-signals", title: "Demand signals", desc: "Market intel + priority", round: "r571+" },
      { href: "/demand-signal-status", title: "Demand signal status", desc: "Open by priority + resolved", round: "r677" },
      { href: "/demand-by-brand", title: "Demand by brand", desc: "Top 50 brands by 90d demand", round: "r712" },
      { href: "/demand-by-model", title: "Demand by model", desc: "Top 50 models by 90d demand", round: "r713" },
      { href: "/training", title: "Supervised training", desc: "Pending + active assignments", round: "r576+" },
      { href: "/supervised-active", title: "Supervised active", desc: "Pending + active list", round: "r684" },
      { href: "/supervised-assignments-recent", title: "Supervised assignments recent", desc: "Last 100 trainee/supervisor pairs (30d)", round: "r937" },
      { href: "/supervised-outcomes", title: "Supervised outcomes", desc: "Lifetime status distribution", round: "r685" },
      { href: "/supervision-funnel", title: "Supervision funnel", desc: "Request → success conversion", round: "r623" },
      { href: "/profile-completeness", title: "Profile completeness", desc: "Per-field coverage", round: "r620" },
      { href: "/signup-completion-rate", title: "Signup completion %", desc: "% new profiles with name+state+city", round: "r939" },
      { href: "/referral-funnel", title: "Referral funnel", desc: "90d cohort signed → paid", round: "r646" },
      { href: "/referral-volume-trend", title: "Referral volume trend", desc: "Daily referrals/first-jobs", round: "r668" },
      { href: "/referrers-leaderboard", title: "Referrers leaderboard", desc: "Top 50 by first-job conversions", round: "r680" },
      { href: "/top-referrers-90d", title: "Top referrers (90d)", desc: "Top 50 by paid bounty volume", round: "r884" },
      { href: "/referrers-by-tier", title: "Referrers by tier", desc: "Referral activity by referrer's cert tier", round: "r891" },
      { href: "/referrals-roi", title: "Referrals ROI ×", desc: "Referee gross / bounty paid", round: "r908" },
      { href: "/referrals-recent", title: "Referrals recent", desc: "Last 100 with eligibility + paid flags", round: "r917" },
      { href: "/retention-cohort", title: "Retention cohort", desc: "Engineer signup-week × active", round: "r647" },
      { href: "/hospital-retention-cohort", title: "Hospital retention cohort", desc: "Hospital signup-week × posted 30d", round: "r836" },
    ],
  },
  {
    label: "Engineers",
    links: [
      { href: "/engineer-utilization", title: "Utilization", desc: "Verified active 7/30/90d", round: "r628" },
      { href: "/engineer-tenure", title: "Tenure", desc: "Verified by signup age", round: "r629" },
      { href: "/engineer-onboarding-funnel", title: "Onboarding funnel", desc: "Signup → first job", round: "r630" },
      { href: "/engineer-loyalty-funnel", title: "Loyalty funnel", desc: "Lifetime cohort: signup → 10+ jobs loyalist", round: "r903" },
      { href: "/engineer-referral-coverage", title: "Referral coverage", desc: "% engineers who referred ≥1", round: "r827" },
      { href: "/bidder-engagement", title: "Bidder engagement", desc: "% verified engineers placing ≥1 bid", round: "r832" },
      { href: "/engineer-dormancy", title: "Dormancy", desc: "Past completers idle >30d", round: "r631" },
      { href: "/engineer-recency", title: "Recency buckets", desc: "Verified engineers by days since last bid", round: "r888" },
      { href: "/verified-engineers-recent", title: "Verified engineers recent", desc: "Last 100 verifications + signup→verified latency", round: "r955" },
      { href: "/engineer-geo", title: "Geo", desc: "Top 50 cities + verification", round: "r633" },
      { href: "/engineer-specialization-coverage", title: "Specialization coverage", desc: "Per-category counts", round: "r634" },
      { href: "/top-engineers-7d", title: "Top earners (7d)", desc: "Top 25 by 7d gross", round: "r615" },
      { href: "/top-engineers-30d", title: "Top earners (30d)", desc: "Top 50 by 30d gross", round: "r635" },
      { href: "/top-engineers-90d", title: "Top earners (90d)", desc: "Top 50 by 90d gross (long loyalists)", round: "r818" },
      { href: "/engineer-acceptance-rate", title: "Acceptance rate", desc: "30d bid → accepted %", round: "r636" },
      { href: "/engineer-payout-history", title: "Payout history", desc: "30/90d/lifetime per engineer", round: "r658" },
      { href: "/engineer-rating-distribution", title: "Rating distribution", desc: "180d histogram", round: "r671" },
      { href: "/lead-scoring", title: "Lead scoring", desc: "≥10 bids, 0 completions", round: "r670" },
    ],
  },
  {
    label: "Hospitals",
    links: [
      { href: "/hospital-utilization", title: "Utilization", desc: "Posting jobs 7/30/90d", round: "r637" },
      { href: "/hospital-repeat-rate", title: "Repeat rate", desc: "Lifetime job count buckets", round: "r638" },
      { href: "/hospital-onboarding-funnel", title: "Onboarding funnel", desc: "Hospital signup → AMC (90d cohort)", round: "r828" },
      { href: "/hospital-loyalty-funnel", title: "Loyalty funnel", desc: "Lifetime: signup → 10+ jobs loyalist", round: "r904" },
      { href: "/hospital-recency", title: "Hospital recency", desc: "Buckets by days since last posted job", round: "r887" },
      { href: "/hospital-geo", title: "Geo", desc: "Top 50 cities", round: "r639" },
      { href: "/hospital-spend-30d", title: "Spend (30d)", desc: "Top 50 spenders + AMC flag", round: "r659" },
      { href: "/hospital-amc-coverage", title: "AMC coverage", desc: "With vs without active AMC", round: "r675" },
      { href: "/hospital-amc-coverage-by-city", title: "AMC coverage by city", desc: "Top 50 cities · AMC penetration %", round: "r899" },
      { href: "/top-hospitals-30d", title: "Top hospitals (30d)", desc: "Top 25 by 30d posts", round: "r616" },
      { href: "/top-hospitals-90d", title: "Top hospitals (90d)", desc: "Top 50 by 90d posts", round: "r819" },
      { href: "/top-amc-spenders",  title: "Top AMC spenders",   desc: "Top 50 by 90d pool credits",  round: "r817" },
    ],
  },
  {
    label: "Repair jobs",
    links: [
      { href: "/repair-job-funnel", title: "Funnel", desc: "30d posted → completed", round: "r641" },
      { href: "/repair-jobs-status", title: "Status snapshot", desc: "All-time status distribution", round: "r692" },
      { href: "/repair-jobs-status-snapshot", title: "Status snapshot (live)", desc: "All-time histogram + share%", round: "r878" },
      { href: "/job-fee-distribution", title: "Fee distribution", desc: "90d gross by bucket", round: "r642" },
      { href: "/job-bid-counts", title: "Bid counts", desc: "Bids-per-job histogram", round: "r643" },
      { href: "/unmatched-jobs", title: "Unmatched >7d", desc: "Posted >7d ago · zero bids", round: "r661" },
      { href: "/jobs-by-hour-of-day", title: "Jobs by hour", desc: "30d hour-of-day distribution", round: "r690" },
      { href: "/jobs-by-day-of-week", title: "Jobs by weekday", desc: "90d weekday distribution", round: "r691" },
      { href: "/jobs-heatmap", title: "Jobs heatmap (hour×weekday)", desc: "7×24 IST grid of posted jobs (90d)", round: "r892" },
    ],
  },
  {
    label: "Spare parts",
    links: [
      { href: "/parts-demand-supply", title: "Demand vs supply", desc: "90d demand vs bonded stock", round: "r644" },
      { href: "/spare-part-orders-recent", title: "Spare part orders recent", desc: "Last 100 orders (30d)", round: "r911" },
      { href: "/spare-parts-by-status", title: "Spare parts by status", desc: "90d count + ₹ per order_status", round: "r912" },
      { href: "/spare-parts-by-month", title: "Spare parts by month", desc: "12mo orders + ₹", round: "r913" },
      { href: "/spare-parts-buyer-mix", title: "Spare parts buyer mix", desc: "Engineer vs hospital share % (90d)", round: "r914" },
      { href: "/spare-parts-by-month-by-status", title: "Spare parts month × status", desc: "12mo total/paid/pending/failed/refunded", round: "r978" },
      { href: "/parts-vendor-share", title: "Vendor share", desc: "Top 50 bonded suppliers", round: "r645" },
      { href: "/bonded-inventory", title: "Bonded inventory", desc: "SKU rollup · in-stock", round: "r619" },
      { href: "/bonded-by-supplier-tier", title: "By supplier tier", desc: "OEM/AUTHORIZED/VERIFIED rollup", round: "r708" },
      { href: "/bonded-dispatch-status", title: "Dispatch status", desc: "All-time dispatch status dist", round: "r709" },
    ],
  },
  {
    label: "Operations latency",
    links: [
      { href: "/kyc-aging", title: "KYC aging", desc: "Pending/rejected age buckets", round: "r612" },
      { href: "/dispute-aging", title: "Dispute aging", desc: "Evidence pack age buckets", round: "r613" },
      { href: "/dispute-resolution-latency", title: "Dispute resolution latency", desc: "Submitted → decision p50/p90", round: "r648" },
      { href: "/dispute-outcomes", title: "Dispute outcomes", desc: "Accepted vs rejected + avg stake", round: "r715" },
      { href: "/bid-latency", title: "Bid acceptance latency", desc: "Posted → accepted (p50/p90)", round: "r617" },
      { href: "/dsr-latency", title: "DSR sign-off latency", desc: "Engineer → hospital signed", round: "r618" },
      { href: "/code-red-sla", title: "Code Red SLA", desc: "Emergency accept rate", round: "r622" },
      { href: "/code-red-by-hour", title: "Code Red by hour", desc: "90d hourly distribution", round: "r716" },
    ],
  },
  {
    label: "Business health",
    links: [
      { href: "/amc-churn", title: "AMC churn", desc: "Rolling 30/90/180d churn %", round: "r614" },
      { href: "/amc-renewal-pipeline", title: "AMC renewal pipeline", desc: "Expiring 30/60/90d · MRR/ARR", round: "r627" },
      { href: "/amc-near-expiry", title: "AMC near expiry", desc: "Expiring within 30d list", round: "r660" },
      { href: "/amc-near-expiry-by-tier", title: "AMC near expiry by tier", desc: "Expiring 30/60/90d + MRR at risk per tier", round: "r882" },
      { href: "/amc-pending-by-hospital", title: "AMC pending by hospital", desc: "Top 50 hospitals with pending payment orders", round: "r883" },
      { href: "/amc-tier-distribution", title: "AMC tier distribution", desc: "Per-tier active + MRR", round: "r640" },
      { href: "/amc-categories-coverage", title: "AMC categories coverage", desc: "Equipment categories rolled up", round: "r689" },
      { href: "/amc-visits-cadence", title: "AMC visits cadence", desc: "Completed vs scheduled %", round: "r649" },
      { href: "/amc-visits-recent", title: "AMC visits recent (30d)", desc: "Last 100 amc-contract-tagged repair jobs", round: "r906" },
      { href: "/amc-vs-adhoc-jobs", title: "AMC vs ad-hoc jobs", desc: "12mo monthly split + AMC share %", round: "r907" },
      { href: "/repair-jobs-by-source", title: "Repair jobs by source", desc: "amc_visit · code_red · direct (90d)", round: "r928" },
      { href: "/amc-debits-by-engineer", title: "AMC debits by engineer", desc: "Top 50 engineers consuming AMC pool 90d", round: "r909" },
      { href: "/amc-pool-health", title: "AMC pool health", desc: "Balance distribution buckets", round: "r678" },
      { href: "/amc-pool-low-balance", title: "AMC pool low balance", desc: "Active AMCs below 2× monthly fee · outreach queue", round: "r724" },
      { href: "/amc-paused", title: "AMC paused", desc: "Paused contracts · MRR frozen", round: "r679" },
      { href: "/amc-paused-recent", title: "AMC paused (sorted)", desc: "100 most-recently-paused + days-paused tone", round: "r951" },
      { href: "/amc-paused-by-tier", title: "AMC paused by tier", desc: "Frozen MRR + avg days paused per tier", round: "r982" },
      { href: "/amc-cancellations", title: "AMC cancellations 30d", desc: "Cancelled/failed/expired list", round: "r683" },
      { href: "/amc-cancellations-recent", title: "AMC cancellations (sorted)", desc: "30d cancellations with MRR lost", round: "r952" },
      { href: "/chains-health", title: "Chains health", desc: "Per-chain AMC % + jobs", round: "r621" },
      { href: "/chains-leaderboard", title: "Chains leaderboard", desc: "Top 50 by member count", round: "r681" },
    ],
  },
  {
    label: "Daily trends (14d)",
    links: [
      { href: "/signups-by-day-trend", title: "Signups", desc: "Daily + engineer breakdown", round: "r652" },
      { href: "/bid-volume-trend", title: "Bids", desc: "Placed + accepted + engineers", round: "r653" },
      { href: "/jobs-volume-trend", title: "Jobs", desc: "Posted + completed + gross", round: "r654" },
      { href: "/demand-signals-trend", title: "Demand signals", desc: "Daily + distinct SKUs + reporters", round: "r655" },
      { href: "/referral-volume-trend", title: "Referrals", desc: "Daily referrals + first-jobs", round: "r668" },
      { href: "/code-red-volume-trend", title: "Code Red", desc: "Daily opened + timed-out", round: "r669" },
      { href: "/amc-pool-credits-trend", title: "AMC pool credits", desc: "Daily ledger credit/debit/refund", round: "r693" },
      { href: "/amc-pool-credits-source", title: "AMC pool credits/month", desc: "12mo credit/debit/refund/net", round: "r896" },
      { href: "/amc-pool-debits-recent", title: "AMC pool debits recent", desc: "Last 100 debits (30d) + balance-after tone", round: "r947" },
      { href: "/amc-pool-debits-by-month-by-tier", title: "Pool debits month × tier", desc: "6mo cross-tab · which tier drains pools fastest", round: "r983" },
      { href: "/amc-pool-credits-by-month-by-tier", title: "Pool credits month × tier", desc: "6mo cross-tab · pool top-up cadence per tier", round: "r985" },
      { href: "/amc-pool-credits-recent", title: "AMC pool credits recent", desc: "Last 100 credits (30d)", round: "r948" },
      { href: "/bonded-intake-trend", title: "Bonded intake", desc: "Daily intake rows + qty + cost", round: "r706" },
      { href: "/bonded-dispatch-trend", title: "Bonded dispatch", desc: "Daily dispatches + qty + installed", round: "r707" },
    ],
  },
  {
    label: "Monthly trends (12mo)",
    links: [
      { href: "/repair-jobs-by-month", title: "Repair jobs", desc: "Posted / completed / cancelled / gross", round: "r694" },
      { href: "/jobs-by-month-by-status", title: "Jobs month × status", desc: "12mo posted/completed/cancelled/in-flight", round: "r967" },
      { href: "/signups-by-month", title: "Signups", desc: "Total + engineer subset", round: "r695" },
      { href: "/signups-by-month-by-role", title: "Signups month × role", desc: "12mo engineer vs hospital split", round: "r968" },
      { href: "/amc-contracts-by-month", title: "AMC contracts", desc: "New AMCs + new MRR", round: "r696" },
      { href: "/amc-contracts-by-month-by-tier", title: "New AMCs month × tier", desc: "6mo acquisition by tier", round: "r971" },
      { href: "/payouts-by-month", title: "Engineer payouts", desc: "Paid count / rupees / failed", round: "r697" },
      { href: "/disputes-by-month", title: "Disputes", desc: "Submitted / accepted / rejected", round: "r698" },
      { href: "/disputes-by-month-by-status", title: "Disputes month × status", desc: "12mo submitted/accepted/rejected/pending", round: "r974" },
      { href: "/referrals-by-month", title: "Referrals", desc: "Referrals / first jobs / bounties", round: "r699" },
      { href: "/referrals-by-month-by-status", title: "Referrals month × status", desc: "12mo cohort funnel: signup→first→eligible→paid", round: "r972" },
      { href: "/demand-signals-by-month", title: "Demand signals", desc: "Signals / SKUs / resolved", round: "r701" },
      { href: "/code-red-by-month", title: "Code Red", desc: "Opened / resolved / timed-out", round: "r702" },
      { href: "/code-red-by-month-by-status", title: "Code Red month × status", desc: "12mo monthly funnel", round: "r969" },
      { href: "/escrow-by-month", title: "Escrow", desc: "Released vs refunded", round: "r703" },
      { href: "/tier-changes-by-month", title: "Tier changes", desc: "Promotions / demotions", round: "r704" },
      { href: "/spot-audits-by-month", title: "Spot audits", desc: "Invitations / responses / rating", round: "r705" },
      { href: "/supervised-by-month", title: "Supervised", desc: "Assigned / successful / failed", round: "r710" },
      { href: "/supervised-by-month-by-status", title: "Supervised month × status", desc: "12mo requested/successful/failed/declined", round: "r973" },
      { href: "/amc-payment-by-month", title: "AMC payments", desc: "Paid count / rupees / failed", round: "r711" },
    ],
  },
  {
    label: "Weekly trends (13wk)",
    links: [
      { href: "/jobs-by-week",            title: "Jobs",            desc: "Posted/completed/cancelled/gross", round: "r735" },
      { href: "/signups-by-week",         title: "Signups",         desc: "Total + engineer subset",          round: "r736" },
      { href: "/amc-contracts-by-week",   title: "AMC contracts",   desc: "New AMCs + new MRR",               round: "r737" },
      { href: "/payouts-by-week",         title: "Engineer payouts", desc: "Paid count + rupees + failed",    round: "r738" },
      { href: "/disputes-by-week",        title: "Disputes",        desc: "Submitted/accepted/rejected",      round: "r739" },
      { href: "/referrals-by-week",       title: "Referrals",       desc: "Referrals/first-jobs/bounties",    round: "r740" },
      { href: "/demand-signals-by-week",  title: "Demand signals",  desc: "Signals/SKUs/resolved",            round: "r741" },
      { href: "/code-red-by-week",        title: "Code Red",        desc: "Opened/resolved/timed-out",        round: "r742" },
      { href: "/escrow-by-week",          title: "Escrow",          desc: "Released vs refunded",             round: "r743" },
      { href: "/tier-changes-by-week",    title: "Tier changes",    desc: "Promotions/demotions",             round: "r744" },
      { href: "/supervised-by-week",      title: "Supervised",      desc: "Assigned/successful/failed",       round: "r745" },
      { href: "/spot-audits-by-week",     title: "Spot audits",     desc: "Invitations/responses/rating",     round: "r746" },
      { href: "/amc-payment-by-week",     title: "AMC payments",    desc: "Paid count + rupees + failed",     round: "r747" },
    ],
  },
  {
    label: "Time patterns",
    links: [
      { href: "/signups-by-hour",         title: "Signups by hour", desc: "90d hourly distribution",          round: "r748" },
      { href: "/bids-by-hour",            title: "Bids by hour",    desc: "90d hourly distribution",          round: "r749" },
      { href: "/payouts-by-hour",         title: "Payouts by hour", desc: "90d queued_at distribution",       round: "r750" },
      { href: "/signups-by-day-of-week",  title: "Signups weekday", desc: "90d weekday distribution",         round: "r751" },
      { href: "/bids-by-day-of-week",     title: "Bids weekday",    desc: "90d weekday distribution",         round: "r752" },
      { href: "/code-red-by-day-of-week", title: "Code Red weekday", desc: "90d weekday distribution",        round: "r753" },
      { href: "/payouts-by-day-of-week",  title: "Payouts weekday", desc: "90d weekday distribution",         round: "r754" },
      { href: "/amc-by-day-of-week",      title: "AMC weekday",     desc: "180d signup weekday",              round: "r755" },
    ],
  },
  {
    label: "Cross-cuts & revenue",
    links: [
      { href: "/at-risk-revenue",         title: "At-risk revenue", desc: "6-category leak roll-up",          round: "r756" },
      { href: "/jobs-completion-rate",    title: "Completion rate", desc: "Posted-to-completed weekly funnel", round: "r757" },
      { href: "/amc-churn-monthly",       title: "AMC churn %",     desc: "12-month churn %",                 round: "r758" },
      { href: "/top-suppliers-30d",       title: "Top suppliers",   desc: "Top 25 by 30d intake",             round: "r759" },
      { href: "/bid-amount-distribution", title: "Bid amounts",     desc: "90d bid rupee buckets",            round: "r760" },
      { href: "/bid-vs-contract-spread",  title: "Bid vs contract", desc: "Negotiation stretch p7/30/90d",    round: "r761" },
      { href: "/jobs-by-equipment-type",  title: "Jobs by equipment", desc: "90d category breakdown",         round: "r762" },
      { href: "/commission-vs-payout",    title: "Commission vs payout", desc: "12mo GMV vs paid vs net",     round: "r779" },
      { href: "/pulse-extended",          title: "Pulse extended ★",desc: "10 KPIs WoW (r780 milestone)",     round: "r780" },
    ],
  },
  {
    label: "Cumulative (12mo growth)",
    links: [
      { href: "/verified-engineer-growth", title: "Verified engineers", desc: "Cumulative verified base",     round: "r763" },
      { href: "/amc-base-growth",          title: "AMC base",        desc: "Cumulative AMCs + MRR",           round: "r764" },
      { href: "/signups-cumulative",       title: "Signups",         desc: "Cumulative user base",            round: "r765" },
      { href: "/payouts-cumulative",       title: "Engineer payouts", desc: "Cumulative paid count + rupees", round: "r766" },
      { href: "/gmv-cumulative",           title: "GMV",             desc: "Cumulative GMV + jobs",           round: "r767" },
      { href: "/commission-cumulative",    title: "Commission",      desc: "Cumulative platform take",        round: "r768" },
      { href: "/escrow-cumulative",        title: "Escrow",          desc: "Cumulative released + refunded",  round: "r769" },
      { href: "/amc-revenue-cumulative",   title: "AMC revenue",     desc: "Cumulative AMC payment orders",   round: "r770" },
      { href: "/referrals-cumulative",     title: "Referrals",       desc: "Cumulative referrals + first-jobs", round: "r771" },
      { href: "/demand-signals-cumulative", title: "Demand signals", desc: "Cumulative signals + resolved",   round: "r772" },
      { href: "/disputes-cumulative",      title: "Disputes",        desc: "Cumulative disputes",             round: "r773" },
      { href: "/code-red-cumulative",      title: "Code Red",        desc: "Cumulative Code Red",             round: "r774" },
      { href: "/supervised-cumulative",    title: "Supervised",      desc: "Cumulative supervised",           round: "r775" },
      { href: "/spot-audits-cumulative",   title: "Spot audits",     desc: "Cumulative spot audits",          round: "r776" },
      { href: "/tier-changes-cumulative",  title: "Tier changes",    desc: "Cumulative promo/demo",           round: "r777" },
      { href: "/bonded-intake-cumulative", title: "Bonded intake",   desc: "Cumulative bonded rows/qty/cost", round: "r778" },
    ],
  },
  {
    label: "Health rates",
    links: [
      { href: "/amc-pool-coverage",            title: "AMC pool coverage",       desc: "Active AMCs by buffer buckets",                 round: "r793" },
      { href: "/jobs-fill-rate",               title: "Jobs fill rate",          desc: "% jobs that got bid within 7d",                 round: "r794" },
      { href: "/jobs-time-to-complete",        title: "Jobs time-to-complete",   desc: "Posted → completed p50/p90 hours",              round: "r795" },
      { href: "/escrow-release-rate",          title: "Escrow release rate",     desc: "% completed jobs whose escrow released",        round: "r796" },
      { href: "/amc-payment-collection-rate",  title: "AMC payment collection",  desc: "% AMC payment orders paid · 7/30/90d",          round: "r797" },
      { href: "/payouts-success-rate",         title: "Payouts success rate",    desc: "% engineer payouts processed vs failed",        round: "r798" },
      { href: "/dispute-resolution-rate",      title: "Dispute resolution rate", desc: "% disputes mediator decided",                   round: "r799" },
      { href: "/amc-renewal-rate",             title: "AMC renewal rate",        desc: "% renewal attempts succeeded · 30/90/365d",     round: "r800" },
      { href: "/supervised-success-rate",      title: "Supervised success rate", desc: "% supervised jobs marked successful",           round: "r801" },
      { href: "/jobs-cancellation-rate",       title: "Jobs cancellation rate",  desc: "% repair jobs ending in cancellation",          round: "r802" },
      { href: "/spot-audit-pass-rate",         title: "Spot audit pass rate",    desc: "% spot audit responses rated ≥4★",              round: "r803" },
      { href: "/hospital-retention-rate",      title: "Hospital retention rate", desc: "% active hospitals with ≥2 jobs · 30/90/180d",  round: "r805" },
      { href: "/engineer-retention-rate",      title: "Engineer retention rate", desc: "% engineers with ≥2 completions · 30/90/180d",  round: "r806" },
      { href: "/bids-acceptance-rate-platform", title: "Bid acceptance (platform)", desc: "% all bids accepted · 7/30/90d",              round: "r807" },
      { href: "/code-red-resolution-rate",     title: "Code Red resolution rate", desc: "% emergency requests resolved · 7/30/90d",      round: "r825" },
      { href: "/onboarding-time-to-first-action", title: "Onboarding time-to-first-action", desc: "Median + p90 min from signup → first action", round: "r859" },
      { href: "/first-bid-latency", title: "First bid latency",       desc: "Posted → first-bid time distribution",                round: "r861" },
      { href: "/amc-renewal-by-tenure", title: "Renewal by tenure",   desc: "Renewal success % by contract age",                   round: "r863" },
      { href: "/referral-payout-conversion", title: "Referral signup→paid %", desc: "Referral funnel conversion",                  round: "r864" },
      { href: "/spot-audit-coverage-rate", title: "Spot audit coverage", desc: "Invitation + response rate vs completed jobs",     round: "r865" },
      { href: "/amc-pool-utilization", title: "AMC pool utilization", desc: "debits/credits% per active contract",                 round: "r866" },
      { href: "/tier-progression-rate", title: "Tier progression rate", desc: "Engineer cert promotions vs demotions",             round: "r867" },
      { href: "/tier-graduations-recent", title: "Tier graduations recent", desc: "Last 100 cert tier transitions (30d)",          round: "r876" },
    ],
  },
  {
    label: "Aging surfaces",
    links: [
      { href: "/pending-payouts-aging",     title: "Pending payouts aging",    desc: "engineer_payouts pending bucketed by age",   round: "r809" },
      { href: "/pending-amc-orders-aging",  title: "Pending AMC orders aging", desc: "amc_payment_orders pending bucketed by age", round: "r810" },
      { href: "/repair-jobs-stuck",         title: "Repair jobs stuck >14d",   desc: "Non-terminal repair jobs older than 14d",    round: "r811" },
      { href: "/repair-jobs-recent",        title: "Repair jobs recent (7d)",  desc: "Last 100 created · live raw view",           round: "r949" },
      { href: "/amc-renewal-failures-aging", title: "Renewal failures aging",  desc: "renewal_failed by days since end_date",      round: "r820" },
      { href: "/amc-renewal-failures",       title: "Renewal failures list",   desc: "renewal_failed outreach queue",              round: "r821" },
      { href: "/amc-renewal-by-month-by-status", title: "Renewals month × status", desc: "12mo succeeded/failed/abandoned monthly", round: "r963" },
      { href: "/amc-renewal-attempts-by-tier", title: "Renewal attempts × tier", desc: "Per-tier 90d outcome counts", round: "r977" },
    ],
  },
  {
    label: "Geo & dimension breakdowns",
    links: [
      { href: "/amc-revenue-by-city",   title: "AMC revenue by city (90d)",   desc: "Top 50 cities by 90d AMC paid rupees",       round: "r812" },
      { href: "/amc-revenue-by-state",  title: "AMC revenue by state (90d)",  desc: "Top 40 states by 90d AMC paid rupees",       round: "r923" },
      { href: "/jobs-revenue-by-city",  title: "Jobs revenue by city (90d)",  desc: "Top 50 cities by 90d completed-jobs gross",   round: "r813" },
      { href: "/jobs-by-state",         title: "Jobs by state",               desc: "Top 40 states · hospitals + jobs + AMC count", round: "r920" },
      { href: "/signups-by-city",       title: "Signups by city (90d)",       desc: "Top 50 cities by 90d new accounts",           round: "r814" },
      { href: "/signups-by-state",      title: "Signups by state (90d)",      desc: "Top 40 states by 90d new accounts",           round: "r922" },
      { href: "/signups-recent",        title: "Signups recent (7d)",         desc: "Last 100 new profiles · raw view",             round: "r953" },
      { href: "/payouts-by-bank",       title: "Payouts by bank (90d)",       desc: "Top 50 banks · processed vs failed",          round: "r815" },
      { href: "/payouts-by-mode",       title: "Payouts by mode (90d)",       desc: "UPI/IMPS/NEFT/RTGS split",                    round: "r860" },
      { href: "/chains-amc-gap",        title: "Chains AMC gap",              desc: "Chain hospitals without AMC · sales queue",   round: "r868" },
      { href: "/demand-by-city",        title: "Demand by city (90d)",        desc: "Top 50 cities by 90d demand signals",         round: "r824" },
      { href: "/demand-priority-distribution", title: "Demand priority", desc: "Demand signals by founder priority · 90d",   round: "r871" },
      { href: "/demand-signals-recent", title: "Demand signals recent", desc: "Last 100 raw signal events (30d)", round: "r915" },
      { href: "/chains-revenue-rollup", title: "Chains revenue rollup (90d)", desc: "Top 50 chains by AMC + jobs revenue",         round: "r826" },
      { href: "/amc-payments-by-tier",  title: "AMC payments by tier (90d)",  desc: "Paid rupees rolled up by AMC tier",           round: "r829" },
      { href: "/amc-revenue-by-month-by-tier", title: "AMC revenue month × tier", desc: "Cross-tab 6mo AMC paid orders",         round: "r962" },
      { href: "/amc-renewal-success-by-tier", title: "Renewal success by tier", desc: "Per-tier renewal success % (90d)",        round: "r854" },
      { href: "/amc-mrr-by-tier",        title: "AMC MRR by tier",         desc: "Active + MRR + ARR + share% per tier",        round: "r877" },
      { href: "/code-red-by-equipment", title: "Code Red by equipment", desc: "Top 50 equipment types · 90d Code Red volume + resolution", round: "r862" },
      { href: "/codered-to-repair-conversion", title: "Code Red → repair conversion", desc: "% Code Red that spawned + completed repair job", round: "r897" },
      { href: "/code-red-recent-list", title: "Code Red recent", desc: "Last 100 emergency events (30d)", round: "r918" },
      { href: "/amc-pool-balance-by-hospital", title: "AMC pool balance by hospital", desc: "Top 50 by active-contract pool balance", round: "r831" },
      { href: "/amc-pool-balance-by-city", title: "AMC pool balance by city",        desc: "Top 50 cities by active-contract balance", round: "r841" },
      { href: "/amc-pool-balance-by-tier", title: "AMC pool balance by tier",        desc: "Total pool + avg buffer (months of MRR) per tier", round: "r919" },
      { href: "/amc-pool-balance-by-state", title: "AMC pool balance by state",       desc: "Top 40 states by active-contract balance", round: "r924" },
      { href: "/state-overview",        title: "State overview ★",            desc: "All-state consolidated dashboard (r925 / PR #1550 milestone)", round: "r925★" },
      { href: "/escrow-by-state",       title: "Escrow by state",             desc: "Held + released + refunded per state",        round: "r926" },
      { href: "/payouts-by-state",      title: "Payouts by state",            desc: "Top 40 states by engineer payout volume 90d", round: "r927" },
      { href: "/spare-parts-by-state",  title: "Spare parts by state",        desc: "Top 40 states by 90d spare-part orders ₹",    round: "r961" },
      { href: "/payouts-by-engineer-tier", title: "Payouts by engineer tier",  desc: "90d processed payouts by cert tier",          round: "r833" },
      { href: "/jobs-by-engineer-tier", title: "Jobs by engineer tier",        desc: "90d completed jobs by cert tier",             round: "r834" },
      { href: "/jobs-completion-by-tier", title: "Jobs completion by tier",    desc: "Per-tier completion % from accepted bids",    round: "r934" },
      { href: "/jobs-completion-by-equipment", title: "Completion hours by equipment", desc: "p50/p90/avg hours per equipment (90d)", round: "r886" },
    ],
  },
  {
    label: "Cron & periodic jobs",
    links: [
      { href: "/cron-status", title: "Cron status", desc: "pg_cron last-run + failures", round: "r599" },
    ],
  },
];

export default async function OpsIndexPage() {
  await requireFounder();

  return (
    <div className="space-y-8">
      <header className="flex items-baseline justify-between">
        <h1 className="text-xl font-semibold">Ops index</h1>
        <span className="text-xs text-[var(--color-muted)]">
          r599–r1302 sprint · 482 ships · all founder ops surfaces in one place
        </span>
      </header>

      <OpsIndexSearchable sections={SECTIONS} />

      <section className="rounded border border-[var(--color-border)] bg-white p-3 text-xs text-[var(--color-muted)]">
        <strong>r855 — search-filter shipped.</strong> 200+ founder ops surfaces
        across ~18 sections, all filterable by title / description / route / round.
        Start at <a href="/platform-pulse" className="underline">/platform-pulse</a>
        (r700 milestone) for the daily executive snapshot;
        <a href="/security-overview" className="underline ml-1">/security-overview</a> (r850)
        for anti-mod stack state.
      </section>
    </div>
  );
}
