-- ORDER BY re-check probe (round3801-3803 follow-up)
-- Self-contained: the pairs below are every (function, first-order-key,
-- direction) the round3801/3803 repairs touched that was zero-arg testable.
-- 73 were undetermined at repair time because their tables held <3 rows or
-- <2 distinct values. Re-run this whole file once real data accumulates:
--   supabase db query --linked -f scripts/verify/orderby_recheck.sql
-- Expected: STILL_UNORDERED count 0. Anything else is a regression.
-- (Origin: session scratchpad obproof3_full.sql, salvaged 2026-09-06 —
--  the migration footers referenced a scratchpad path that dies with the
--  session; this copy survives in-repo.)
CREATE TEMP TABLE _r3801_pairs(fn text, col text, dir text);
INSERT INTO _r3801_pairs VALUES
('market_share_status_funnel_r2673','total_revenue_rupees','DESC'),
('founder_repair_jobs_by_source','jobs_90d','DESC'),
('founder_eng360_reviewer_breakdown','spread','DESC'),
('founder_apprentice_grad_candidates','days_in_program','DESC'),
('rpc_press_spokesperson_perf_r3109','reach','DESC'),
('fn_r3111_tone_outcome','broadcasts_count','DESC'),
('warranty_won_tier_mix_r2239','deals_won','DESC'),
('r2249_low_engagement_recipients','open_rate_pct','ASC'),
('dr_detector_defect_class_severity_r3132','event_count','DESC'),
('dr_detector_defect_class_severity_r3132','total_revenue_loss','DESC'),
('r2736_engineer_scores','avg_score','ASC'),
('r2778_trade_show_engineer_leaderboard','pipeline_rupees','DESC'),
('founder_r2788_engineer_grade_rollup','avg_csat','DESC'),
('founder_r2790_outcome_funnel','row_count','DESC'),
('founder_r2813_surface_stability','avg_stability','ASC'),
('rpc_r2839_chain_rollup','expected_revenue','DESC'),
('rpc_r2850_verdict_distribution','engineer_count','DESC'),
('r2859_signal_mix','uplift_lakhs','DESC'),
('founder_r2862_audience_split','total_engagement','DESC'),
('founder_r2869_member_scorecard','avg_rating','DESC'),
('r2966_city_summary','failed','DESC'),
('founder_r2967_disinfection_method_mix','probe_count','DESC'),
('r3002_replacement_reason_breakdown','replacements','DESC'),
('fn_r3009_findings_by_region','revenue_at_risk','DESC'),
('founder_r3032_brand_mix','lots','DESC'),
('r3034_by_severity','units','DESC'),
('r3043_findings_by_category','total','DESC'),
('r3043_findings_by_category','critical_count','DESC'),
('r3086_spillage_by_severity','total_ml','DESC'),
('founder_r2971_vendor_concentration','total_rupees','DESC'),
('founder_board_category_breakdown','pct_done','ASC'),
('founder_amc_debits_by_engineer','total_debit_rupees','DESC'),
('founder_iwi_introducer_ladder','invested','DESC'),
('fn_diligence_per_acquirer_rollup_r3103','avg_readiness_pct','ASC'),
('founder_r3104_test_method_usage','sample_count','DESC'),
('rpc_press_response_status_r3109','hits','DESC'),
('fn_r3111_followup_completion','completion_pct','ASC'),
('r2350_engineer_leave_totals','approved_days','DESC'),
('dr_detector_calibration_capa_status_r3132','panel_count','DESC'),
('founder_r3135_nda_status_rollup','member_count','DESC'),
('founder_r2696_by_tier','total_allocated_rupees','DESC'),
('r2995_drain_outcome_distribution','n','DESC'),
('founder_roadmap_by_audience_r2753','net_trust_delta_pp','ASC'),
('founder_engineer_rollup_r2766','avg_score','DESC'),
('founder_r2777_projects_by_stage','total_award','DESC'),
('r2778_trade_show_goal_gap','gap','ASC'),
('r2783_decision_breakdown','total_npv_inr','DESC'),
('r2810_tier_breakdown','closure_rate_pct','DESC'),
('founder_bet_by_category_r2841','capital_inr','DESC'),
('r2890_channel_breakdown','event_count','DESC'),
('founder_r2887_reciprocity_score','net_position_rupees','DESC'),
('founder_r2895_chain_rollup','gap_branches','DESC'),
('founder_r2895_chain_rollup','critical_branches','DESC'),
('r2966_finding_severity_mix','finding_count','DESC'),
('founder_fmt_status_breakdown_r2996','n','DESC'),
('r3034_bearing_health_dist','units','DESC'),
('r3086_agent_type_breakdown','visits','DESC'),
('founder_r3737_backlog_digest','total_backlog','DESC'),
('founder_hospital_amc_coverage_by_city','hospitals_total','DESC'),
('founder_engineer_leave_calendar_by_type','cnt','DESC'),
('founder_dispute_by_mediator','decisions_90d','DESC'),
('founder_admin_top_ops','count_30d','DESC'),
('founder_admin_top_ops','count_total','DESC'),
('founder_engineer_payout_history','paid_lifetime','DESC'),
('founder_spare_parts_by_state','rupees_90d','DESC'),
('founder_chains_amc_gap','members_without_amc','DESC'),
('founder_apprentice_overdue','days_overdue','DESC'),
('founder_time_category_summary','hours_30d','DESC'),
('founder_r2292_by_classification','total_gross_paise','DESC'),
('founder_r3104_compliance_rollup','sample_count','DESC'),
('founder_r3104_vendor_mix','action_count','DESC'),
('r3108_ward_heatmap','fails','DESC'),
('r3108_ward_heatmap','withdrawn','DESC'),
('fn_r3111_language_reach','avg_nps','DESC'),
('r2249_channel_mix','blast_count','DESC'),
('dr_detector_audit_fleet_summary_r3132','panel_count','DESC'),
('founder_r2694_region_flow','rotation_count','DESC'),
('r2736_severity_breakdown','actions','DESC'),
('founder_dw_by_category_r2765','total_minutes','DESC'),
('r2810_verdict_distribution','engineer_count','DESC'),
('r2815_long_duration_watchlist','worst_duration_minutes','DESC'),
('founder_r2826_eta_variance','variance_pct','DESC'),
('founder_r2830_engineer_leaderboard','total_ltv_uplift','DESC'),
('rpc_r2831_plays_by_chain','commit_rupees','DESC'),
('rpc_r2882_city_heatmap','visits','DESC'),
('source_system_reconciliation_r2889','claims_using_source','DESC'),
('source_system_reconciliation_r2889','reconciliation_pct','ASC'),
('fn_r2898_doc_type_heatmap','missing_count','DESC'),
('r2905_region_pressure','avg_market_share','DESC'),
('r2905_region_pressure','critical_or_high_count','DESC'),
('r2919_model_breakdown','fail_count','DESC'),
('rpc_r2928_tier_accuracy','accuracy_pct','DESC'),
('r2966_finding_type_mix','finding_count','DESC'),
('founder_r2967_modality_risk_heatmap','open_critical','DESC'),
('founder_r2967_modality_risk_heatmap','open_major','DESC'),
('r2995_defect_by_region','critical','DESC'),
('r2995_defect_by_region','major','DESC'),
('founder_fmt_zone_type_health_r2996','avg_adhesion_pct','ASC'),
('r3000_manufacturer_burn_leaderboard','pass_rate_pct','DESC'),
('r3035_failure_mode_distribution','total_failed','DESC'),
('r3086_ppe_compliance','visits','DESC'),
('founder_r3079_action_summary','event_count','DESC'),
('founder_jobs_by_state','jobs_90d','DESC'),
('tier_distribution_r2492','total_points','DESC'),
('founder_payout_fail_reasons','cnt','DESC'),
('founder_chains_revenue_rollup','total_rupees_90d','DESC'),
('founder_engineer_skills_critical_skill_coverage','coverage_pct','ASC'),
('top_overdue_hospitals_r1747','total_outstanding_rupees','DESC'),
('founder_cash_pipeline_by_stage','weighted_arr_rupees','DESC'),
('founder_r2292_by_policy','total_gross_paise','DESC'),
('founder_r2385_pattern_category_rollup','total_bugs_prevented','DESC'),
('r3106_fio2_accuracy_by_model','worst_fio2_dev','DESC'),
('r3108_vendor_deviation','fail_rate_pct','DESC'),
('balance_kind_distribution_r2633','month_count','DESC'),
('fn_r3111_role_concern_hotspots','total_feedback','DESC'),
('fn_r3111_role_concern_hotspots','concern_pct','DESC'),
('founder_r3123_category_gap_heatmap','gap_clauses','DESC'),
('owner_load_r2672','total_variance_rupees','DESC'),
('founder_r2694_outcome_breakdown','rotation_count','DESC'),
('founder_on_call_region_breakdown_r2702','engineer_count','DESC'),
('r2704_source_performance','total_savings_rupees','DESC'),
('founder_cab_top_contributors_r2717','total_value_rupees','DESC'),
('founder_r2733_source_mix','candidates','DESC'),
('founder_r2747_pilots_by_chain','total_budget_rupees','DESC'),
('founder_r2777_agency_breakdown','total_award','DESC'),
('r2778_trade_show_funnel','expected_rupees','DESC'),
('r2783_qoq_adoption_trend','delta_pct','DESC'),
('founder_r2788_customers_by_tier','breach_total','DESC'),
('founder_r2830_gesture_mix','total_ltv_uplift','DESC'),
('rpc_r2831_plays_by_outcome','commit_rupees','DESC'),
('rpc_r2839_category_mix','expected_revenue','DESC'),
('founder_r2862_channel_performance','total_published','DESC'),
('founder_r2872_velocity_band_distribution','total_quotes_accepted','DESC'),
('founder_r2895_category_posture','coverage_pct','ASC'),
('fn_r2898_channel_mix','events','DESC'),
('r2905_top_win_drivers','win_count','DESC'),
('r2905_top_win_drivers','total_value_rupees','DESC'),
('r2919_city_heatmap','total_exposure','DESC'),
('r2921_mood_distribution','occurrences','DESC'),
('founder_r2967_auditor_productivity','findings_logged','DESC'),
('founder_r2971_chain_summary','total_gap','DESC'),
('r2995_fuel_type_mix','sites','DESC'),
('r3000_fda_audit_risk_summary','avg_risk_score','DESC'),
('r3034_engineer_load','audits','DESC'),
('r3043_city_leaderboard','avg_visual','ASC'),
('r3043_city_leaderboard','fail_count','DESC'),
('fn_r3047_recurring_fault_assets','incident_count','DESC'),
('r3086_tier_distribution','avg_score','DESC'),
('founder_r3079_compliance_split','event_count','DESC'),
('founder_signups_by_state','total_90d','DESC'),
('founder_spare_parts_by_status','rupees_90d','DESC'),
('founder_amc_payment_orders_status','total_rupees','DESC'),
('founder_hospital_spend_30d','spend_30d_rupees','DESC'),
('founder_demand_by_model','signals_90d','DESC'),
('founder_top_engineers_90d','gross_rupees','DESC'),
('founder_amc_revenue_by_city','paid_rupees','DESC'),
('founder_amc_pool_balance_by_city','total_balance','DESC'),
('founder_code_red_by_equipment','cnt_90d','DESC'),
('founder_amc_revenue_by_state','paid_rupees','DESC'),
('fn_acquirer_archetype_mix_r3103','total_weighted_cr','DESC'),
('founder_r3104_sample_point_breakdown','total_samples','DESC'),
('founder_r3104_sample_point_breakdown','failures','DESC'),
('founder_r2385_direction_theme_rollup','total_expected_ships','DESC'),
('correction_status_funnel_r2633','correction_count','DESC'),
('rpc_crisis_playbook_outcomes_r3109','total','DESC'),
('r2255_account_lead_load','total_contract_rupees','DESC'),
('r2278_compliance_alerts','days_remaining','ASC'),
('founder_r3135_conflict_audit','member_count','DESC'),
('root_cause_breakdown_r2672','total_variance_rupees','DESC'),
('audience_kind_distribution_r2621','engagement_count','DESC'),
('market_share_owner_load_r2673','total_revenue_rupees','DESC'),
('founder_chain_finance_action_outcomes_r2675','action_count','DESC'),
('founder_r2684_category_summary','breach_count','DESC'),
('founder_on_call_overload_signal_dist_r2702','engineer_count','DESC'),
('founder_r2747_pilots_by_tech_kind','total_budget_rupees','DESC'),
('founder_r2777_institution_tier_rollup','total_award','DESC'),
('r2785_bet_rollup','total_spend_rupees','DESC'),
('founder_r2788_outcome_distribution','credit_total','DESC'),
('rpc_r2839_run_health','run_count','DESC'),
('founder_bet_capital_efficiency_r2841','score_per_lakh','DESC'),
('weakness_heatmap_r2889','avg_weakness','DESC'),
('weakness_heatmap_r2889','unrehearsed_count','DESC'),
('r2905_loss_reasons','loss_count','DESC'),
('r2905_loss_reasons','total_value_rupees','DESC'),
('r2919_engineer_workload','total_cost','DESC'),
('founder_r2958_hospital_scorecard','pass_pct','ASC'),
('r2995_nabh_witness_coverage','tests','DESC'),
('founder_fmt_engineer_performance_r2996','inspections','DESC'),
('founder_fmt_engineer_performance_r2996','rework_count','DESC'),
('r3002_city_risk_heatmap','fails','DESC'),
('r3002_city_risk_heatmap','condemns','DESC'),
('sync_audit_summary_r3023','sync_rate_pct','ASC'),
('r3034_root_cause_breakdown','replacements','DESC'),
('r3086_regional_discipline','avg_score','DESC'),
('founder_r3079_top_branches_at_risk','retire_count','DESC'),
('founder_r3079_top_branches_at_risk','total_cost','DESC'),
('founder_top_hospitals_90d','jobs_posted','DESC'),
('founder_top_hospitals_90d','gross_rupees','DESC'),
('founder_jobs_revenue_by_city','gross_rupees','DESC'),
('founder_spot_audit_by_engineer','responses_180d','DESC'),
('founder_spot_audit_by_engineer','avg_rating','ASC'),
('founder_spare_parts_buyer_mix','rupees_90d','DESC'),
('founder_amc_pool_balance_by_state','total_balance','DESC'),
('founder_r2292_top_offenders','non_compliant_streams','DESC'),
('founder_r2292_top_offenders','open_findings','DESC'),
('r2302_pass_rate_by_topic','pass_rate_pct','ASC'),
('rpc_press_overview_r3109','total_reach','DESC'),
('fn_r3111_channel_rollup','broadcasts_count','DESC'),
('warranty_stage_breakdown_r2239','deal_count','DESC'),
('r2255_csm_load','total_amcs','DESC'),
('r2278_downtime_by_type','total_revenue_impact_rupees','DESC'),
('dr_detector_ghost_image_audit_r3132','panel_count','DESC'),
('r2704_top_savings_customers','total_savings_rupees','DESC'),
('founder_r2747_outcome_grade_breakdown','outcome_count','DESC'),
('founder_r2750_oem_rollup','completion_pct','ASC'),
('rpc_r2764_saving_by_kind','total_saving_rupees','DESC'),
('founder_dw_decision_breakdown_r2765','topics','DESC'),
('founder_action_mix_r2766','total_actions','DESC'),
('founder_r2788_policy_bands','breach_total','DESC'),
('founder_r2790_redaction_distribution','photos_total','DESC'),
('rpc_r2831_signals_by_kind','cnt','DESC'),
('founder_engineer_vendor_by_tier_r2802','avg_strength','DESC'),
('r2810_region_summary','closure_rate_pct','DESC'),
('founder_r2826_stage_funnel','job_count','DESC'),
('rpc_r2850_tier_breakdown','total_revenue_rupees','DESC'),
('r2859_by_chain','uplift_lakhs','DESC'),
('founder_r2895_amc_upsell_pipeline','total_amc_upsell_rupees','DESC'),
('r2911_chemical_efficacy_audit','pass_rate_pct','ASC'),
('rpc_r2928_customer_pain','breach_pct','DESC'),
('founder_r2971_fixture_mix','short_or_worse','DESC'),
('r2995_cert_upload_backlog','n','DESC'),
('founder_fmt_replacement_outcomes_r2996','n','DESC'),
('r3002_engineer_scorecard','inspections','DESC'),
('rpc_r3040_defect_class_spend','total_cost','DESC'),
('r3043_chain_rollup','fail_count','DESC'),
('r3043_chain_rollup','critical_count','DESC'),
('r3086_remediation_status','count_scorecards','DESC'),
('founder_r3747_incident_digest','food_safety_incidents_total','DESC'),
('founder_signups_by_city','signups_90d','DESC'),
('founder_jobs_completion_by_equipment','jobs_90d','DESC'),
('founder_escrow_by_state','held_rupees','DESC'),
('founder_r3104_lab_partner_mix','samples_processed','DESC'),
('r3106_capa_category_leaderboard','total_cost_rupees','DESC'),
('rpc_press_topic_rollup_r3109','reach','DESC'),
('fn_r3111_audience_rollup','total_reach','DESC'),
('accuracy_by_segment_r2332','accuracy_pct','DESC'),
('dr_detector_replacement_cost_funnel_r3132','total_replacement_lakhs','DESC'),
('leakage_kind_distribution_r2651','total_rupees','DESC'),
('r2736_compliance_breakdown','captures','DESC'),
('founder_r2747_scale_decision_breakdown','decision_count','DESC'),
('founder_r2750_region_rollup','completion_pct','ASC'),
('founder_r2758_region_rollup','total_bonus','DESC'),
('rpc_r2764_status_pipeline','saving_in_status_rupees','DESC'),
('founder_engineer_vendor_by_category_r2802','avg_strength','DESC'),
('founder_r2826_engineer_leaderboard','avg_score','DESC'),
('r2859_by_equipment','avg_abs_r','DESC'),
('founder_r2895_city_heatmap','critical_count','DESC'),
('founder_r2895_city_heatmap','total_failures','DESC'),
('founder_r2912_tier_rollup','avg_latency','ASC'),
('r2919_chain_summary','total_fine_exposure','DESC'),
('founder_r2967_chain_fleet_rollup','overdue_calibration','DESC'),
('founder_r2967_chain_fleet_rollup','failed_recall','DESC'),
('founder_r2987_oem_scorecard','total_recovered_rupees','DESC'),
('founder_fmt_surface_prep_efficacy_r2996','excellent_count','DESC'),
('r3000_material_burn_deep_dive','avg_afterflame','DESC'),
('r3002_model_fleet_wear','condemned','DESC'),
('firmware_spread_r3023','units','DESC'),
('founder_r3079_chain_summary','retire_count','DESC'),
('founder_top_engineers_30d','gross_rupees','DESC'),
('founder_jobs_by_equipment_type','jobs_count','DESC'),
('founder_payouts_by_state','paid_rupees_90d','DESC'),
('founder_investor_open_tracker_recent_events','happened_at','DESC'),
('founder_apprentice_masters_scoreboard','active_apprentices','DESC'),
('founder_engineer_ces_by_engineer_90d','avg_ces','ASC'),
('founder_engineer_ces_by_engineer_90d','high_effort_pct','DESC'),
('founder_cash_pipeline_by_segment','weighted_arr_rupees','DESC'),
('founder_r3104_action_type_cost','total_actual_cost_rupees','DESC'),
('r2302_engineer_leaderboard','pass_rate_pct','ASC'),
('rpc_press_sentiment_trend_r3109','hit_date','DESC'),
('fn_r3111_cadence_effectiveness','avg_nps','DESC'),
('warranty_lost_reasons_r2239','deal_count','DESC'),
('founder_r3123_lab_readiness_scorecard','readiness_pct','ASC'),
('r2259_root_cause_breakdown','losses_count','DESC'),
('dr_detector_capa_event_rollup_r3132','event_count','DESC'),
('status_funnel_r2651','total_rupees','DESC'),
('status_funnel_r2621','total_value_rupees','DESC'),
('owner_load_r2671','total_savings_rupees','DESC'),
('r2995_reserve_summary_by_chain','red_sites','DESC'),
('r2995_reserve_summary_by_chain','amber_sites','DESC'),
('r2736_issue_breakdown','actions','DESC'),
('r2743_on_call_load','incident_count','DESC'),
('r2743_on_call_load','breach_count','DESC'),
('founder_r2758_severity_mix','total','DESC'),
('founder_r2777_strategic_value_rollup','total_projected_revenue','DESC'),
('r2778_trade_show_verdict_breakdown','pipeline_rupees','DESC'),
('r2783_ai_module_leaderboard','total_npv_inr','DESC'),
('r2815_intervention_mix','events','DESC'),
('founder_r2826_verdict_mix','job_count','DESC'),
('rpc_r2839_verdict_breakdown','revenue_sum','DESC'),
('founder_r2862_narratives_by_status','narrative_count','DESC'),
('founder_r2872_tier_rollup','total_accepted','DESC'),
('rpc_r2882_site_type_breakdown','visits','DESC'),
('r2890_tier_distribution','total_bonus','DESC'),
('fn_r2898_tier_breakdown','avg_completeness','DESC'),
('founder_r2912_window_split','avg_latency','DESC'),
('r2966_outcome_breakdown','audit_count','DESC'),
('founder_r2987_category_velocity','avg_velocity_days','ASC'),
('r3002_replacement_pipeline','replacements','DESC'),
('library_version_coverage_r3023','units','DESC'),
('r3043_zone_hygiene','fail_rate_pct','DESC'),
('fn_r3047_manufacturer_failure_heatmap','failure_rate_pct','DESC'),
('founder_r3079_wear_distribution','apron_count','DESC'),
('founder_r3738_uncertified_use_digest','total_uncertified_use_incidents','DESC'),
('founder_r2971_spend_forecast','projected_rupees','DESC');
CREATE TEMP TABLE _r3801_out(fn text, col text, dir text, n int, dvals int, viol int, verdict text);
DO $proof$
DECLARE
  r record; v_n int; v_d int; v_v int;
BEGIN
  PERFORM set_config('request.jwt.claims',
    json_build_object('sub','756a3373-1077-470e-bc0a-79b8d6673ef4','role','authenticated',
                      'email','ganesh1431.dhanavath@gmail.com')::text, true);
  FOR r IN SELECT * FROM _r3801_pairs LOOP
    BEGIN
      EXECUTE format(
        'WITH q AS (SELECT row_number() OVER () AS rn, t.%I AS v FROM public.%I() t)
         SELECT count(*), count(DISTINCT a.v),
                count(*) FILTER (WHERE a.v IS NOT NULL AND b.v IS NOT NULL AND %s)
         FROM q a LEFT JOIN q b ON b.rn = a.rn + 1',
        r.col, r.fn, CASE WHEN r.dir='DESC' THEN 'a.v < b.v' ELSE 'a.v > b.v' END)
      INTO v_n, v_d, v_v;
    EXCEPTION WHEN OTHERS THEN
      INSERT INTO _r3801_out VALUES (r.fn, r.col, r.dir, NULL, NULL, NULL, 'ERROR ' || SQLSTATE);
      CONTINUE;
    END;
    INSERT INTO _r3801_out VALUES (r.fn, r.col, r.dir, v_n, v_d, v_v,
      CASE WHEN v_n < 3 OR v_d < 2 THEN 'undetermined'
           WHEN v_v > 0 THEN 'STILL_UNORDERED'
           ELSE 'ordered' END);
  END LOOP;
END
$proof$;
SELECT coalesce(json_agg(json_build_object(
  'fn', fn, 'col', col, 'dir', dir, 'n', n, 'dvals', dvals, 'viol', viol, 'v', verdict)), '[]'::json)::text AS j
FROM _r3801_out;
