-- Round 323 — TTL purge for spot_audit_invitations.
--
-- spot_audit_invitations holds 7-day-TTL invites generated by the
-- 1-in-20 post-completion audit nudge. The table has an expires_at
-- column but no purge function — rows accumulate forever once any
-- audit ramps in production.
--
-- Sibling fixes in this lineage:
--   * round 304 — purge_old_phone_otp_requests
--   * round 322 — expire_lapsed_amc_contracts
--
-- Caution: spot_audit_responses references spot_audit_invitations
-- with ON DELETE CASCADE. A naive `DELETE FROM ... WHERE expires_at
-- < now()` would drop responses too — destroying the audit signal
-- we collected this invite for. Smart purge: only delete invitations
-- where:
--   (a) the invite expired more than 30 days ago (extra grace), AND
--   (b) no response was ever recorded.
-- Accepted/answered audits are kept indefinitely as part of the
-- engineer's track record.

CREATE OR REPLACE FUNCTION public.purge_old_spot_audit_invitations()
RETURNS int
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_deleted int := 0;
BEGIN
  WITH purged AS (
    DELETE FROM public.spot_audit_invitations i
     WHERE i.expires_at < now() - interval '30 days'
       AND NOT EXISTS (
         SELECT 1 FROM public.spot_audit_responses r
          WHERE r.invitation_id = i.id
       )
    RETURNING 1
  )
  SELECT count(*) INTO v_deleted FROM purged;
  RETURN v_deleted;
END;
$$;

ALTER FUNCTION public.purge_old_spot_audit_invitations() OWNER TO postgres;
REVOKE ALL ON FUNCTION public.purge_old_spot_audit_invitations() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.purge_old_spot_audit_invitations() TO service_role;

COMMENT ON FUNCTION public.purge_old_spot_audit_invitations() IS
  'Round 323 — drop spot_audit_invitations that expired >30 days ago '
  'AND have no recorded response. Responded-to invites are preserved '
  'so the engineer audit trail stays intact. Daily cron via cron-tick.';
