-- =====================================================================
-- Round 3793 -- finish the round3792 class-A repair: the NOT NULL columns
-- =====================================================================
--
-- Round 3792 class A remapped 14 functions' founder_action_log INSERTs
-- onto that table's real column names (action/action_type/action_kind ->
-- op_name, payload -> after_value, target_kind -> target_table,
-- target_id -> target_row_id, note -> reason). That fix was necessary but
-- NOT SUFFICIENT, and the gap is worth recording because it is a limit of
-- the tool that found the whole class.
--
-- plpgsql_check is a STATIC check against the catalog. It reports a column
-- that does not exist. It does NOT and cannot report a NOT NULL column
-- that an INSERT simply omits -- that is a runtime constraint violation,
-- not a resolution failure. founder_action_log declares four NOT NULL
-- columns with no default: actor_user_id, actor_email, op_name and (with
-- defaults) id/outcome/created_at.
--
-- So after round3792 all 14 functions were still broken -- they had merely
-- changed failure mode from 42703 (column does not exist) to 23502 (null
-- value in column "actor_user_id" violates not-null constraint). This was
-- caught by EXECUTING one of them against production inside a probe that
-- rolled back, not by the static sweep, which reported them clean.
--
-- The lesson, for the remaining waves: a green plpgsql_check is necessary
-- but not sufficient. Anything that writes has to actually be run.
--
-- All 14 omit actor_user_id. Two of them (rpc_r1646_mark_status,
-- rpc_r1646_record_followup) also omit actor_email; both already declare
-- `v_email text := (auth.jwt()->>'email')` and both are is_founder()
-- gated, so v_email is used for those, matching their own existing code.
--
-- The value supplied for actor_user_id is auth.uid(), which is what the
-- 2322 CORRECT founder_action_log INSERT sites elsewhere in this schema
-- all use -- the canonical form being
--   INSERT INTO public.founder_action_log
--     (actor_user_id, actor_email, op_name, after_value)
--   VALUES (auth.uid(), (auth.jwt()->>'email'), '<op>', jsonb_build_object(...))
-- These 14 were the ONLY sites in the schema missing it, so this closes
-- the class rather than sampling it.
--
-- Generated by rewriting each live definition: the INSERT's column list
-- and its VALUES tuple are parsed with real paren matching, the new
-- entries are prepended to both, and the result is re-parsed to assert
-- the arity still matches and that all three NOT NULL columns are now
-- present. The header (signature + RETURNS + volatility + search_path)
-- is asserted byte-identical, so no overload can be created.
--
-- VERIFICATION runs inside the transaction and, unlike round3792, it does
-- not stop at static analysis: it EXECUTES one of the repaired functions
-- for real, confirms a founder_action_log row was written with a non-null
-- actor_user_id, and then undoes it via a subtransaction sentinel so the
-- probe leaves nothing behind.

BEGIN;

-- public.add_chain_membership(p_chain_contract_id uuid, p_hospital_org_id uuid, p_membership_kind text, p_override_json jsonb, p_notes text)
--   founder_action_log columns now: actor_user_id, actor_email, op_name, target_table, target_row_id, after_value
CREATE OR REPLACE FUNCTION public.add_chain_membership(p_chain_contract_id uuid, p_hospital_org_id uuid, p_membership_kind text, p_override_json jsonb, p_notes text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_id uuid;
  v_email text;
BEGIN
  IF NOT public.is_founder() THEN
    RAISE EXCEPTION 'forbidden';
  END IF;

  v_email := (auth.jwt()->>'email');

  INSERT INTO public.hospital_chain_membership (
    chain_contract_id, hospital_org_id, membership_kind, binding_rate_card_override, notes
  ) VALUES (
    p_chain_contract_id, p_hospital_org_id,
    COALESCE(p_membership_kind, 'included'), p_override_json, p_notes
  )
  ON CONFLICT (chain_contract_id, hospital_org_id) DO UPDATE
    SET membership_kind = EXCLUDED.membership_kind,
        binding_rate_card_override = EXCLUDED.binding_rate_card_override,
        removed_at = NULL,
        notes = EXCLUDED.notes
  RETURNING id INTO v_id;

  INSERT INTO public.founder_action_log (actor_user_id, actor_email, op_name, target_table, target_row_id, after_value)
  VALUES (auth.uid(), v_email, 'chain_membership_added', 'hospital_chain_membership', v_id, jsonb_build_object('chain_contract_id', p_chain_contract_id, 'hospital_org_id', p_hospital_org_id, 'kind', p_membership_kind));

  RETURN v_id;
END;
$function$;

-- public.create_chain_master_contract(p_chain_name text, p_parent_org_id uuid, p_contract_code text, p_master_tier text, p_rate_card_json jsonb, p_notes text)
--   founder_action_log columns now: actor_user_id, actor_email, op_name, target_table, target_row_id, after_value
CREATE OR REPLACE FUNCTION public.create_chain_master_contract(p_chain_name text, p_parent_org_id uuid, p_contract_code text, p_master_tier text, p_rate_card_json jsonb, p_notes text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_id uuid;
  v_email text;
BEGIN
  IF NOT public.is_founder() THEN
    RAISE EXCEPTION 'forbidden';
  END IF;

  v_email := (auth.jwt()->>'email');

  INSERT INTO public.hospital_chain_master_contracts (
    chain_name, parent_org_id, contract_code, master_tier, rate_card_json, notes, created_by
  ) VALUES (
    p_chain_name, p_parent_org_id, p_contract_code, p_master_tier,
    COALESCE(p_rate_card_json, '{}'::jsonb), p_notes, auth.uid()
  )
  RETURNING id INTO v_id;

  INSERT INTO public.founder_action_log (actor_user_id, actor_email, op_name, target_table, target_row_id, after_value)
  VALUES (auth.uid(), v_email, 'chain_contract_created', 'hospital_chain_master_contracts', v_id, jsonb_build_object('chain_name', p_chain_name, 'tier', p_master_tier));

  RETURN v_id;
END;
$function$;

-- public.fn_founder_onboarding_create_hire(p_hire_name text, p_hire_email text, p_role_title text, p_start_date date, p_mentor_name text)
--   founder_action_log columns now: actor_user_id, op_name, after_value, actor_email
CREATE OR REPLACE FUNCTION public.fn_founder_onboarding_create_hire(p_hire_name text, p_hire_email text, p_role_title text, p_start_date date, p_mentor_name text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_id uuid;
BEGIN
  IF NOT is_founder() THEN
    RAISE EXCEPTION 'forbidden';
  END IF;

  INSERT INTO founder_onboarding_hires (hire_name, hire_email, role_title, start_date, mentor_name)
  VALUES (p_hire_name, p_hire_email, p_role_title, COALESCE(p_start_date, CURRENT_DATE), p_mentor_name)
  RETURNING id INTO v_id;

  PERFORM fn_founder_onboarding_seed_items(v_id);

  INSERT INTO founder_action_log (actor_user_id, op_name, after_value, actor_email)
  VALUES (auth.uid(), 'founder_onboarding_create_hire', jsonb_build_object('hire_id', v_id, 'name', p_hire_name, 'role', p_role_title), (auth.jwt()->>'email'));

  RETURN v_id;
END;
$function$;

-- public.fn_founder_onboarding_set_status(p_hire_id uuid, p_status text)
--   founder_action_log columns now: actor_user_id, op_name, after_value, actor_email
CREATE OR REPLACE FUNCTION public.fn_founder_onboarding_set_status(p_hire_id uuid, p_status text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NOT is_founder() THEN
    RAISE EXCEPTION 'forbidden';
  END IF;

  IF p_status NOT IN ('active','completed','offboarded') THEN
    RAISE EXCEPTION 'invalid status';
  END IF;

  UPDATE founder_onboarding_hires
     SET status = p_status, updated_at = now()
   WHERE id = p_hire_id;

  INSERT INTO founder_action_log (actor_user_id, op_name, after_value, actor_email)
  VALUES (auth.uid(), 'founder_onboarding_set_status', jsonb_build_object('hire_id', p_hire_id, 'status', p_status), (auth.jwt()->>'email'));
END;
$function$;

-- public.fn_founder_onboarding_toggle_item(p_item_id uuid, p_done boolean, p_note text)
--   founder_action_log columns now: actor_user_id, op_name, after_value, actor_email
CREATE OR REPLACE FUNCTION public.fn_founder_onboarding_toggle_item(p_item_id uuid, p_done boolean, p_note text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NOT is_founder() THEN
    RAISE EXCEPTION 'forbidden';
  END IF;

  UPDATE founder_onboarding_checklist_items
     SET done = p_done,
         done_at = CASE WHEN p_done THEN now() ELSE NULL END,
         done_note = p_note
   WHERE id = p_item_id;

  INSERT INTO founder_action_log (actor_user_id, op_name, after_value, actor_email)
  VALUES (auth.uid(), 'founder_onboarding_toggle_item', jsonb_build_object('item_id', p_item_id, 'done', p_done), (auth.jwt()->>'email'));
END;
$function$;

-- public.founder_log_vip_touchpoint(p_vip_contact_id uuid, p_touchpoint_kind text, p_outcome text, p_summary text)
--   founder_action_log columns now: actor_user_id, op_name, actor_email, after_value
CREATE OR REPLACE FUNCTION public.founder_log_vip_touchpoint(p_vip_contact_id uuid, p_touchpoint_kind text, p_outcome text, p_summary text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE new_id uuid;
BEGIN
  IF NOT is_founder() THEN RAISE EXCEPTION 'forbidden'; END IF;
  INSERT INTO public.hospital_vip_touchpoints(vip_contact_id, touchpoint_kind, outcome, summary, recorded_by_email)
  VALUES (p_vip_contact_id, p_touchpoint_kind, p_outcome, p_summary, (auth.jwt()->>'email'))
  RETURNING id INTO new_id;

  UPDATE public.hospital_vip_contacts
     SET last_contacted_at = now(), updated_at = now()
   WHERE id = p_vip_contact_id;

  INSERT INTO public.founder_action_log(actor_user_id, op_name, actor_email, after_value)
  VALUES (auth.uid(), 'vip_touchpoint_logged', (auth.jwt()->>'email'), jsonb_build_object('vip_contact_id', p_vip_contact_id, 'kind', p_touchpoint_kind, 'outcome', p_outcome));

  RETURN new_id;
END;
$function$;

-- public.founder_night_shift_approve(p_id uuid, p_note text)
--   founder_action_log columns now: actor_user_id, op_name, actor_email, target_table, target_row_id, reason
CREATE OR REPLACE FUNCTION public.founder_night_shift_approve(p_id uuid, p_note text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NOT is_founder() THEN RAISE EXCEPTION 'forbidden'; END IF;
  UPDATE engineer_night_shift_approval_queue
     SET status = 'approved',
         decided_at = now(),
         decided_by_email = (auth.jwt()->>'email'),
         decision_note = p_note
   WHERE id = p_id AND status = 'pending';
  INSERT INTO founder_action_log(actor_user_id, op_name, actor_email, target_table, target_row_id, reason)
  VALUES (auth.uid(), 'night_shift_approve', (auth.jwt()->>'email'), 'night_shift_queue', p_id, p_note);
END;
$function$;

-- public.founder_night_shift_reject(p_id uuid, p_note text)
--   founder_action_log columns now: actor_user_id, op_name, actor_email, target_table, target_row_id, reason
CREATE OR REPLACE FUNCTION public.founder_night_shift_reject(p_id uuid, p_note text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NOT is_founder() THEN RAISE EXCEPTION 'forbidden'; END IF;
  UPDATE engineer_night_shift_approval_queue
     SET status = 'rejected',
         decided_at = now(),
         decided_by_email = (auth.jwt()->>'email'),
         decision_note = p_note
   WHERE id = p_id AND status = 'pending';
  INSERT INTO founder_action_log(actor_user_id, op_name, actor_email, target_table, target_row_id, reason)
  VALUES (auth.uid(), 'night_shift_reject', (auth.jwt()->>'email'), 'night_shift_queue', p_id, p_note);
END;
$function$;

-- public.founder_safe_log_note(p_investor_name text, p_investor_email text, p_principal_rupees bigint, p_valuation_cap_rupees bigint, p_discount_pct numeric, p_expires_at timestamp with time zone, p_notes text)
--   founder_action_log columns now: actor_user_id, op_name, actor_email, after_value
CREATE OR REPLACE FUNCTION public.founder_safe_log_note(p_investor_name text, p_investor_email text, p_principal_rupees bigint, p_valuation_cap_rupees bigint, p_discount_pct numeric, p_expires_at timestamp with time zone, p_notes text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_id uuid;
BEGIN
  IF NOT is_founder() THEN RAISE EXCEPTION 'forbidden'; END IF;
  INSERT INTO investor_safe_notes(investor_name, investor_email, principal_rupees, valuation_cap_rupees, discount_pct, expires_at, notes)
  VALUES (p_investor_name, p_investor_email, p_principal_rupees, p_valuation_cap_rupees, p_discount_pct, p_expires_at, p_notes)
  RETURNING id INTO v_id;

  INSERT INTO founder_action_log(actor_user_id, op_name, actor_email, after_value)
  VALUES (auth.uid(), 'safe.note.logged', (auth.jwt()->>'email'), jsonb_build_object('safe_id', v_id, 'investor', p_investor_name, 'principal', p_principal_rupees));
  RETURN v_id;
END;$function$;

-- public.founder_safe_log_queue_action(p_safe_id uuid, p_action_type text, p_priority text, p_due_by timestamp with time zone, p_notes text)
--   founder_action_log columns now: actor_user_id, op_name, actor_email, after_value
CREATE OR REPLACE FUNCTION public.founder_safe_log_queue_action(p_safe_id uuid, p_action_type text, p_priority text, p_due_by timestamp with time zone, p_notes text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE v_id uuid;
BEGIN
  IF NOT is_founder() THEN RAISE EXCEPTION 'forbidden'; END IF;
  INSERT INTO investor_safe_refresh_queue(safe_id, action_type, priority, due_by, notes)
  VALUES (p_safe_id, p_action_type, COALESCE(p_priority,'normal'), p_due_by, p_notes)
  RETURNING id INTO v_id;

  INSERT INTO founder_action_log(actor_user_id, op_name, actor_email, after_value)
  VALUES (auth.uid(), 'safe.queue.created', (auth.jwt()->>'email'), jsonb_build_object('queue_id', v_id, 'safe_id', p_safe_id, 'action_type', p_action_type, 'priority', p_priority));
  RETURN v_id;
END;$function$;

-- public.founder_safe_log_resolve(p_queue_id uuid, p_outcome text, p_notes text)
--   founder_action_log columns now: actor_user_id, op_name, actor_email, after_value
CREATE OR REPLACE FUNCTION public.founder_safe_log_resolve(p_queue_id uuid, p_outcome text, p_notes text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NOT is_founder() THEN RAISE EXCEPTION 'forbidden'; END IF;
  UPDATE investor_safe_refresh_queue
     SET status = CASE WHEN p_outcome='dismissed' THEN 'dismissed' ELSE 'done' END,
         completed_at = now(),
         notes = COALESCE(p_notes, notes)
   WHERE id = p_queue_id;

  INSERT INTO founder_action_log(actor_user_id, op_name, actor_email, after_value)
  VALUES (auth.uid(), 'safe.queue.resolved', (auth.jwt()->>'email'), jsonb_build_object('queue_id', p_queue_id, 'outcome', p_outcome));
  RETURN true;
END;$function$;

-- public.rpc_r1646_mark_status(p_assignment_id uuid, p_new_status text, p_declined_reason text)
--   founder_action_log columns now: actor_user_id, actor_email, op_name, after_value
CREATE OR REPLACE FUNCTION public.rpc_r1646_mark_status(p_assignment_id uuid, p_new_status text, p_declined_reason text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_email text := (auth.jwt()->>'email');
BEGIN
  IF NOT is_founder() THEN RAISE EXCEPTION 'forbidden'; END IF;
  IF p_new_status NOT IN ('pending','signed','declined','overdue','waived') THEN
    RAISE EXCEPTION 'invalid status';
  END IF;

  UPDATE culture_deck_signature_assignments
     SET status = p_new_status,
         signed_at = CASE WHEN p_new_status = 'signed' THEN COALESCE(signed_at, now()) ELSE signed_at END,
         declined_reason = CASE WHEN p_new_status = 'declined' THEN p_declined_reason ELSE declined_reason END,
         updated_at = now()
   WHERE id = p_assignment_id;

  INSERT INTO founder_action_log(actor_user_id, actor_email, op_name, after_value)
  VALUES (auth.uid(), v_email, 'r1646_mark_status', jsonb_build_object('assignment_id', p_assignment_id, 'new_status', p_new_status, 'actor_email', v_email));
END;
$function$;

-- public.rpc_r1646_record_followup(p_assignment_id uuid, p_channel text, p_outcome text, p_notes text)
--   founder_action_log columns now: actor_user_id, actor_email, op_name, after_value
CREATE OR REPLACE FUNCTION public.rpc_r1646_record_followup(p_assignment_id uuid, p_channel text, p_outcome text, p_notes text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_id uuid;
  v_email text := (auth.jwt()->>'email');
BEGIN
  IF NOT is_founder() THEN RAISE EXCEPTION 'forbidden'; END IF;
  INSERT INTO culture_deck_signature_followups(assignment_id, channel, outcome, notes, created_by_email)
  VALUES (p_assignment_id, p_channel, p_outcome, p_notes, v_email)
  RETURNING id INTO v_id;

  UPDATE culture_deck_signature_assignments
     SET followup_count = followup_count + 1,
         last_followup_at = now(),
         updated_at = now()
   WHERE id = p_assignment_id;

  INSERT INTO founder_action_log(actor_user_id, actor_email, op_name, after_value)
  VALUES (auth.uid(), v_email, 'r1646_record_followup', jsonb_build_object('assignment_id', p_assignment_id, 'channel', p_channel, 'actor_email', v_email));
  RETURN v_id;
END;
$function$;

-- public.set_chain_contract_status(p_chain_contract_id uuid, p_new_status text, p_reason text)
--   founder_action_log columns now: actor_user_id, actor_email, op_name, target_table, target_row_id, after_value
CREATE OR REPLACE FUNCTION public.set_chain_contract_status(p_chain_contract_id uuid, p_new_status text, p_reason text)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_email text;
BEGIN
  IF NOT public.is_founder() THEN
    RAISE EXCEPTION 'forbidden';
  END IF;

  IF p_new_status NOT IN ('draft','active','suspended','terminated') THEN
    RAISE EXCEPTION 'invalid_status';
  END IF;

  v_email := (auth.jwt()->>'email');

  UPDATE public.hospital_chain_master_contracts
     SET status = p_new_status,
         updated_at = now()
   WHERE id = p_chain_contract_id;

  INSERT INTO public.founder_action_log (actor_user_id, actor_email, op_name, target_table, target_row_id, after_value)
  VALUES (auth.uid(), v_email, 'chain_contract_status_changed', 'hospital_chain_master_contracts', p_chain_contract_id, jsonb_build_object('new_status', p_new_status, 'reason', p_reason));

  RETURN true;
END;
$function$;

-- =====================================================================
-- VERIFY
-- =====================================================================
DO $gate$
DECLARE
  v_names  text[] := ARRAY[
    'add_chain_membership',
    'create_chain_master_contract',
    'fn_founder_onboarding_create_hire',
    'fn_founder_onboarding_set_status',
    'fn_founder_onboarding_toggle_item',
    'founder_log_vip_touchpoint',
    'founder_night_shift_approve',
    'founder_night_shift_reject',
    'founder_safe_log_note',
    'founder_safe_log_queue_action',
    'founder_safe_log_resolve',
    'rpc_r1646_mark_status',
    'rpc_r1646_record_followup',
    'set_chain_contract_status'
  ];
  v_bad    text;
  v_extra  text;
  v_before int;
  v_after  int;
  v_id     uuid;
  v_actor  uuid;
  v_op     text;
BEGIN
  -- 1. every function still exists, exactly once
  SELECT string_agg(x, ', ') INTO v_bad
    FROM unnest(v_names) x
   WHERE NOT EXISTS (SELECT 1 FROM pg_proc p
                      WHERE p.pronamespace='public'::regnamespace AND p.proname = x);
  IF v_bad IS NOT NULL THEN
    RAISE EXCEPTION 'round 3793 VERIFY FAILED: function(s) vanished: %', v_bad;
  END IF;

  SELECT string_agg(q.proname || ' x' || q.c, ', ') INTO v_extra
    FROM (SELECT p.proname, count(*) AS c FROM pg_proc p
           WHERE p.pronamespace='public'::regnamespace AND p.proname = ANY(v_names)
           GROUP BY p.proname) q
   WHERE q.c > 1;
  IF v_extra IS NOT NULL THEN
    RAISE EXCEPTION 'round 3793 VERIFY FAILED: extra overload(s): %', v_extra;
  END IF;

  -- 2. no founder_action_log INSERT in the schema omits actor_user_id any more
  SELECT string_agg(DISTINCT q.proname, ', ') INTO v_bad
    FROM (
      SELECT p.proname, m[1] AS collist
        FROM pg_proc p
        CROSS JOIN LATERAL regexp_matches(pg_get_functiondef(p.oid),
            'INSERT[[:space:]]+INTO[[:space:]]+(?:public\.)?founder_action_log[[:space:]]*\(([^)]*)\)', 'gi') m
       WHERE p.pronamespace='public'::regnamespace
         AND p.prolang=(SELECT oid FROM pg_language WHERE lanname='plpgsql')
    ) q
   WHERE q.collist !~* 'actor_user_id' OR q.collist !~* 'actor_email' OR q.collist !~* 'op_name';
  IF v_bad IS NOT NULL THEN
    RAISE EXCEPTION 'round 3793 VERIFY FAILED: INSERT still omits a NOT NULL column in: %', v_bad;
  END IF;

  -- 3. EXECUTE one for real, then undo it
  PERFORM set_config('request.jwt.claims',
    json_build_object('sub','756a3373-1077-470e-bc0a-79b8d6673ef4','role','authenticated',
                      'email','ganesh1431.dhanavath@gmail.com')::text, true);
  SELECT count(*) INTO v_before FROM public.founder_action_log;
  BEGIN
    v_id := public.founder_safe_log_note('ROUND3793 PROBE','probe@equipseva.invalid',
              1000000, 5000000, 20.0, now() + interval '30 days', 'round3793 verification probe');
    SELECT count(*) INTO v_after FROM public.founder_action_log;
    SELECT l.actor_user_id, l.op_name INTO v_actor, v_op
      FROM public.founder_action_log l ORDER BY l.created_at DESC LIMIT 1;

    IF v_after <> v_before + 1 THEN
      RAISE EXCEPTION 'round 3793 VERIFY FAILED: expected 1 new founder_action_log row, got %', v_after - v_before;
    END IF;
    IF v_actor IS NULL THEN
      RAISE EXCEPTION 'round 3793 VERIFY FAILED: actor_user_id written as NULL';
    END IF;
    IF v_op <> 'safe.note.logged' THEN
      RAISE EXCEPTION 'round 3793 VERIFY FAILED: unexpected op_name %', v_op;
    END IF;

    RAISE EXCEPTION 'ROUND3793_PROBE_ROLLBACK';
  EXCEPTION
    WHEN SQLSTATE 'P0001' THEN
      IF SQLERRM <> 'ROUND3793_PROBE_ROLLBACK' THEN
        RAISE EXCEPTION 'round 3793 VERIFY FAILED during probe: %', SQLERRM;
      END IF;
  END;

  SELECT count(*) INTO v_after FROM public.founder_action_log;
  IF v_after <> v_before THEN
    RAISE EXCEPTION 'round 3793 VERIFY FAILED: probe left % row(s) behind', v_after - v_before;
  END IF;

  RAISE NOTICE 'round 3793 verified: % function(s) repaired; live write probed and rolled back cleanly',
    array_length(v_names,1);
END
$gate$;

COMMIT;
