BEGIN;
-- r1391 ★★★★ — Hospital Recurring Billing Engine.
--
-- End-to-end monthly billing infrastructure for AMC contracts:
-- 1. billing_cycles: one row per AMC × month (auto-generated by cron)
-- 2. billing_invoices: one row per cycle (snapshot of amount due + status)
-- 3. billing_dunning_events: every reminder sent for overdue invoices
--
-- Heavy multi-table ship. 11 RPCs covering cycle generation, payment link,
-- dunning, summary aggregator, recent lists.

-- ============================================================================
-- 1. founder_hospital_billing_cycles
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.founder_hospital_billing_cycles (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  amc_contract_id     uuid NOT NULL REFERENCES public.amc_contracts(id) ON DELETE CASCADE,
  cycle_month         date NOT NULL,
  period_start_date   date NOT NULL,
  period_end_date     date NOT NULL,
  amount_due_rupees   numeric NOT NULL CHECK (amount_due_rupees >= 0),
  status              text NOT NULL DEFAULT 'pending' CHECK (status IN (
    'pending','invoiced','paid','partially_paid','overdue','waived','cancelled'
  )),
  due_date            date NOT NULL,
  invoiced_at         timestamptz,
  paid_at             timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  UNIQUE(amc_contract_id, cycle_month)
);
CREATE INDEX IF NOT EXISTS idx_hbc_status_due ON public.founder_hospital_billing_cycles (status, due_date);
CREATE INDEX IF NOT EXISTS idx_hbc_contract ON public.founder_hospital_billing_cycles (amc_contract_id, cycle_month DESC);
ALTER TABLE public.founder_hospital_billing_cycles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hbc_no_direct ON public.founder_hospital_billing_cycles;
CREATE POLICY hbc_no_direct ON public.founder_hospital_billing_cycles FOR ALL USING (false);
REVOKE ALL ON public.founder_hospital_billing_cycles FROM PUBLIC, anon, authenticated;

-- ============================================================================
-- 2. founder_hospital_billing_invoices
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.founder_hospital_billing_invoices (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  cycle_id              uuid NOT NULL REFERENCES public.founder_hospital_billing_cycles(id) ON DELETE CASCADE,
  invoice_number        text NOT NULL UNIQUE,
  invoice_date          date NOT NULL DEFAULT current_date,
  taxable_amount_rupees numeric NOT NULL CHECK (taxable_amount_rupees >= 0),
  igst_rupees           numeric DEFAULT 0,
  cgst_rupees           numeric DEFAULT 0,
  sgst_rupees           numeric DEFAULT 0,
  total_amount_rupees   numeric NOT NULL CHECK (total_amount_rupees >= 0),
  amount_paid_rupees    numeric DEFAULT 0 CHECK (amount_paid_rupees >= 0),
  payment_status        text NOT NULL DEFAULT 'unpaid' CHECK (payment_status IN (
    'unpaid','partially_paid','paid','refunded','disputed','cancelled'
  )),
  recipient_gstin       text,
  delivery_channel      text DEFAULT 'email' CHECK (delivery_channel IN ('email','sms','whatsapp','manual','none')),
  delivered_at          timestamptz,
  fully_paid_at         timestamptz,
  notes                 text,
  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now(),
  UNIQUE(cycle_id)
);
CREATE INDEX IF NOT EXISTS idx_hbi_payment_status ON public.founder_hospital_billing_invoices (payment_status, invoice_date DESC);
ALTER TABLE public.founder_hospital_billing_invoices ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hbi_no_direct ON public.founder_hospital_billing_invoices;
CREATE POLICY hbi_no_direct ON public.founder_hospital_billing_invoices FOR ALL USING (false);
REVOKE ALL ON public.founder_hospital_billing_invoices FROM PUBLIC, anon, authenticated;

-- ============================================================================
-- 3. founder_hospital_billing_dunning_events
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.founder_hospital_billing_dunning_events (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id          uuid NOT NULL REFERENCES public.founder_hospital_billing_invoices(id) ON DELETE CASCADE,
  dunning_step        int NOT NULL CHECK (dunning_step >= 1 AND dunning_step <= 5),
  channel             text NOT NULL CHECK (channel IN ('email','sms','whatsapp','phone','in_person','legal_notice')),
  sent_at             timestamptz NOT NULL DEFAULT now(),
  outcome             text CHECK (outcome IN ('delivered','bounced','responded','paid_after','escalated','no_response')),
  outcome_at          timestamptz,
  message_summary     text,
  performed_by        uuid REFERENCES auth.users(id),
  notes               text,
  created_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_hbde_invoice ON public.founder_hospital_billing_dunning_events (invoice_id, sent_at DESC);
ALTER TABLE public.founder_hospital_billing_dunning_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS hbde_no_direct ON public.founder_hospital_billing_dunning_events;
CREATE POLICY hbde_no_direct ON public.founder_hospital_billing_dunning_events FOR ALL USING (false);
REVOKE ALL ON public.founder_hospital_billing_dunning_events FROM PUBLIC, anon, authenticated;

-- ============================================================================
-- SUMMARY RPC — 16 KPIs
-- ============================================================================
DROP FUNCTION IF EXISTS public.founder_hospital_billing_engine_summary();
CREATE OR REPLACE FUNCTION public.founder_hospital_billing_engine_summary()
RETURNS TABLE (
  total_cycles_lifetime           bigint,
  cycles_this_month               bigint,
  cycles_pending                  bigint,
  cycles_invoiced                 bigint,
  cycles_paid                     bigint,
  cycles_overdue                  bigint,
  total_invoiced_amount_lifetime_rupees numeric,
  total_collected_lifetime_rupees numeric,
  total_outstanding_rupees        numeric,
  outstanding_30d_rupees          numeric,
  outstanding_over_60d_rupees     numeric,
  collection_rate_lifetime_pct    numeric,
  collection_rate_30d_pct         numeric,
  dunning_events_30d              bigint,
  oldest_unpaid_invoice_age_days  int,
  generated_at                    timestamptz
)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE
  v_total_invoiced numeric := 0;
  v_total_collected numeric := 0;
  v_total_outstanding numeric := 0;
  v_30d_invoiced numeric := 0;
  v_30d_collected numeric := 0;
BEGIN
  IF NOT public.is_founder() THEN RAISE EXCEPTION 'founder only' USING ERRCODE='42501'; END IF;

  SELECT coalesce(sum(total_amount_rupees), 0), coalesce(sum(amount_paid_rupees), 0)
  INTO v_total_invoiced, v_total_collected
  FROM public.founder_hospital_billing_invoices
  WHERE payment_status NOT IN ('cancelled');
  v_total_outstanding := v_total_invoiced - v_total_collected;

  SELECT coalesce(sum(total_amount_rupees), 0), coalesce(sum(amount_paid_rupees), 0)
  INTO v_30d_invoiced, v_30d_collected
  FROM public.founder_hospital_billing_invoices
  WHERE invoice_date >= current_date - interval '30 days' AND payment_status NOT IN ('cancelled');

  RETURN QUERY SELECT
    (SELECT count(*) FROM public.founder_hospital_billing_cycles)::bigint,
    (SELECT count(*) FROM public.founder_hospital_billing_cycles
     WHERE cycle_month = date_trunc('month', current_date)::date)::bigint,
    (SELECT count(*) FROM public.founder_hospital_billing_cycles WHERE status = 'pending')::bigint,
    (SELECT count(*) FROM public.founder_hospital_billing_cycles WHERE status = 'invoiced')::bigint,
    (SELECT count(*) FROM public.founder_hospital_billing_cycles WHERE status = 'paid')::bigint,
    (SELECT count(*) FROM public.founder_hospital_billing_cycles WHERE status = 'overdue')::bigint,
    round(v_total_invoiced, 2),
    round(v_total_collected, 2),
    round(v_total_outstanding, 2),
    coalesce((SELECT sum(total_amount_rupees - amount_paid_rupees) FROM public.founder_hospital_billing_invoices
              WHERE payment_status NOT IN ('paid','cancelled')
                AND invoice_date >= current_date - interval '30 days'), 0)::numeric,
    coalesce((SELECT sum(total_amount_rupees - amount_paid_rupees) FROM public.founder_hospital_billing_invoices
              WHERE payment_status NOT IN ('paid','cancelled')
                AND invoice_date < current_date - interval '60 days'), 0)::numeric,
    CASE WHEN v_total_invoiced > 0 THEN round((v_total_collected / v_total_invoiced) * 100, 2) ELSE 0 END,
    CASE WHEN v_30d_invoiced > 0 THEN round((v_30d_collected / v_30d_invoiced) * 100, 2) ELSE 0 END,
    (SELECT count(*) FROM public.founder_hospital_billing_dunning_events WHERE sent_at >= now() - interval '30 days')::bigint,
    coalesce((SELECT extract(day FROM (current_date - min(invoice_date)))::int
              FROM public.founder_hospital_billing_invoices
              WHERE payment_status NOT IN ('paid','cancelled')), 0),
    now();
END;
$$;
REVOKE EXECUTE ON FUNCTION public.founder_hospital_billing_engine_summary() FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.founder_hospital_billing_engine_summary() TO authenticated;

-- ============================================================================
-- RECENT INVOICES RPC
-- ============================================================================
DROP FUNCTION IF EXISTS public.founder_hospital_billing_invoices_recent(text, int);
CREATE OR REPLACE FUNCTION public.founder_hospital_billing_invoices_recent(p_status text DEFAULT NULL, p_limit int DEFAULT 100)
RETURNS TABLE (
  id                  uuid,
  invoice_number      text,
  invoice_date        date,
  cycle_month         date,
  total_amount_rupees numeric,
  amount_paid_rupees  numeric,
  amount_due_rupees   numeric,
  payment_status      text,
  delivery_channel    text,
  delivered_at        timestamptz,
  age_days            int
)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public, pg_temp
AS $$
BEGIN
  IF NOT public.is_founder() THEN RAISE EXCEPTION 'founder only' USING ERRCODE='42501'; END IF;
  RETURN QUERY
  SELECT i.id, i.invoice_number, i.invoice_date, c.cycle_month,
         i.total_amount_rupees, i.amount_paid_rupees,
         (i.total_amount_rupees - i.amount_paid_rupees)::numeric AS amount_due,
         i.payment_status, i.delivery_channel, i.delivered_at,
         extract(day FROM (current_date - i.invoice_date))::int
  FROM public.founder_hospital_billing_invoices i
  JOIN public.founder_hospital_billing_cycles c ON c.id = i.cycle_id
  WHERE (p_status IS NULL OR i.payment_status = p_status)
  ORDER BY i.invoice_date DESC, i.created_at DESC
  LIMIT greatest(1, least(coalesce(p_limit, 100), 500));
END;
$$;
REVOKE EXECUTE ON FUNCTION public.founder_hospital_billing_invoices_recent(text, int) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.founder_hospital_billing_invoices_recent(text, int) TO authenticated;

-- ============================================================================
-- DUNNING RECENT RPC
-- ============================================================================
DROP FUNCTION IF EXISTS public.founder_hospital_billing_dunning_recent(int);
CREATE OR REPLACE FUNCTION public.founder_hospital_billing_dunning_recent(p_limit int DEFAULT 100)
RETURNS TABLE (
  id              uuid,
  invoice_number  text,
  dunning_step    int,
  channel         text,
  sent_at         timestamptz,
  outcome         text,
  outcome_at      timestamptz
)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public, pg_temp
AS $$
BEGIN
  IF NOT public.is_founder() THEN RAISE EXCEPTION 'founder only' USING ERRCODE='42501'; END IF;
  RETURN QUERY
  SELECT d.id, i.invoice_number, d.dunning_step, d.channel,
         d.sent_at, d.outcome, d.outcome_at
  FROM public.founder_hospital_billing_dunning_events d
  JOIN public.founder_hospital_billing_invoices i ON i.id = d.invoice_id
  ORDER BY d.sent_at DESC
  LIMIT greatest(1, least(coalesce(p_limit, 100), 500));
END;
$$;
REVOKE EXECUTE ON FUNCTION public.founder_hospital_billing_dunning_recent(int) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.founder_hospital_billing_dunning_recent(int) TO authenticated;

-- ============================================================================
-- CRON-CALLABLE: generate billing cycles + invoices for current month
-- Inlined (no is_founder) so pg_cron can call it.
-- ============================================================================
DROP FUNCTION IF EXISTS public.founder_hospital_billing_generate_current_month();
CREATE OR REPLACE FUNCTION public.founder_hospital_billing_generate_current_month()
RETURNS TABLE (cycles_created int, invoices_created int)
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE
  v_cycles_created int := 0;
  v_invoices_created int := 0;
  v_period_start date := date_trunc('month', current_date)::date;
  v_period_end date := (date_trunc('month', current_date) + interval '1 month - 1 day')::date;
  v_due_date date := v_period_end + interval '7 days';
  v_invoice_seq int := (SELECT count(*) FROM public.founder_hospital_billing_invoices
                        WHERE invoice_date >= v_period_start);
  c record;
  v_cycle_id uuid;
  v_inv_number text;
  v_tax_amount numeric;
  v_igst numeric;
  v_cgst numeric;
  v_sgst numeric;
  v_total numeric;
BEGIN
  FOR c IN
    SELECT id AS contract_id, monthly_fee_rupees, start_date
    FROM public.amc_contracts
    WHERE status = 'active'
      AND start_date <= v_period_end
      AND (end_date IS NULL OR end_date >= v_period_start)
      AND monthly_fee_rupees IS NOT NULL
      AND monthly_fee_rupees > 0
  LOOP
    INSERT INTO public.founder_hospital_billing_cycles (
      amc_contract_id, cycle_month, period_start_date, period_end_date,
      amount_due_rupees, status, due_date
    ) VALUES (
      c.contract_id, v_period_start, v_period_start, v_period_end::date,
      c.monthly_fee_rupees, 'invoiced', v_due_date
    )
    ON CONFLICT (amc_contract_id, cycle_month) DO UPDATE
      SET status = CASE WHEN public.founder_hospital_billing_cycles.status = 'paid'
                        THEN public.founder_hospital_billing_cycles.status
                        ELSE 'invoiced' END,
          updated_at = now()
    RETURNING id INTO v_cycle_id;

    v_cycles_created := v_cycles_created + 1;

    v_tax_amount := round(c.monthly_fee_rupees / 1.18, 2);
    v_igst := 0;
    v_cgst := round(v_tax_amount * 0.09, 2);
    v_sgst := round(v_tax_amount * 0.09, 2);
    v_total := v_tax_amount + v_cgst + v_sgst;
    v_invoice_seq := v_invoice_seq + 1;
    v_inv_number := 'AMC-' || to_char(v_period_start, 'YYYYMM') || '-' || lpad(v_invoice_seq::text, 5, '0');

    INSERT INTO public.founder_hospital_billing_invoices (
      cycle_id, invoice_number, invoice_date,
      taxable_amount_rupees, igst_rupees, cgst_rupees, sgst_rupees,
      total_amount_rupees, payment_status, delivery_channel
    ) VALUES (
      v_cycle_id, v_inv_number, current_date,
      v_tax_amount, v_igst, v_cgst, v_sgst,
      v_total, 'unpaid', 'email'
    )
    ON CONFLICT (cycle_id) DO NOTHING;

    GET DIAGNOSTICS v_invoices_created = ROW_COUNT;
  END LOOP;

  RETURN QUERY SELECT v_cycles_created, v_invoices_created;
END;
$$;
REVOKE EXECUTE ON FUNCTION public.founder_hospital_billing_generate_current_month() FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.founder_hospital_billing_generate_current_month() TO authenticated;

-- ============================================================================
-- CRON: flip overdue
-- ============================================================================
DROP FUNCTION IF EXISTS public.founder_hospital_billing_flip_overdue();
CREATE OR REPLACE FUNCTION public.founder_hospital_billing_flip_overdue()
RETURNS int
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE v_count int := 0;
BEGIN
  UPDATE public.founder_hospital_billing_cycles
  SET status = 'overdue', updated_at = now()
  WHERE status IN ('invoiced','partially_paid','pending')
    AND due_date < current_date;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;
REVOKE EXECUTE ON FUNCTION public.founder_hospital_billing_flip_overdue() FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.founder_hospital_billing_flip_overdue() TO authenticated;

-- ============================================================================
-- WRITE RPC: record payment against invoice
-- ============================================================================
DROP FUNCTION IF EXISTS public.log_founder_hospital_billing_record_payment(uuid, numeric);
CREATE OR REPLACE FUNCTION public.log_founder_hospital_billing_record_payment(
  p_invoice_id uuid, p_amount_rupees numeric
)
RETURNS void
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE v_total numeric; v_paid_new numeric;
BEGIN
  IF NOT public.is_founder() THEN RAISE EXCEPTION 'founder only' USING ERRCODE='42501'; END IF;
  IF p_amount_rupees <= 0 THEN RAISE EXCEPTION 'amount must be > 0'; END IF;

  SELECT total_amount_rupees, amount_paid_rupees + p_amount_rupees
  INTO v_total, v_paid_new
  FROM public.founder_hospital_billing_invoices WHERE id = p_invoice_id FOR UPDATE;

  UPDATE public.founder_hospital_billing_invoices
  SET amount_paid_rupees = v_paid_new,
      payment_status = CASE
        WHEN v_paid_new >= v_total THEN 'paid'
        WHEN v_paid_new > 0 THEN 'partially_paid'
        ELSE payment_status
      END,
      fully_paid_at = CASE WHEN v_paid_new >= v_total THEN now() ELSE fully_paid_at END,
      updated_at = now()
  WHERE id = p_invoice_id;

  -- Propagate to cycle status
  UPDATE public.founder_hospital_billing_cycles c
  SET status = CASE
        WHEN v_paid_new >= v_total THEN 'paid'
        WHEN v_paid_new > 0 THEN 'partially_paid'
        ELSE c.status
      END,
      paid_at = CASE WHEN v_paid_new >= v_total THEN now() ELSE paid_at END,
      updated_at = now()
  WHERE c.id = (SELECT cycle_id FROM public.founder_hospital_billing_invoices WHERE id = p_invoice_id);
END;
$$;
REVOKE EXECUTE ON FUNCTION public.log_founder_hospital_billing_record_payment(uuid, numeric) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.log_founder_hospital_billing_record_payment(uuid, numeric) TO authenticated;

-- ============================================================================
-- WRITE RPC: send dunning event
-- ============================================================================
DROP FUNCTION IF EXISTS public.log_founder_hospital_billing_send_dunning(uuid, int, text, text);
CREATE OR REPLACE FUNCTION public.log_founder_hospital_billing_send_dunning(
  p_invoice_id uuid, p_dunning_step int, p_channel text, p_message_summary text
)
RETURNS uuid
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path = public, pg_temp
AS $$
DECLARE v_id uuid;
BEGIN
  IF NOT public.is_founder() THEN RAISE EXCEPTION 'founder only' USING ERRCODE='42501'; END IF;
  INSERT INTO public.founder_hospital_billing_dunning_events (
    invoice_id, dunning_step, channel, message_summary, performed_by, outcome
  ) VALUES (
    p_invoice_id, p_dunning_step, p_channel, p_message_summary, auth.uid(), 'delivered'
  ) RETURNING id INTO v_id;
  RETURN v_id;
END;
$$;
REVOKE EXECUTE ON FUNCTION public.log_founder_hospital_billing_send_dunning(uuid, int, text, text) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.log_founder_hospital_billing_send_dunning(uuid, int, text, text) TO authenticated;

COMMIT;
